// AUTO-GENERATED FILE. DO NOT MODIFY.

// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;
import ballerina/mime;

listener http:Listener ep0 = new (9090);

service / on ep0 {
    # Delete a directory.
    #
    # + id - The ID of the directory to delete
    # + return - returns can be any of following types
    # http:Ok (successfully deleted the directory)
    # http:Forbidden (no permission to delete the directory)
    # http:NotFound (the directory does not exist)
    resource function delete p/directory/[DirectoryId id]() returns DeleteDirectoryResponse|http:Forbidden|http:NotFound {
        return <DeleteDirectoryResponse>{success: true};
    }

    # Deletes a dictionary entry.
    #
    # + id - The ID of the dictionary entry to delete
    # + X\-Signavio\-ID - (authtoken)
    # + Cookie - JSESSIONID=(jsessionid); LBROUTEID=(lbrouteid)
    # + return - returns can be any of following types
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized. Authentication failed due to incorrect credentials.  Please re-check the credentials provided or the `x-signavio-id` token.)
    # http:NotFound (No entry with the given ID exists.)
    resource function delete p/glossary/[string id](@http:Header {name: "X-Signavio-ID"} string xSignavioID, @http:Header {name: "Cookie"} string cookie) returns SuccessResponse|http:Unauthorized|http:NotFound {
        return {success: true};
    }

    # Delete initiative
    #
    # + initiativeId - The id of the initiative to delete
    # + return - returns can be any of following types
    # http:NoContent (Successfully deleted initiative)
    # http:BadRequest (Trying to delete default initiative)
    # http:Unauthorized (User is not authorized to delete initiatives)
    # http:NotFound (Initiative not found)
    # http:Forbidden (User does not have permission to delete the given initiative)
    resource function delete transformationmanager/v1/initiatives/[UUID initiativeId]() returns http:NoContent|ErrorResponseBadRequest|ErrorResponseUnauthorized|ErrorResponseNotFound|ErrorResponseForbidden {
        return http:NO_CONTENT;
    }

    # This endpoint implements an OData service endpoint according to version 4.0 of
    # the OData Protocol specification.
    #
    # + entitySetName - The name for the entity set (in this case, the oData view). Can be returned by calling the /$metadata endpoint
    # + return - returns can be any of following types
    # http:Ok (Data for the given entity, returned as a JSON schema)
    resource function get pi/signal/odata/v1/[string entitySetName](@http:Query {name: "$count"} boolean? dollarCount, @http:Query {name: "$deltatoken"} string? dollarDeltatoken, @http:Query {name: "$expand"} string? dollarExpand, @http:Query {name: "$filter"} string? dollarFilter, @http:Query {name: "$format"} string? dollarFormat, @http:Query {name: "$id"} string? dollarId, @http:Query {name: "$orderby"} string? dollarOrderby, @http:Query {name: "$search"} string? dollarSearch, @http:Query {name: "$select"} string[] dollarSelect = [], int? skip = (), @http:Query {name: "$skiptoken"} string? dollarSkiptoken = (), @http:Query {name: "$top"} int? dollarTop = ()) returns OdataOutput|ODataErrorResponseBadRequest|ODataErrorResponseUnauthorized|ODataErrorResponseForbidden|ODataErrorResponseNotFound|ODataErrorResponseNotAcceptable|ODataErrorResponseUnsupportedMediaType|ODataErrorResponseUnprocessableEntity|ODataErrorResponseInternalServerError|ODataErrorResponseServiceUnavailable|ODataErrorResponseGatewayTimeout {
        return <OdataOutput>{
            atOdataContext: "https://api.eu.signavio.cloud.sap/pi/signal/odata/v1/$metadata#" + entitySetName,
            atOdataCount: 2,
            value: [
                {caseId: "case-1001", cycleTime: 42.5},
                {caseId: "case-1002", cycleTime: 37.1}
            ]
        };
    }

    # List of cases resources
    #
    # + return - returns can be any of following types
    # http:Ok (OK)
    resource function get spg/report/v1/cases(@http:Query {name: "filter[processId]"} string? filterProcessId, @http:Header {name: "Content-Type"} "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json", string 'field = "id,creator", string include = "creator,tasks,variables", @http:Query {name: "page[limit]"} int pageLimit = 100, @http:Query {name: "page[offset]"} int pageOffset = 0) returns CasesResourcesResponseSchema|CasesResourceReferencesResponseSchemaAccepted|FailureBadRequest|FailureUnauthorized|FailureForbidden|FailureNotFound|FailureMethodNotAllowed|FailureInternalServerError|FailureNotImplemented|FailureBadGateway|FailureServiceUnavailable|FailureGatewayTimeout|FailureHttpVersionNotSupported {
        return <CasesResourcesResponseSchema>{
            data: [
                {
                    id: {date: "2026-07-01", timestamp: 1751328000},
                    'type: "Cases",
                    attributes: {
                        creator: {id: {date: "2026-07-01", timestamp: 1751328000}, 'type: "Users"}
                    }
                }
            ]
        };
    }

    # Cases resource
    #
    # + return - returns can be any of following types
    # http:Ok (OK)
    resource function get spg/report/v1/cases/[string id](@http:Header {name: "Content-Type"} "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json", string 'field = "id,creator", string include = "creator,tasks,variables") returns CasesResourceResponseSchema|FailureBadRequest|FailureUnauthorized|FailureForbidden|FailureNotFound|FailureMethodNotAllowed|FailureInternalServerError|FailureNotImplemented|FailureBadGateway|FailureServiceUnavailable|FailureGatewayTimeout|FailureHttpVersionNotSupported {
        return <CasesResourceResponseSchema>{
            data: {
                id: {date: "2026-07-01", timestamp: 1751328000},
                'type: "Cases",
                attributes: {
                    creator: {id: {date: "2026-07-01", timestamp: 1751328000}, 'type: "Users"}
                }
            }
        };
    }

    # List of tasks resources
    #
    # + return - returns can be any of following types
    # http:Ok (OK)
    resource function get spg/report/v1/tasks(@http:Query {name: "filter[id]"} string? filterId, @http:Query {name: "filter[case.id]"} string? filterCaseId, @http:Query {name: "filter[assignee.email]"} string? filterAssigneeEmail, @http:Query {name: "filter[completed]"} string? filterCompleted, @http:Header {name: "Content-Type"} "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json", string fields = "id", string include = "case", @http:Query {name: "page[limit]"} int pageLimit = 100, @http:Query {name: "page[offset]"} int pageOffset = 0) returns TasksResourcesResponseSchema|TasksResourceReferencesResponseSchemaAccepted|FailureBadRequest|FailureUnauthorized|FailureForbidden|FailureNotFound|FailureMethodNotAllowed|FailureInternalServerError|FailureNotImplemented|FailureBadGateway|FailureServiceUnavailable|FailureGatewayTimeout|FailureHttpVersionNotSupported {
        return <TasksResourcesResponseSchema>{
            data: [
                {
                    id: {date: "2026-07-02", timestamp: 1751414400},
                    'type: "Tasks",
                    attributes: {
                        case: {id: {date: "2026-07-01", timestamp: 1751328000}, 'type: "Cases"}
                    }
                }
            ]
        };
    }

    # List of users resources
    #
    # + return - returns can be any of following types
    # http:Ok (OK)
    resource function get spg/report/v1/users(@http:Query {name: "filter[id]"} string? filterId, @http:Header {name: "Content-Type"} "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json", @http:Query {name: "page[limit]"} int pageLimit = 100, @http:Query {name: "page[offset]"} int pageOffset = 0) returns UsersResourcesResponseSchema|UsersResourceReferencesResponseSchemaAccepted|FailureBadRequest|FailureUnauthorized|FailureForbidden|FailureNotFound|FailureMethodNotAllowed|FailureInternalServerError|FailureNotImplemented|FailureBadGateway|FailureServiceUnavailable|FailureGatewayTimeout|FailureHttpVersionNotSupported {
        return <UsersResourcesResponseSchema>{
            data: [
                {
                    id: {date: "2026-07-01", timestamp: 1751328000},
                    'type: "Users",
                    attributes: {}
                }
            ]
        };
    }

    # Get status of ingestion request
    #
    # + executionId - Ingestion request execution Id
    # + return - returns can be any of following types
    # http:Ok (OK)
    resource function get spi/ingestions/v1/[string executionId]/status() returns ExecutionStatusDto|http:Unauthorized|ErrorResponseDtoBadRequest|ErrorResponseDtoUnauthorized|ErrorResponseDtoNotFound|ErrorResponseDtoInternalServerError {
        // Re-auth probe: the sentinel execution id is rejected with 401 exactly once, so the
        // wrapper client must re-authenticate and replay the request to succeed. Any other
        // execution id behaves normally.
        if executionId == "reauth-probe" && nextReauthProbeCall() == 1 {
            return http:UNAUTHORIZED;
        }
        return <ExecutionStatusDto>{
            displayStatus: "Completed",
            message: "The ingestion request completed successfully.",
            status: "COMPLETED"
        };
    }

    # Retrieves your workspace's root folders' metadata.
    #
    # + return - Returns four resources, which represent a workspace's root folders
    resource function get p/directory() returns HyperMediaObject[] {
        return [
            {rel: "dir", href: "/directory/8f2c1b3a", rep: {"name": "Shared Documents", "type": "public"}},
            {rel: "dir", href: "/directory/7a9d0e4f", rep: {"name": "My Documents", "type": "private"}},
            {rel: "dir", href: "/directory/5c6b8a21", rep: {"name": "Trash", "type": "trash"}},
            {rel: "glos", href: "/glossary/2d4e6f80", rep: {"name": "Dictionary"}}
        ];
    }

    # Get meta-data of items in a given directory.
    #
    # + id - The ID of the directory to get the content of
    # + return - returns can be any of following types
    # http:Ok (Successfully provided meta-data of all items in the directory)
    resource function get p/directory/[DirectoryId id]() returns HyperMediaObject[]|http:NotFound|http:Forbidden {
        return [
            {rel: "mod", href: "/model/1a2b3c4d", rep: {"name": "Invoice Approval Process", "type": "BPMN 2.0"}},
            {rel: "dir", href: "/directory/9f8e7d6c", rep: {"name": "Procurement"}}
        ];
    }

    # Lists dictionary entries, optionally filtered by category, and with full-text search or title initial letter filter.
    #
    # + return - returns can be any of following types
    # http:Ok (A JSON representation of the search results)
    resource function get p/glossary(string? letter, string? q, string? category, string? sort, int? 'limit, int? offset, string? include, @http:Header {name: "Cookie"} string cookie, @http:Header {name: "Content-Type"} string contentType) returns DictionaryResponse[]|http:DefaultStatusCodeResponse {
        return [
            {
                rel: "gitem",
                href: "/glossary/ge-1001",
                rep: {
                    id: "ge-1001",
                    title: "Customer",
                    category: "cat-org-units",
                    categoryName: "Organizational Units",
                    description: "An external party purchasing goods or services."
                }
            }
        ];
    }

    # Retrieves the specified dictionary entry.
    #
    # + id - The ID of the dictionary entry to retrieve
    # + return - returns can be any of following types
    # http:Ok (Success)
    resource function get p/glossary/[string id](@http:Header {name: "X-Signavio-ID"} string xSignavioID, @http:Header {name: "Cookie"} string cookie) returns DictionaryResponse[]|http:Unauthorized|http:NotFound|http:DefaultStatusCodeResponse {
        return [
            {
                rel: "info",
                href: "/glossary/" + id + "/info",
                rep: {
                    id: id,
                    title: "Customer",
                    category: "cat-org-units",
                    categoryName: "Organizational Units",
                    description: "An external party purchasing goods or services.",
                    author: "user-42",
                    updated: "2026-06-30T09:15:00Z"
                }
            }
        ];
    }

    resource function get p/model/[string modelId]/'json() returns DiagramJson|http:BadRequest|http:NotFound {
        return <DiagramJson>{
            resourceId: "canvas-" + modelId,
            properties: {"name": "Invoice Approval Process", "documentation": "Approves incoming invoices."},
            childShapes: [
                {resourceId: "sid-start-event", properties: {"title": "Invoice received"}},
                {resourceId: "sid-task-1", properties: {"title": "Check invoice"}}
            ]
        };
    }

    # Get BPMN 2.0 XML
    #
    # + modelId - The ID of the model
    # + exportSubprocesses - Whether to include linked subprocesses
    # + language - Which tenant content language to use as the primary language of the exported XML
    # + return - returns can be any of following types
    # http:Ok (Success)
    # http:BadRequest (Invalid SBO)
    resource function get p/model/[string modelId]/bpmn2_0_xml(boolean? exportSubprocesses, string? language) returns xml|http:BadRequest {
        return xml `<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" id="defs-1"><process id="invoice-approval" isExecutable="false"/></definitions>`;
    }

    # Search the workspace
    #
    # + q - The search term
    # + return - JSON array containing folder and model object representations
    resource function get p/search(string q, string? types, string? contentmode, string? 'limit, string? offset, @http:Query {name: "fields_json"} string? fieldsJson) returns SearchNotModifiedResponseArrayNotModified {
        return {
            body: [
                {rel: "mod", href: "/model/1a2b3c4d", rep: {"name": "Invoice Approval Process"}},
                {rel: "search", href: "/search", rep: {"totalNrOfResults": 1}}
            ]
        };
    }

    # List initiatives
    #
    # + return - returns can be any of following types
    # http:Ok (Success)
    resource function get transformationmanager/v1/initiatives(InitiativeStatus? status, ValueDriver? valueDriver, Role? authorizationRole, UUID? createdBy, string? nameContains, UUID? hasMember, string? search, int:Signed32 pageNumber = 1, int:Signed32 pageSize = 10, "dateCreated"|"dateUpdated"|"name"|"startDate"|"endDate"|"lastActivity"|"numberOfInsights" sortBy = "dateCreated", "Ascending"|"Descending" sortOrder = "Ascending") returns Initiative[]|ErrorResponseUnauthorized|ErrorResponseForbidden {
        return [mockInitiative];
    }

    # Get initiative
    #
    # + initiativeId - The id of the initiative to retrieve
    # + return - returns can be any of following types
    # http:Ok (Success)
    resource function get transformationmanager/v1/initiatives/[UUID initiativeId]() returns Initiative|ErrorResponseUnauthorized|ErrorResponseNotFound|ErrorResponseForbidden {
        return mockInitiative;
    }

    # Get all insights
    #
    # + return - returns can be any of following types
    # http:Ok (Success)
    resource function get transformationmanager/v1/insights(string? nameContains, "OPEN"|"IN_PROGRESS"|"RESOLVED"? status, "IT_CAPACITY_PLANNING"|"IMPROVE_DEMAND_FORECAST_ACCURACY"|"IMPROVE_ON_TIME_DELIVERY"|"IMPROVE_FTE_PRODUCTIVITY"|"IMPROVE_USER_COMPLIANCE"|"INCREASE_CASH_FORECAST_ACCURACY"|"INCREASE_DAYS_PAYABLES"|"INCREASE_EFFECTIVENESS_MARKETING"|"OPERATIONAL_EXCELLENCE"|"REDUCE_HR_MANUAL_TRANSACTION"|"REDUCE_ASSET_COST"|"REDUCE_CUSTOMER_CHURN"|"REDUCE_DATA_MANAGEMENT_COST"|"REDUCE_DAYS_IN_INVENTORY"|"REDUCE_DAYS_SALES"|"REDUCE_DAYS_CLOSE_ANNUAL_BOOKS"|"REDUCE_FINANCE_COST"|"REDUCE_MANUFACTURING_CYCLE_TIME"|"REDUCE_READING_TO_INVOICE_TIME"|"REDUCE_NON_COMPLIANT_SERVICES"|"REDUCE_SUPPLY_CHAIN_PLANNING_COST"|"REDUCE_REVENUE_LOSS"|"REDUCE_SALES_COSTS"|"REDUCE_SERVICE_SUPPORT_COST"|"REDUCE_TIME_TO_FILL"|"REDUCE_TIME_TO_MARKET"|"REDUCE_LOGISTICS_COST"|"REDUCE_MANUFACTURING_COSTS"|"REDUCE_UNPLANNED_DOWNTIME"|"REDUCE_UNCOLLECTIBLE_ACCOUNTS"? valueDriver, string? createdBy, string? tag, string? assignee, string? discoveryReferenceSRI, "PROCESS_MANAGER"|"PROCESS_INTELLIGENCE"|"PROCESS_INSIGHTS"|"BENCHMARKING_ANALYTICS"|"JOURNEY_MODELER"|"SUITE_CAPABILITIES"|"PROCESS_GOVERNANCE"? discoveryReferenceApplication, string? processIntelligenceProcessId, string? processIntelligenceCanvasId, "INVESTIGATION"|"DASHBOARD"? processIntelligenceCanvasType, string? processIntelligenceWidgetId, string? processInsightsSystemId, string? processInsightsProcessFlowId, int:Signed32 pageNumber = 1, int:Signed32 pageSize = 10, "dateCreated"|"dateUpdated"|"name"|"impactScore"|"effortScore"|"priorityScore" sortBy = "dateCreated", "Ascending"|"Descending" sortOrder = "Ascending") returns Insight[]|http:Unauthorized|http:Forbidden {
        return [mockInsight];
    }

    # Get all objectives
    #
    # + return - returns can be any of following types
    # http:Ok (Success returns objectives wrapped in value array)
    resource function get transformationmanager/v1/objectives(@http:Query {name: "$count"} boolean dollarCount = false, int:Signed32 page = 0, int:Signed32 size = 10) returns ObjectivesResponse|ObjectivesErrorResponseBadRequest|ObjectivesErrorResponseUnauthorized|ObjectivesErrorResponseForbidden|ObjectivesErrorResponseInternalServerError {
        return <ObjectivesResponse>{
            count: 1,
            value: [
                {
                    sId: "Objective_reduce-cycle-time",
                    name: "Reduce order-to-cash cycle time",
                    description: "Reduce the average order-to-cash cycle time by 20 percent.",
                    attributes: [],
                    dateCreated: "2026-01-15T10:00:00Z",
                    dateUpdated: "2026-02-01T08:30:00Z"
                }
            ]
        };
    }

    # Retrieve Model
    #
    # + id - The ID of the model to be retrieved
    # + return - returns can be any of following types
    # http:Ok (Successful Operation)
    resource function get v1/model/[string id]() returns ModelResourceResponse[]|http:InternalServerError {
        return [
            {
                rel: "mod",
                href: "/model/" + id,
                rep: {
                    name: "Invoice Approval Process",
                    'type: "BPMN 2.0",
                    description: "Approves incoming invoices before payment.",
                    created: "2026-05-12T14:20:00Z"
                }
            }
        ];
    }

    # Create an API access token (login)
    #
    # + return - returns can be any of following types
    # http:Ok (Authentication successful)
    resource function post auth/v1/token(@http:Header {name: "Content-Type"} string? contentType, @http:Payload map<string> payload) returns StringOk|JsonBadRequest|JsonUnauthorized|JsonInternalServerError {
        return <StringOk>{body: "a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6"};
    }

    # Establishes a Process Manager workspace session (mocks the classic `/p/login` endpoint).
    #
    # + return - the session's X-Signavio-ID token, with a JSESSIONID cookie attached
    resource function post p/login(@http:Payload map<string> payload) returns http:Response {
        http:Response response = new;
        response.setTextPayload("mock-signavio-id");
        response.addCookie(new http:Cookie("JSESSIONID", "mock-session-id", path = "/"));
        return response;
    }

    # Add automatic measurement to existing metrics.
    #
    # + journeyId - The ID of the journey to be updated
    # + metricId - The ID of the metric to be updated
    # + return - returns can be any of following types
    # http:NoContent (Updated successfully)
    resource function post jm/v1/journeys/[string journeyId]/metrics/[string metricId]/value(@http:Payload AutomaticMeasurement payload) returns http:NoContent|http:BadRequest|http:Unauthorized|http:NotFound|http:Locked {
        return http:NO_CONTENT;
    }

    # Upload schema and data
    #
    # + return - returns can be any of following types
    # http:Ok (OK)
    resource function post spi/ingestions/v1/data(http:Request request) returns UploadSchemaAndDataResponseDtoOk|ErrorResponseDtoBadRequest|ErrorResponseDtoUnauthorized|ErrorResponseDtoInternalServerError {
        return <UploadSchemaAndDataResponseDtoOk>{body: {executionId: "exec-7f3a9c1e"}};
    }

    resource function post p/bpmn2_0\-import(http:Request request) returns BpmnImportResultOk|http:BadRequest|http:Unauthorized|http:InternalServerError {
        // Mimic the real server: the file part must be named exactly "bpmn2_0file" (the
        // @jsondata:Name wire name), otherwise the server rejects with "BPMN2_0Import.NoFile".
        // This guards against the wire name being lost in payload serialization (see sanitations
        // items 12 and 14).
        mime:Entity[]|error parts = request.getBodyParts();
        boolean hasNamedFile = false;
        if parts is mime:Entity[] {
            foreach mime:Entity part in parts {
                if part.getContentDisposition().name == "bpmn2_0file" {
                    hasNamedFile = true;
                }
            }
        }
        if !hasNamedFile {
            return <http:BadRequest>{body: "BPMN2_0Import.NoFile"};
        }
        return <BpmnImportResultOk>{
            body: {
                mainModelId: "model-1a2b3c4d",
                numCreated: 1,
                numUpdated: 0,
                createdIds: ["model-1a2b3c4d"],
                updatedIds: []
            }
        };
    }

    # Create a new directory
    #
    # + return - returns can be any of following types
    # http:Ok (Successfully created folder and returns its meta-data)
    resource function post p/directory(@http:Payload map<string> payload) returns HyperMediaObjectOk|http:InternalServerError {
        return <HyperMediaObjectOk>{
            body: {rel: "dir", href: "/directory/3e5f7a9b", rep: {"name": "New Folder"}}
        };
    }

    # Creates a dictionary entry.
    #
    # + return - returns can be any of following types
    # http:Ok (Returns a JSON object containing the created dictionary item)
    resource function post p/glossary(@http:Header {name: "X-Signavio-ID"} string xSignavioID, @http:Header {name: "Cookie"} string cookie, @http:Payload map<string> payload) returns DictionaryResponseOk|http:Unauthorized|http:Conflict|http:InternalServerError {
        return <DictionaryResponseOk>{
            body: {
                rel: "gitem",
                href: "/glossary/ge-2002",
                rep: {
                    id: "ge-2002",
                    title: "Supplier",
                    category: "cat-org-units",
                    description: "An external party providing goods or services."
                }
            }
        };
    }

    # Create initiative
    #
    # + return - returns can be any of following types
    # http:Created (Successfully created initiative)
    resource function post transformationmanager/v1/initiatives(@http:Payload IncomingInitiative payload) returns Initiative|ErrorResponseBadRequest|ErrorResponseUnauthorized|ErrorResponseForbidden {
        return mockInitiative;
    }

    # Create an insight
    #
    # + return - returns can be any of following types
    # http:Created (Successfully created insight)
    resource function post transformationmanager/v1/insights(@http:Payload IncomingInsight payload) returns Insight|http:BadRequest|http:Unauthorized|http:Forbidden {
        return mockInsight;
    }

    # Update initiative
    #
    # + initiativeId - The id of the initiative to update
    # + return - returns can be any of following types
    # http:Ok (Successfully updated initiative)
    resource function put transformationmanager/v1/initiatives/[UUID initiativeId](@http:Payload IncomingInitiative payload) returns Initiative|ErrorResponseBadRequest|ErrorResponseUnauthorized|ErrorResponseNotFound|ErrorResponseForbidden {
        return mockInitiative;
    }
}

final Initiative & readonly mockInitiative = {
    id: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    name: "Order to Cash Optimization",
    description: "Streamline the order-to-cash process across regions.",
    status: "IN_PROGRESS",
    'type: "STANDARD",
    sri: "sri:signavio:transformation:eu:initiative/3fa85f64-5717-4562-b3fc-2c963f66afa6",
    valueDrivers: ["OPERATIONAL_EXCELLENCE"],
    authorizations: [
        {
            role: "OWNER",
            targetType: "USER",
            target: {id: "9e107d9d-372b-4c81-9134-2f7f4a1c2b3d", displayName: "Alex Fischer"}
        }
    ],
    dateCreated: "2026-01-15T10:00:00Z",
    dateUpdated: "2026-02-01T08:30:00Z",
    lastActivity: "2026-02-01T08:30:00Z",
    createdBy: {
        id: "9e107d9d-372b-4c81-9134-2f7f4a1c2b3d",
        displayName: "Alex Fischer",
        email: "alex.fischer@example.com",
        userGroupIds: []
    },
    updatedBy: {
        id: "9e107d9d-372b-4c81-9134-2f7f4a1c2b3d",
        displayName: "Alex Fischer",
        email: "alex.fischer@example.com",
        userGroupIds: []
    }
};

final Insight & readonly mockInsight = {
    id: "1c9e7d5b-3a2f-4e6d-8c1b-0f9a8e7d6c5b",
    name: "Long approval times for high-value invoices",
    description: "Invoices above 10k EUR wait on average 4 days for approval.",
    status: "OPEN",
    sri: "sri:signavio:transformation:eu:insight/1c9e7d5b-3a2f-4e6d-8c1b-0f9a8e7d6c5b",
    valueDrivers: ["OPERATIONAL_EXCELLENCE"],
    authorizations: [
        {
            role: "OWNER",
            targetType: "USER",
            target: {id: "9e107d9d-372b-4c81-9134-2f7f4a1c2b3d", displayName: "Alex Fischer"}
        }
    ],
    assignees: [],
    tags: [],
    discoveries: [],
    priorityScore: 7.5,
    effortScore: 3.0,
    impactScore: 8.0,
    dateCreated: "2026-03-10T12:00:00Z",
    dateUpdated: "2026-03-12T09:45:00Z",
    createdBy: {
        id: "9e107d9d-372b-4c81-9134-2f7f4a1c2b3d",
        displayName: "Alex Fischer",
        email: "alex.fischer@example.com",
        userGroupIds: []
    },
    updatedBy: {
        id: "9e107d9d-372b-4c81-9134-2f7f4a1c2b3d",
        displayName: "Alex Fischer",
        email: "alex.fischer@example.com",
        userGroupIds: []
    }
};

// Status-code response wrapper types referenced by the mock service signatures.
// These lived in the generated service-side types.bal, which is removed in favour
// of the root package types — only the wrappers are re-declared here.

public type StringOk record {|
    *http:Ok;
    string body;
|};

public type JsonBadRequest record {|
    *http:BadRequest;
    json body;
|};

public type JsonUnauthorized record {|
    *http:Unauthorized;
    json body;
|};

public type JsonInternalServerError record {|
    *http:InternalServerError;
    json body;
|};

public type HyperMediaObjectOk record {|
    *http:Ok;
    HyperMediaObject body;
|};

public type DictionaryResponseOk record {|
    *http:Ok;
    DictionaryResponse body;
|};

public type UploadSchemaAndDataResponseDtoOk record {|
    *http:Ok;
    UploadSchemaAndDataResponseDto body;
|};

public type BpmnImportResultOk record {|
    *http:Ok;
    BpmnImportResult body;
|};

public type SearchNotModifiedResponse record {
    string rel?;
    string href?;
    record {} rep?;
};

public type SearchNotModifiedResponseArrayNotModified record {|
    *http:NotModified;
    SearchNotModifiedResponse[] body;
|};

public type CasesResourceReferencesResponseSchemaAccepted record {|
    *http:Accepted;
    CasesResourceReferencesResponseSchema body;
|};

public type TasksResourceReferencesResponseSchemaAccepted record {|
    *http:Accepted;
    TasksResourceReferencesResponseSchema body;
|};

public type UsersResourceReferencesResponseSchemaAccepted record {|
    *http:Accepted;
    UsersResourceReferencesResponseSchema body;
|};

public type ErrorResponseBadRequest record {|
    *http:BadRequest;
    json body;
|};

public type ErrorResponseUnauthorized record {|
    *http:Unauthorized;
    json body;
|};

public type ErrorResponseNotFound record {|
    *http:NotFound;
    json body;
|};

public type ErrorResponseForbidden record {|
    *http:Forbidden;
    json body;
|};

public type ErrorResponseDtoBadRequest record {|
    *http:BadRequest;
    json body;
|};

public type ErrorResponseDtoUnauthorized record {|
    *http:Unauthorized;
    json body;
|};

public type ErrorResponseDtoNotFound record {|
    *http:NotFound;
    json body;
|};

public type ErrorResponseDtoInternalServerError record {|
    *http:InternalServerError;
    json body;
|};

public type ObjectivesErrorResponseBadRequest record {|
    *http:BadRequest;
    json body;
|};

public type ObjectivesErrorResponseUnauthorized record {|
    *http:Unauthorized;
    json body;
|};

public type ObjectivesErrorResponseForbidden record {|
    *http:Forbidden;
    json body;
|};

public type ObjectivesErrorResponseInternalServerError record {|
    *http:InternalServerError;
    json body;
|};

public type FailureBadRequest record {|
    *http:BadRequest;
    json body;
|};

public type FailureUnauthorized record {|
    *http:Unauthorized;
    json body;
|};

public type FailureForbidden record {|
    *http:Forbidden;
    json body;
|};

public type FailureNotFound record {|
    *http:NotFound;
    json body;
|};

public type FailureMethodNotAllowed record {|
    *http:MethodNotAllowed;
    json body;
|};

public type FailureInternalServerError record {|
    *http:InternalServerError;
    json body;
|};

public type FailureNotImplemented record {|
    *http:NotImplemented;
    json body;
|};

public type FailureBadGateway record {|
    *http:BadGateway;
    json body;
|};

public type FailureServiceUnavailable record {|
    *http:ServiceUnavailable;
    json body;
|};

public type FailureGatewayTimeout record {|
    *http:GatewayTimeout;
    json body;
|};

public type FailureHttpVersionNotSupported record {|
    *http:HttpVersionNotSupported;
    json body;
|};

public type ODataErrorResponseBadRequest record {|
    *http:BadRequest;
    json body;
|};

public type ODataErrorResponseUnauthorized record {|
    *http:Unauthorized;
    json body;
|};

public type ODataErrorResponseForbidden record {|
    *http:Forbidden;
    json body;
|};

public type ODataErrorResponseNotFound record {|
    *http:NotFound;
    json body;
|};

public type ODataErrorResponseNotAcceptable record {|
    *http:NotAcceptable;
    json body;
|};

public type ODataErrorResponseUnsupportedMediaType record {|
    *http:UnsupportedMediaType;
    json body;
|};

public type ODataErrorResponseUnprocessableEntity record {|
    *http:UnprocessableEntity;
    json body;
|};

public type ODataErrorResponseInternalServerError record {|
    *http:InternalServerError;
    json body;
|};

public type ODataErrorResponseServiceUnavailable record {|
    *http:ServiceUnavailable;
    json body;
|};

public type ODataErrorResponseGatewayTimeout record {|
    *http:GatewayTimeout;
    json body;
|};

// Counts calls to the ingestion-status re-auth probe so the mock can reject the first attempt
// with 401 and accept the replay. Isolated + lock-guarded for safe concurrent test execution.
isolated int reauthProbeCalls = 0;

isolated function nextReauthProbeCall() returns int {
    lock {
        reauthProbeCalls += 1;
        return reauthProbeCalls;
    }
}
