// AUTO-GENERATED FILE. DO NOT MODIFY.

// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;
import ballerina/os;
import ballerina/test;

final boolean isLiveServer = os:getEnv("IS_LIVE_SERVER") == "true";
final string region = isLiveServer && os:getEnv("SAP_SIGNAVIO_REGION") != "" ? os:getEnv("SAP_SIGNAVIO_REGION") : "eu";
final string gatewayUrl = isLiveServer ? string `https://api.${region}.signavio.cloud.sap` : "http://localhost:9090";
final string workspaceUrl = isLiveServer ? string `https://app-${region}.signavio.com` : "http://localhost:9090";
final string username = isLiveServer ? os:getEnv("SAP_SIGNAVIO_USERNAME") : "user@example.com";
final string password = isLiveServer ? os:getEnv("SAP_SIGNAVIO_PASSWORD") : "test_password";
final string odataAccessToken = isLiveServer ? os:getEnv("SAP_SIGNAVIO_ODATA_TOKEN") : "mock-odata-token";

// `Client.init()` now performs live logins (gateway JWT + Process Manager session), so it
// can't run as part of a module-level variable initializer here - that phase completes
// before the mock listener in mock_service.bal starts accepting connections. Constructing
// the client in `@test:BeforeSuite` instead guarantees the mock listener is already up.
isolated Client? signavioHolder = ();

@test:BeforeSuite
function setUpSignavioClient() returns error? {
    Client newClient = check new ({auth: {username, password, odataAccessToken}}, gatewayUrl, workspaceUrl);
    lock {
        signavioHolder = newClient;
    }
}

isolated function getSignavio() returns Client {
    lock {
        Client? c = signavioHolder;
        if c is Client {
            return c;
        }
        panic error("signavio client was not initialized - @test:BeforeSuite did not run");
    }
}

@test:Config {groups: ["live_tests", "mock_tests"]}
isolated function testAuthenticate() returns error? {
    Client signavio = getSignavio();
    string response = check signavio->authenticate({
        name: username,
        password,
        tokenonly: true
    });
    test:assertTrue(response.length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
isolated function testListCases() returns error? {
    Client signavio = getSignavio();
    CasesResourcesResponseSchema|CasesResourceReferencesResponseSchema response = check signavio->listCases();
    test:assertTrue(response is CasesResourcesResponseSchema);
    if response is CasesResourcesResponseSchema {
        test:assertTrue(response.data.length() > 0);
    }
}

@test:Config {groups: ["live_tests", "mock_tests"]}
isolated function testGetCase() returns error? {
    Client signavio = getSignavio();
    CasesResourceResponseSchema response = check signavio->getCase("case-1001");
    test:assertEquals(response.data.'type, "Cases");
}

@test:Config {groups: ["live_tests", "mock_tests"]}
isolated function testListTasks() returns error? {
    Client signavio = getSignavio();
    TasksResourcesResponseSchema|TasksResourceReferencesResponseSchema response = check signavio->listTasks();
    test:assertTrue(response is TasksResourcesResponseSchema);
    if response is TasksResourcesResponseSchema {
        test:assertTrue(response.data.length() > 0);
    }
}

@test:Config {groups: ["live_tests", "mock_tests"]}
isolated function testListUsers() returns error? {
    Client signavio = getSignavio();
    UsersResourcesResponseSchema|UsersResourceReferencesResponseSchema response = check signavio->listUsers();
    test:assertTrue(response is UsersResourcesResponseSchema);
    if response is UsersResourcesResponseSchema {
        test:assertTrue(response.data.length() > 0);
    }
}

@test:Config {groups: ["live_tests", "mock_tests"]}
isolated function testAddAutomaticMeasurementToMetric() returns error? {
    Client signavio = getSignavio();
    error? response = signavio->addAutomaticMeasurementToMetric("journey-1", "metric-1", {
        'type: "NPS",
        value: <NPSMeasurement>{
            score: 45,
            time: "2026-07-01T00:00:00Z",
            detractors: 10,
            promoters: 55,
            passives: 35
        }
    });
    test:assertTrue(response is ());
}

@test:Config {groups: ["live_tests", "mock_tests"]}
isolated function testListDictionaryEntries() returns error? {
    Client signavio = getSignavio();
    DictionaryResponse[] response = check signavio->listDictionaryEntries();
    test:assertTrue(response.length() > 0);
    test:assertEquals(response[0].rel, "gitem");
}

@test:Config {groups: ["live_tests", "mock_tests"]}
isolated function testCreateDictionaryEntry() returns error? {
    Client signavio = getSignavio();
    DictionaryResponse response = check signavio->createDictionaryEntry(
        {
            title: "Supplier (sap.signavio connector test)",
            category: "cat-org-units",
            description: "An external party providing goods or services."
        }
    );
    test:assertEquals(response.rel, "gitem");
}

@test:Config {groups: ["live_tests", "mock_tests"]}
isolated function testGetDictionaryEntry() returns error? {
    Client signavio = getSignavio();
    DictionaryResponse[] response = check signavio->getDictionaryEntry("ge-1001");
    test:assertTrue(response.length() > 0);
    test:assertEquals(response[0].rel, "info");
}

@test:Config {groups: ["live_tests", "mock_tests"]}
isolated function testDeleteDictionaryEntry() returns error? {
    Client signavio = getSignavio();
    SuccessResponse response = check signavio->deleteDictionaryEntry("ge-1001");
    test:assertEquals(response.success, true);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
isolated function testGetRootDirectories() returns error? {
    Client signavio = getSignavio();
    HyperMediaObject[] response = check signavio->getRootDirectories();
    test:assertTrue(response.length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
isolated function testCreateDirectory() returns error? {
    Client signavio = getSignavio();
    HyperMediaObject response = check signavio->createDirectory({
        name: "New Folder",
        parent: "/directory/8f2c1b3a9d4e5f60718293a4b5c6d7e8"
    });
    test:assertEquals(response.rel, "dir");
}

@test:Config {groups: ["live_tests", "mock_tests"]}
isolated function testGetDirectoryContent() returns error? {
    Client signavio = getSignavio();
    HyperMediaObject[] response = check signavio->getDirectoryContent("8f2c1b3a9d4e5f60718293a4b5c6d7e8");
    test:assertTrue(response.length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
isolated function testDeleteDirectory() returns error? {
    Client signavio = getSignavio();
    DeleteDirectoryResponse response = check signavio->deleteDirectory("8f2c1b3a9d4e5f60718293a4b5c6d7e8");
    test:assertEquals(response.success, true);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
isolated function testGetModelJson() returns error? {
    Client signavio = getSignavio();
    DiagramJson response = check signavio->getModelJson("1a2b3c4d");
    test:assertTrue(response.resourceId !is ());
}

@test:Config {groups: ["live_tests", "mock_tests"]}
isolated function testGetBpmnXml() returns error? {
    Client signavio = getSignavio();
    xml response = check signavio->getBpmnXml("1a2b3c4d");
    test:assertTrue(response.toString().length() > 0);
}

// A minimal but valid BPMN 2.0 document - the mock server accepts any bytes, but a live
// tenant validates the XML and requires a BPMNDI (diagram interchange) section; without one
// it returns 200 OK with the model uncreated and a "MissingBPMNDIPart" error in the body.
final string & readonly minimalBpmnXml = string `<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL"
             xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI"
             xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC"
             id="defs1" targetNamespace="http://www.signavio.com/bpmn20">
  <process id="test_process" name="Connector test process" isExecutable="false">
    <startEvent id="start"/>
  </process>
  <bpmndi:BPMNDiagram id="diagram1">
    <bpmndi:BPMNPlane id="plane1" bpmnElement="test_process">
      <bpmndi:BPMNShape id="start_di" bpmnElement="start">
        <omgdc:Bounds x="100" y="100" width="36" height="36"/>
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>`;

@test:Config {groups: ["live_tests", "mock_tests"]}
isolated function testImportBpmnXml() returns error? {
    Client signavio = getSignavio();
    BpmnImportResult response = check signavio->importBpmn20Xml({
        bpmn2File: {
            fileName: "process.bpmn",
            fileContent: minimalBpmnXml.toBytes()
        }
    });
    test:assertTrue(response.mainModelId !is ());
}

@test:Config {groups: ["live_tests", "mock_tests"]}
isolated function testUploadSchemaAndData() returns error? {
    Client signavio = getSignavio();
    UploadSchemaAndDataResponseDto response = check signavio->uploadSchemaAndData({
        schema: "{\"type\":\"record\",\"name\":\"orders\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"}]}",
        primaryKeys: ["id"],
        files: [{fileName: "data.csv", fileContent: "id,name\n1,Acme".toBytes()}]
    });
    test:assertTrue(response.executionId.length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
isolated function testGetIngestionStatus() returns error? {
    Client signavio = getSignavio();
    ExecutionStatusDto response = check signavio->getStatus("exec-7f3a9c1e");
    test:assertEquals(response.status, "COMPLETED");
}

@test:Config {groups: ["live_tests", "mock_tests"]}
isolated function testListInitiatives() returns error? {
    Client signavio = getSignavio();
    Initiative[] response = check signavio->listInitiatives();
    test:assertTrue(response.length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
isolated function testCreateInitiative() returns error? {
    Client signavio = getSignavio();
    Initiative response = check signavio->createInitiative({
        name: "Order to Cash Optimization",
        status: "IN_PROGRESS",
        valueDrivers: ["OPERATIONAL_EXCELLENCE"],
        authorizations: [
            {role: "OWNER", targetId: "9e107d9d-372b-4c81-9134-2f7f4a1c2b3d", targetType: "USER"}
        ]
    });
    test:assertTrue(response.id.length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
isolated function testGetInitiative() returns error? {
    Client signavio = getSignavio();
    Initiative response = check signavio->getInitiative("3fa85f64-5717-4562-b3fc-2c963f66afa6");
    test:assertEquals(response.id, "3fa85f64-5717-4562-b3fc-2c963f66afa6");
}

@test:Config {groups: ["live_tests", "mock_tests"]}
isolated function testUpdateInitiative() returns error? {
    Client signavio = getSignavio();
    Initiative response = check signavio->updateInitiative("3fa85f64-5717-4562-b3fc-2c963f66afa6", {
        name: "Order to Cash Optimization",
        status: "IN_PROGRESS",
        valueDrivers: ["OPERATIONAL_EXCELLENCE"],
        authorizations: [
            {role: "OWNER", targetId: "9e107d9d-372b-4c81-9134-2f7f4a1c2b3d", targetType: "USER"}
        ]
    });
    test:assertTrue(response.name.length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
isolated function testDeleteInitiative() returns error? {
    Client signavio = getSignavio();
    error? response = signavio->deleteInitiative("3fa85f64-5717-4562-b3fc-2c963f66afa6");
    test:assertTrue(response is ());
}

@test:Config {groups: ["live_tests", "mock_tests"]}
isolated function testListInsights() returns error? {
    Client signavio = getSignavio();
    Insight[] response = check signavio->listInsights();
    test:assertTrue(response.length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
isolated function testCreateInsight() returns error? {
    Client signavio = getSignavio();
    Insight response = check signavio->createInsight({
        name: "Long approval times for high-value invoices",
        status: "OPEN",
        valueDrivers: ["OPERATIONAL_EXCELLENCE"],
        authorizations: [
            {role: "OWNER", targetId: "9e107d9d-372b-4c81-9134-2f7f4a1c2b3d", targetType: "USER"}
        ],
        assignees: ["9e107d9d-372b-4c81-9134-2f7f4a1c2b3d"],
        priorityScore: 7.5,
        effortScore: 3.0,
        impactScore: 8.0
    });
    test:assertTrue(response.id.length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
isolated function testRetrieveModel() returns error? {
    Client signavio = getSignavio();
    ModelResourceResponse[] response = check signavio->retrieveModel("1a2b3c4d");
    test:assertTrue(response.length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
isolated function testListObjectives() returns error? {
    Client signavio = getSignavio();
    ObjectivesResponse response = check signavio->listObjectives();
    test:assertTrue(response?.value !is ());
}

@test:Config {groups: ["live_tests", "mock_tests"]}
isolated function testSearch() returns error? {
    Client signavio = getSignavio();
    http:Response response = check signavio->search(queries = {q: "invoice"});
    // The mock server always returns 304 (Not Modified) for this query; a live tenant with no
    // matching ETag/cache context legitimately returns 200 with fresh results instead.
    test:assertTrue(response.statusCode == 304 || response.statusCode == 200);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
isolated function testQueryEntitySet() returns error? {
    Client signavio = getSignavio();
    OdataOutput response = check signavio->queryEntitySet("defects", queries = {dollarSelect: ["caseId"]});
    test:assertTrue(response.value.length() > 0);
}

// Verifies the wrapper transparently re-authenticates and replays a request when the server
// responds 401 (an expired gateway JWT / workspace session). The mock rejects the sentinel
// execution id "reauth-probe" with 401 exactly once; a successful result proves the wrapper
// caught the 401, re-logged in, and retried. Mock-only (the live server can't be forced to 401).
@test:Config {groups: ["mock_tests"]}
isolated function testReauthenticatesOn401() returns error? {
    Client signavio = getSignavio();
    ExecutionStatusDto status = check signavio->getStatus("reauth-probe");
    test:assertEquals(status.status, "COMPLETED");
}
