// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;
import ballerina/mime;

# Merged OpenAPI specification for the SAP Signavio APIs: Authentication, Analytics (SPG), Metrics, Dictionary, Directory, Import and Export, Ingestion, Initiatives and Assets, Insights, Model, Objectives, Search, and SIGNAL Engine OData.
#
# SAP Signavio splits its REST surface across two backends that each need their own auth:
#   - The API gateway (`api.<region>.signavio.cloud.sap`), authenticated with a JWT obtained
#     from `POST /auth/v1/token`. Used by Ingestion, Transformation Manager, Analytics (SPG),
#     and Journey Modeler Metrics.
#   - The Process Manager workspace (`app-<region>.signavio.com`), authenticated with a
#     session (`JSESSIONID` cookie + `X-Signavio-ID` header) obtained from `POST /p/login`.
#     Used by Directory, Model, Dictionary, Search, and Import/Export.
# `Client.init()` performs both logins from the single set of credentials supplied in
# `ConnectionConfig`, so callers never need to handle either auth flow themselves.
isolated client class GeneratedClient {
    # A plain (no baked auth) client for the API gateway. The gateway JWT is injected per
    # request (via `gatewayHeaders`) from the refreshable `jwt` state rather than baked into
    # this client's config, so an expired token can be replaced without rebuilding the client.
    final http:Client gatewayClient;
    # A plain (no Bearer auth) client for `POST /auth/v1/token`. The gateway rejects that
    # specific route with a 404 whenever an `Authorization` header is present - even a
    # previously-issued valid JWT - so re-authentication cannot reuse `gatewayClient`.
    final http:Client authClient;
    # A plain client for the Process Manager workspace, also used for `POST /p/login`.
    final http:Client workspaceClient;
    # A client authenticated with `auth.odataAccessToken`, used only by the SIGNAL Engine OData
    # operations. `()` when no `odataAccessToken` was supplied.
    final http:Client? odataClient;

    // Credentials retained so the client can re-authenticate itself when a token/session expires.
    private final string username;
    private final string password;
    private final string? tenant;

    // Refreshable auth state, replaced by `reauthenticate()` and read per request under `lock`.
    private string jwt = "";
    private map<string> & readonly sessionHeaders = {};

    # Gets invoked to initialize the `connector`. Exchanges `config.auth` for a gateway JWT and
    # a Process Manager workspace session; both are refreshed automatically when they expire.
    #
    # + config - The configurations to be used when initializing the `connector`
    # + gatewayUrl - URL of the SAP Signavio API gateway. Defaults to the URL derived from `config.region`
    # + workspaceUrl - URL of the SAP Signavio Process Manager workspace. Defaults to the URL derived from `config.region`
    # + return - An error if connector initialization, or either login, failed
    public isolated function init(ConnectionConfig config, string? gatewayUrl = (), string? workspaceUrl = ()) returns error? {
        http:ClientConfiguration httpClientConfig = {httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        string resolvedGatewayUrl = gatewayUrl ?: string `https://api.${config.region}.signavio.cloud.sap`;
        string resolvedWorkspaceUrl = workspaceUrl ?: string `https://app-${config.region}.signavio.com`;

        self.username = config.auth.username;
        self.password = config.auth.password;
        self.tenant = config.auth.tenant;

        self.authClient = check new (resolvedGatewayUrl, httpClientConfig);
        self.gatewayClient = check new (resolvedGatewayUrl, httpClientConfig);
        self.workspaceClient = check new (resolvedWorkspaceUrl, httpClientConfig);

        string? odataAccessToken = config.auth.odataAccessToken;
        if odataAccessToken is string {
            http:ClientConfiguration odataClientConfig = {httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding, auth: {username: config.auth.username, password: odataAccessToken}};
            self.odataClient = check new (resolvedGatewayUrl, odataClientConfig);
        } else {
            self.odataClient = ();
        }

        // Perform the initial gateway login and workspace session establishment.
        check self.reauthenticate();
    }

    # Re-runs both SAP Signavio logins and replaces the cached gateway JWT and workspace session.
    # Called once during `init`, and again by the wrapper client whenever a request comes back
    # unauthenticated (the gateway JWT is valid ~24h and the workspace session has its own
    # server-side timeout, so a long-lived client must be able to refresh both).
    #
    # + return - An error if either login failed
    public isolated function reauthenticate() returns error? {
        TokenRequest credentials = {name: self.username, password: self.password, tokenonly: true};
        string? tenant = self.tenant;
        if tenant is string {
            credentials.tenant = tenant;
        }

        // Exchange the account credentials for an API gateway JWT (POST /auth/v1/token).
        http:Request tokenRequest = new;
        tokenRequest.setPayload(createFormURLEncodedRequestBody(check jsondata:toJson(credentials).ensureType()),
                "application/x-www-form-urlencoded");
        string newJwt = check self.authClient->post("/auth/v1/token", tokenRequest);
        lock {
            self.jwt = newJwt;
        }

        // Establish a Process Manager workspace session (POST /p/login).
        credentials.tokenonly = false;
        http:Request loginRequest = new;
        loginRequest.setPayload(createFormURLEncodedRequestBody(check jsondata:toJson(credentials).ensureType()),
                "application/x-www-form-urlencoded");
        http:Response loginResponse = check self.workspaceClient->post("/p/login", loginRequest);
        string signavioId = check loginResponse.getTextPayload();
        // Forward every cookie the login response set, not just JSESSIONID - the workspace host
        // is load-balanced and sets an affinity cookie (e.g. AWSELB/LBROUTEID) that must be echoed
        // back, or a follow-up request routed to a different node fails to find the session.
        boolean hasSession = false;
        string[] cookiePairs = [];
        foreach http:Cookie cookie in loginResponse.getCookies() {
            cookiePairs.push(string `${cookie.name}=${cookie.value}`);
            if cookie.name == "JSESSIONID" {
                hasSession = true;
            }
        }
        if !hasSession {
            return error("Failed to establish a SAP Signavio Process Manager workspace session: no JSESSIONID cookie was returned. Check the supplied username/password.");
        }
        // `Accept: application/json` is required - some Process Manager routes (e.g. the
        // dictionary/glossary GET endpoints) serve an HTML browser page by default and only
        // return their JSON representation when this is explicitly requested.
        map<string> & readonly newSessionHeaders = {
            "Cookie": string:'join("; ", ...cookiePairs),
            "X-Signavio-ID": signavioId,
            "Accept": "application/json"
        };
        lock {
            self.sessionHeaders = newSessionHeaders;
        }
    }

    # Merges the current gateway JWT (`Authorization: Bearer ...`) with the caller-supplied headers.
    #
    # + extra - The caller-supplied headers for this request
    # + return - The combined header map carrying the current gateway JWT
    private isolated function gatewayHeaders(map<string|string[]> extra) returns map<string|string[]> {
        string token;
        lock {
            token = self.jwt;
        }
        map<string|string[]> merged = {"Authorization": string `Bearer ${token}`};
        foreach [string, string|string[]] [name, value] in extra.entries() {
            merged[name] = value;
        }
        return merged;
    }

    # Returns the current Process Manager workspace session headers (`Cookie`, `X-Signavio-ID`,
    # `Accept`).
    #
    # + return - The current session header map
    private isolated function currentSessionHeaders() returns map<string> {
        lock {
            return self.sessionHeaders;
        }
    }

    # List of case-variables resources
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function listCaseVariables(ListCaseVariablesHeaders headers = {}, *ListCaseVariablesQueries queries) returns CaseVariablesResourcesResponseSchema|CaseVariablesResourceReferencesResponseSchema|error {
        string resourcePath = string `/spg/report/v1/case-variables`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(httpHeaders));
    }

    # Case-variables resource
    #
    # + id - case primary key to include
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function getCaseVariable(string id, GetCaseVariableHeaders headers = {}, *GetCaseVariableQueries queries) returns CaseVariablesResourceResponseSchema|CaseVariablesResourceReferencesResponseSchema|error {
        string resourcePath = string `/spg/report/v1/case-variables/${getEncodedUri(id)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(httpHeaders));
    }

    # Cases related to a case-variables resource
    #
    # + id - case primary key to include
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function listCaseVariableCases(string id, ListCaseVariableCasesHeaders headers = {}, *ListCaseVariableCasesQueries queries) returns CasesResourceResponseSchema|CasesResourceReferencesResponseSchema|error {
        string resourcePath = string `/spg/report/v1/case-variables/${getEncodedUri(id)}/cases`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(httpHeaders));
    }

    # Cases references related to a case-variables resource
    #
    # + id - case primary key to include
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function listCaseVariableCaseRefs(string id, ListCaseVariableCaseRefsHeaders headers = {}, *ListCaseVariableCaseRefsQueries queries) returns CasesResourceReferenceResponseSchema|CasesResourceReferencesResponseSchema|error {
        string resourcePath = string `/spg/report/v1/case-variables/${getEncodedUri(id)}/relationships/cases`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(httpHeaders));
    }

    # List of cases resources
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function listCases(ListCasesHeaders headers = {}, *ListCasesQueries queries) returns CasesResourcesResponseSchema|CasesResourceReferencesResponseSchema|error {
        string resourcePath = string `/spg/report/v1/cases`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(httpHeaders));
    }

    # Cases resource
    #
    # + id - case primary key to include
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function getCase(string id, GetCaseHeaders headers = {}, *GetCaseQueries queries) returns CasesResourceResponseSchema|error {
        string resourcePath = string `/spg/report/v1/cases/${getEncodedUri(id)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(httpHeaders));
    }

    # Tasks related to a cases resource
    #
    # + id - case primary key to include
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function listCaseTasks(string id, ListCaseTasksHeaders headers = {}, *ListCaseTasksQueries queries) returns TasksResourcesResponseSchema|TasksResourceReferencesResponseSchema|error {
        string resourcePath = string `/spg/report/v1/cases/${getEncodedUri(id)}/tasks`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(httpHeaders));
    }

    # Users related to a cases resource
    #
    # + id - case primary key to include
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function getCaseCreator(string id, GetCaseCreatorHeaders headers = {}, *GetCaseCreatorQueries queries) returns UsersResourceResponseSchema|UsersResourceReferencesResponseSchema|error {
        string resourcePath = string `/spg/report/v1/cases/${getEncodedUri(id)}/creator`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(httpHeaders));
    }

    # List of files resources
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function listFiles(ListFilesHeaders headers = {}, *ListFilesQueries queries) returns FilesResourcesResponseSchema|FilesResourceReferencesResponseSchema|error {
        string resourcePath = string `/spg/report/v1/files`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(httpHeaders));
    }

    # Files resource
    #
    # + id - case primary key to include
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function getFile(string id, GetFileHeaders headers = {}, *GetFileQueries queries) returns FilesResourceResponseSchema|FilesResourceReferencesResponseSchema|error {
        string resourcePath = string `/spg/report/v1/files/${getEncodedUri(id)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(httpHeaders));
    }

    # List of groups resources
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function listGroups(ListGroupsHeaders headers = {}, *ListGroupsQueries queries) returns GroupsResourcesResponseSchema|GroupsResourceReferencesResponseSchema|error {
        string resourcePath = string `/spg/report/v1/groups`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(httpHeaders));
    }

    # Groups resource
    #
    # + id - case primary key to include
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function getGroup(string id, GetGroupHeaders headers = {}, *GetGroupQueries queries) returns GroupsResourceResponseSchema|GroupsResourceReferencesResponseSchema|error {
        string resourcePath = string `/spg/report/v1/groups/${getEncodedUri(id)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(httpHeaders));
    }

    # Users references related to a groups resource
    #
    # + id - case primary key to include
    # + headers - Headers to be sent with the request 
    # + return - OK 
    remote isolated function listGroupUserRefs(string id, ListGroupUserRefsHeaders headers = {}) returns UsersResourceReferencesResponseSchema|error {
        string resourcePath = string `/spg/report/v1/groups/${getEncodedUri(id)}/relationships/users`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(httpHeaders));
    }

    # Users related to a groups resource
    #
    # + id - case primary key to include
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function listGroupUsers(string id, ListGroupUsersHeaders headers = {}, *ListGroupUsersQueries queries) returns UsersResourcesResponseSchema|UsersResourceReferencesResponseSchema|error {
        string resourcePath = string `/spg/report/v1/groups/${getEncodedUri(id)}/users`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(httpHeaders));
    }

    # List of tasks resources
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function listTasks(ListTasksHeaders headers = {}, *ListTasksQueries queries) returns TasksResourcesResponseSchema|TasksResourceReferencesResponseSchema|error {
        string resourcePath = string `/spg/report/v1/tasks`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(httpHeaders));
    }

    # Tasks resource
    #
    # + id - case primary key to include
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function getTask(string id, GetTaskHeaders headers = {}, *GetTaskQueries queries) returns TasksResourceResponseSchema|TasksResourceReferencesResponseSchema|error {
        string resourcePath = string `/spg/report/v1/tasks/${getEncodedUri(id)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(httpHeaders));
    }

    # Case related to a tasks resource
    #
    # + id - case primary key to include
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function getTaskCase(string id, GetTaskCaseHeaders headers = {}, *GetTaskCaseQueries queries) returns CasesResourceResponseSchema|CasesResourceReferencesResponseSchema|error {
        string resourcePath = string `/spg/report/v1/tasks/${getEncodedUri(id)}/case`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(httpHeaders));
    }

    # Case reference related to a tasks resource
    #
    # + id - case primary key to include
    # + headers - Headers to be sent with the request 
    # + return - OK 
    remote isolated function getTaskCaseRef(string id, GetTaskCaseRefHeaders headers = {}) returns CasesResourceReferenceResponseSchema|CasesResourceReferencesResponseSchema|error {
        string resourcePath = string `/spg/report/v1/tasks/${getEncodedUri(id)}/relationships/case`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(httpHeaders));
    }

    # List of users resources
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function listUsers(ListUsersHeaders headers = {}, *ListUsersQueries queries) returns UsersResourcesResponseSchema|UsersResourceReferencesResponseSchema|error {
        string resourcePath = string `/spg/report/v1/users`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(httpHeaders));
    }

    # Users resource
    #
    # + id - case primary key to include
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function getUser(string id, GetUserHeaders headers = {}, *GetUserQueries queries) returns UsersResourceResponseSchema|UsersResourceReferencesResponseSchema|error {
        string resourcePath = string `/spg/report/v1/users/${getEncodedUri(id)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(httpHeaders));
    }

    # Add automatic measurement to existing metrics.
    #
    # + journeyId - The ID of the journey to be updated
    # + metricId - The ID of the metric to be updated
    # + payload - The request payload
    # + headers - Headers to be sent with the request 
    # + return - Updated successfully 
    remote isolated function addAutomaticMeasurementToMetric(string journeyId, string metricId, AutomaticMeasurement payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/jm/v1/journeys/${getEncodedUri(journeyId)}/metrics/${getEncodedUri(metricId)}/value`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.gatewayClient->post(resourcePath, request, self.gatewayHeaders(headers));
    }

    # Create an API access token (login)
    #
    # + payload - The request payload
    # + headers - Headers to be sent with the request 
    # + return - Authentication successful. Following successful authentication, subsequent authenticated API requests must include the 'JSESSIONID' cookie 
    remote isolated function authenticate(TokenRequest payload, AuthenticateHeaders headers = {}) returns string|error {
        string resourcePath = string `/auth/v1/token`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        string encodedRequestBody = createFormURLEncodedRequestBody(check jsondata:toJson(payload).ensureType());
        request.setPayload(encodedRequestBody, "application/x-www-form-urlencoded");
        return self.authClient->post(resourcePath, request, httpHeaders);
    }

    # Lists dictionary entries, optionally filtered by category, and with full-text search or title initial letter filter.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A JSON representation of the search results. All dictionary entries are contained in a top-level array (bounded by `[` and `]`),  and contain the key-value pair `"rel": "gitem"` (for 'glossary  item'). The important fields inside the content of their `rep`  object have the same semantics as is defined for dictionary entry  creation. They are:   * `id`   * `title`   * `category`   * `description`   * `attachments` Some fields provide additional information on the entry's category:   * `categoryName`   * `color` **Hint:** If the category ID in the `category` query string is not found, the response includes all categories instead of having a 404  Not Found status 
    remote isolated function listDictionaryEntries(ListDictionaryEntriesHeaders headers = {}, *ListDictionaryEntriesQueries queries) returns DictionaryResponse[]|error {
        string resourcePath = string `/p/glossary`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = withSessionHeaders(self.currentSessionHeaders(), http:getHeaderMap(headers));
        return self.workspaceClient->get(resourcePath, httpHeaders);
    }

    # Creates a dictionary entry.
    #
    # + payload - The request payload
    # + headers - Headers to be sent with the request 
    # + return - Returns a JSON object containing the created dictionary item 
    remote isolated function createDictionaryEntry(DictionaryEntryRequest payload, CreateDictionaryEntryHeaders headers = {}) returns DictionaryResponse|error {
        string resourcePath = string `/p/glossary`;
        map<string|string[]> httpHeaders = withSessionHeaders(self.currentSessionHeaders(), http:getHeaderMap(headers));
        http:Request request = new;
        string encodedRequestBody = createFormURLEncodedRequestBody(check jsondata:toJson(payload).ensureType());
        request.setPayload(encodedRequestBody, "application/x-www-form-urlencoded");
        return self.workspaceClient->post(resourcePath, request, httpHeaders);
    }

    # Retrieves the specified dictionary entry.
    #
    # + id - The ID of the dictionary entry to retrieve
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function getDictionaryEntry(string id, GetDictionaryEntryHeaders headers = {}) returns DictionaryResponse[]|error {
        string resourcePath = string `/p/glossary/${getEncodedUri(id)}`;
        map<string|string[]> httpHeaders = withSessionHeaders(self.currentSessionHeaders(), http:getHeaderMap(headers));
        return self.workspaceClient->get(resourcePath, httpHeaders);
    }

    # Deletes a dictionary entry.
    #
    # + id - The ID of the dictionary entry to delete
    # + headers - Headers to be sent with the request 
    # + return - OK 
    remote isolated function deleteDictionaryEntry(string id, DeleteDictionaryEntryHeaders headers = {}) returns SuccessResponse|error {
        string resourcePath = string `/p/glossary/${getEncodedUri(id)}`;
        map<string|string[]> httpHeaders = withSessionHeaders(self.currentSessionHeaders(), http:getHeaderMap(headers));
        return self.workspaceClient->delete(resourcePath, headers = httpHeaders);
    }

    # Retrieves the specified dictionary entry with additional meta  information: most importantly, the category containing the entry.
    #
    # + id - The ID of the dictionary entry to retrieve
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function getDictionaryEntryInfo(string id, GetDictionaryEntryInfoHeaders headers = {}) returns Representation|error {
        string resourcePath = string `/p/glossary/${getEncodedUri(id)}/info`;
        map<string|string[]> httpHeaders = withSessionHeaders(self.currentSessionHeaders(), http:getHeaderMap(headers));
        return self.workspaceClient->get(resourcePath, httpHeaders);
    }

    # Updates a dictionary entry.
    #
    # + id - The ID of the dictionary entry to update
    # + payload - The request payload
    # + headers - Headers to be sent with the request 
    # + return - OK 
    remote isolated function updateDictionaryEntry(string id, DictionaryEntryUpdateRequest payload, UpdateDictionaryEntryHeaders headers = {}) returns DictionaryResponse|error {
        string resourcePath = string `/p/glossary/${getEncodedUri(id)}/info`;
        map<string|string[]> httpHeaders = withSessionHeaders(self.currentSessionHeaders(), http:getHeaderMap(headers));
        http:Request request = new;
        string encodedRequestBody = createFormURLEncodedRequestBody(check jsondata:toJson(payload).ensureType());
        request.setPayload(encodedRequestBody, "application/x-www-form-urlencoded");
        return self.workspaceClient->put(resourcePath, request, httpHeaders);
    }

    # Retrieves a list of your workspace's dictionary categories.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returns a list of all dictionary categories. The content data is  partly made up of information as described in  `POST /glossarycategory`. Additionally, each category contains the following information:   * `childCategories`: Array of prefixed IDs of categories that have   this category as parent category.   * `childCategoryCount`: The number of child categories.   * `glossaryId`: ID of the workspaces’s Dictionary (not relevant for    API access).   * `itemCount`: The number of dictionary entries in this category    (excluding those in sub-categories).   * `items`: Array of IDs of the contained dictionary entries    (deprecated).   * If the category corresponds to one of the six standard     categories, this field is set. For example, some reports     consider the content of these categories. The following     `oldCategories` exist:     * `ORG_UNIT` - Organizational units     * `DOCUMENT` - Documents     * `ACTIVITY` - Activities     * `STATE` - Events     * `IT_SYSTEM` - IT systems     * `NONE` - Everything else 
    remote isolated function listDictionaryCategories(ListDictionaryCategoriesHeaders headers = {}, *ListDictionaryCategoriesQueries queries) returns DictionaryResponse[]|error {
        string resourcePath = string `/p/glossarycategory`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = withSessionHeaders(self.currentSessionHeaders(), http:getHeaderMap(headers));
        return self.workspaceClient->get(resourcePath, httpHeaders);
    }

    # Creates a dictionary category.
    #
    # + payload - The request payload
    # + headers - Headers to be sent with the request 
    # + return - The newly created category 
    remote isolated function createDictionaryCategory(DictionaryCategoryRequest payload, CreateDictionaryCategoryHeaders headers = {}) returns DictionaryResponse|error {
        string resourcePath = string `/p/glossarycategory`;
        map<string|string[]> httpHeaders = withSessionHeaders(self.currentSessionHeaders(), http:getHeaderMap(headers));
        http:Request request = new;
        string encodedRequestBody = createFormURLEncodedRequestBody(check jsondata:toJson(payload).ensureType());
        request.setPayload(encodedRequestBody, "application/x-www-form-urlencoded");
        return self.workspaceClient->post(resourcePath, request, httpHeaders);
    }

    # Retrieves the specified dictionary category.
    #
    # + id - The ID of the dictionary category to retrieve
    # + headers - Headers to be sent with the request 
    # + return - A list of this category's sub-categories (`rel` is `cat`), and an  object with information on the category itself (`rel` is `info`).  Sending a `GET` request to `/p/glossarycategory/(id)/info` request  will fetch the information object only 
    remote isolated function getDictionaryCategory(string id, GetDictionaryCategoryHeaders headers = {}) returns DictionaryResponse[]|error {
        string resourcePath = string `/p/glossarycategory/${getEncodedUri(id)}`;
        map<string|string[]> httpHeaders = withSessionHeaders(self.currentSessionHeaders(), http:getHeaderMap(headers));
        return self.workspaceClient->get(resourcePath, httpHeaders);
    }

    # Updates an existing dictionary category.
    #
    # + id - The ID of the dictionary category to update
    # + payload - The request payload
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function updateDictionaryCategory(string id, DictionaryCategoryRequest payload, UpdateDictionaryCategoryHeaders headers = {}) returns DictionaryResponse|error {
        string resourcePath = string `/p/glossarycategory/${getEncodedUri(id)}`;
        map<string|string[]> httpHeaders = withSessionHeaders(self.currentSessionHeaders(), http:getHeaderMap(headers));
        http:Request request = new;
        string encodedRequestBody = createFormURLEncodedRequestBody(check jsondata:toJson(payload).ensureType());
        request.setPayload(encodedRequestBody, "application/x-www-form-urlencoded");
        return self.workspaceClient->put(resourcePath, request, httpHeaders);
    }

    # Deletes a dictionary category.
    #
    # + id - The dictionary category to delete
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Success 
    remote isolated function deleteDictionaryCategory(string id, DeleteDictionaryCategoryHeaders headers = {}, *DeleteDictionaryCategoryQueries queries) returns SuccessResponse|error {
        string resourcePath = string `/p/glossarycategory/${getEncodedUri(id)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = withSessionHeaders(self.currentSessionHeaders(), http:getHeaderMap(headers));
        return self.workspaceClient->delete(resourcePath, headers = httpHeaders);
    }

    # Retrieves your workspace's root folders' metadata.
    #
    # + headers - Headers to be sent with the request 
    # + return - Returns four resources, which represent a workspace's root folders:   * `Shared Documents` folder   * `My Documents` folder   * `Trash`   * `Dictionary` **Note:** The actual folder names may differ depending on the workspace language. Each resource's `rel` and `type` properties differ, depending on the resource type. The folders  `Shared Documents`, `My Documents` and `Trash` have the `rel` field set to `dir` and are tagged with a  `type` field, which can be either `public`, `private` or `trash`. Such type fields are only defined for  root folder structures. For the Dictionary, the `rel` field is set to `glos` (from 'glossary'). **Hint:** Although the `href` property values start with a `/` they are relative to the base URL path  rather than being absolute URL paths 
    remote isolated function getRootDirectories(map<string|string[]> headers = {}) returns HyperMediaObject[]|error {
        string resourcePath = string `/p/directory`;
        return self.workspaceClient->get(resourcePath, withSessionHeaders(self.currentSessionHeaders(), headers));
    }

    # Create a new directory
    #
    # + payload - The request payload
    # + headers - Headers to be sent with the request 
    # + return - Successfully created folder and returns its meta-data. **Hint:** The expected HTTP response status is `200 OK` rather than `201 Created` 
    remote isolated function createDirectory(CreateDirectoryRequest payload, map<string|string[]> headers = {}) returns HyperMediaObject|error {
        string resourcePath = string `/p/directory`;
        http:Request request = new;
        string encodedRequestBody = createFormURLEncodedRequestBody(check jsondata:toJson(payload).ensureType());
        request.setPayload(encodedRequestBody, "application/x-www-form-urlencoded");
        return self.workspaceClient->post(resourcePath, request, withSessionHeaders(self.currentSessionHeaders(), headers));
    }

    # Get meta-data of items in a given directory.
    #
    # + id - The ID of the directory to get the content of
    # + headers - Headers to be sent with the request 
    # + return - Successfully provided meta-data of all items in the directory 
    remote isolated function getDirectoryContent(DirectoryId id, map<string|string[]> headers = {}) returns HyperMediaObject[]|error {
        string resourcePath = string `/p/directory/${getEncodedUri(id)}`;
        return self.workspaceClient->get(resourcePath, withSessionHeaders(self.currentSessionHeaders(), headers));
    }

    # Move a given directory.
    #
    # + id - The ID of the directory to move
    # + payload - The request payload
    # + headers - Headers to be sent with the request 
    # + return - Successfully moved the directory and returned its updated meta-data 
    remote isolated function moveDirectory(DirectoryId id, MoveDirectoryRequest payload, map<string|string[]> headers = {}) returns HyperMediaObject|error {
        string resourcePath = string `/p/directory/${getEncodedUri(id)}`;
        http:Request request = new;
        string encodedRequestBody = createFormURLEncodedRequestBody(check jsondata:toJson(payload).ensureType());
        request.setPayload(encodedRequestBody, "application/x-www-form-urlencoded");
        return self.workspaceClient->put(resourcePath, request, withSessionHeaders(self.currentSessionHeaders(), headers));
    }

    # Delete a directory.
    #
    # + id - The ID of the directory to delete
    # + headers - Headers to be sent with the request 
    # + return - successfully deleted the directory 
    remote isolated function deleteDirectory(DirectoryId id, map<string|string[]> headers = {}) returns DeleteDirectoryResponse|error {
        string resourcePath = string `/p/directory/${getEncodedUri(id)}`;
        return self.workspaceClient->delete(resourcePath, headers = withSessionHeaders(self.currentSessionHeaders(), headers));
    }

    # Meta-data of a given directory.
    #
    # + id - The ID of the directory to get the meta-data of
    # + headers - Headers to be sent with the request 
    # + return - Successfully provided meta-data of the directory 
    remote isolated function getDirectoryInfo(DirectoryId id, map<string|string[]> headers = {}) returns DirectoryInfo|error {
        string resourcePath = string `/p/directory/${getEncodedUri(id)}/info`;
        return self.workspaceClient->get(resourcePath, withSessionHeaders(self.currentSessionHeaders(), headers));
    }

    # Rename a given directory.
    #
    # + id - The ID of the directory to rename
    # + payload - The request payload
    # + headers - Headers to be sent with the request 
    # + return - Successfully renamed the directory and returned its updated meta-data 
    remote isolated function renameDirectory(DirectoryId id, RenameDirectoryData payload, map<string|string[]> headers = {}) returns DirectoryInfo|error {
        string resourcePath = string `/p/directory/${getEncodedUri(id)}/info`;
        http:Request request = new;
        string encodedRequestBody = createFormURLEncodedRequestBody(check jsondata:toJson(payload).ensureType());
        request.setPayload(encodedRequestBody, "application/x-www-form-urlencoded");
        return self.workspaceClient->put(resourcePath, request, withSessionHeaders(self.currentSessionHeaders(), headers));
    }

    # publish/unpublish an item
    #
    # + payload - The request payload
    # + headers - Headers to be sent with the request 
    # + return - successfully published or unpublished the item 
    remote isolated function publishItem(PublishData payload, map<string|string[]> headers = {}) returns HyperMediaObject[]|error {
        string resourcePath = string `/p/publish`;
        http:Request request = new;
        string encodedRequestBody = createFormURLEncodedRequestBody(check jsondata:toJson(payload).ensureType());
        request.setPayload(encodedRequestBody, "application/x-www-form-urlencoded");
        return self.workspaceClient->post(resourcePath, request, withSessionHeaders(self.currentSessionHeaders(), headers));
    }

    # Get the model diagram as JSON
    #
    # + modelId - The ID of the model to be retrieved
    # + headers - Headers to be sent with the request 
    # + return - Workflow model data successfully retrieved 
    remote isolated function getModelJson(string modelId, map<string|string[]> headers = {}) returns DiagramJson|error {
        string resourcePath = string `/p/model/${getEncodedUri(modelId)}/json`;
        return self.workspaceClient->get(resourcePath, withSessionHeaders(self.currentSessionHeaders(), headers));
    }

    # Get revision JSON.
    #
    # + revisionId - The ID of the revision to be retrieved
    # + headers - Headers to be sent with the request 
    # + return - JSON representation of a model successfully retrieved 
    remote isolated function getRevisionJson(string revisionId, map<string|string[]> headers = {}) returns DiagramJson|error {
        string resourcePath = string `/p/revision/${getEncodedUri(revisionId)}/json`;
        return self.workspaceClient->get(resourcePath, withSessionHeaders(self.currentSessionHeaders(), headers));
    }

    # Get the model diagram as a PNG image
    #
    # + modelId - The ID of the model
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function getPng(string modelId, map<string|string[]> headers = {}) returns byte[]|error {
        string resourcePath = string `/p/model/${getEncodedUri(modelId)}/png`;
        return self.workspaceClient->get(resourcePath, withSessionHeaders(self.currentSessionHeaders(), headers));
    }

    # Get revision PNG.
    #
    # + revisionId - Revision ID
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function getRevisionPng(string revisionId, map<string|string[]> headers = {}) returns byte[]|error {
        string resourcePath = string `/p/revision/${getEncodedUri(revisionId)}/png`;
        return self.workspaceClient->get(resourcePath, withSessionHeaders(self.currentSessionHeaders(), headers));
    }

    # Get BPMN 2.0 XML
    #
    # + modelId - The ID of the model
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Success 
    remote isolated function getBpmnXml(string modelId, map<string|string[]> headers = {}, *GetBpmnXmlQueries queries) returns xml|error {
        string resourcePath = string `/p/model/${getEncodedUri(modelId)}/bpmn2_0_xml`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.workspaceClient->get(resourcePath, withSessionHeaders(self.currentSessionHeaders(), headers));
    }

    # Get revision BPMN 2.0 XML
    #
    # + revisionId - The ID of the model revision
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Success 
    remote isolated function getRevisionBpmnXml(string revisionId, map<string|string[]> headers = {}, *GetRevisionBpmnXmlQueries queries) returns xml|error {
        string resourcePath = string `/p/revision/${getEncodedUri(revisionId)}/bpmn2_0_xml`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.workspaceClient->get(resourcePath, withSessionHeaders(self.currentSessionHeaders(), headers));
    }

    # Get the model diagram as an SVG image
    #
    # + modelId - The ID of the model
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function getSvg(string modelId, map<string|string[]> headers = {}) returns http:Response|error {
        string resourcePath = string `/p/model/${getEncodedUri(modelId)}/svg`;
        return self.workspaceClient->get(resourcePath, withSessionHeaders(self.currentSessionHeaders(), headers));
    }

    # Get revision SVG.
    #
    # + revisionId - Revision ID
    # + headers - Headers to be sent with the request 
    # + return - SVG representation 
    remote isolated function getRevisionSvg(string revisionId, map<string|string[]> headers = {}) returns http:Response|error {
        string resourcePath = string `/p/revision/${getEncodedUri(revisionId)}/svg`;
        return self.workspaceClient->get(resourcePath, withSessionHeaders(self.currentSessionHeaders(), headers));
    }

    # Import BPMN 2.0 XML
    #
    # + payload - The request payload
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function importBpmn20Xml(BpmnImportRequest payload, map<string|string[]> headers = {}) returns BpmnImportResult|error {
        string resourcePath = string `/p/bpmn2_0-import`;
        http:Request request = new;
        mime:Entity[] bodyParts = check createBodyParts(check jsondata:toJson(payload).ensureType());
        // This endpoint additionally requires the session's X-Signavio-ID value repeated as a
        // "signavio-id" multipart field - sending it only as a header (as every other workspace
        // operation expects) is silently rejected with a "BPMN2_0Import.NoFile" error.
        mime:Entity signavioIdPart = new;
        signavioIdPart.setContentDisposition(mime:getContentDispositionObject("form-data; name=signavio-id;"));
        signavioIdPart.setText(self.currentSessionHeaders().get("X-Signavio-ID"));
        bodyParts.push(signavioIdPart);
        request.setBodyParts(bodyParts);
        return self.workspaceClient->post(resourcePath, request, withSessionHeaders(self.currentSessionHeaders(), headers));
    }

    # Retrieve download link to xml
    #
    # + id - The ID of the model
    # + headers - Headers to be sent with the request 
    # + return - Successful response 
    remote isolated function getDmnDownloadLink(string id, map<string|string[]> headers = {}) returns DmnDownloadLinkResponse|error {
        string resourcePath = string `/p/model/${getEncodedUri(id)}/dmn`;
        return self.workspaceClient->get(resourcePath, withSessionHeaders(self.currentSessionHeaders(), headers));
    }

    # Download DMN XML
    #
    # + id - The download id provided from /dmn-xml-download/{id}
    # + headers - Headers to be sent with the request 
    # + return - File downloaded successfully 
    remote isolated function downloadDmnXml(string id, map<string|string[]> headers = {}) returns byte[]|error {
        string resourcePath = string `/p/dmn-xml-download/${getEncodedUri(id)}`;
        return self.workspaceClient->get(resourcePath, withSessionHeaders(self.currentSessionHeaders(), headers));
    }

    # Upload schema and data
    #
    # + payload - The request payload
    # + headers - Headers to be sent with the request 
    # + return - OK 
    remote isolated function uploadSchemaAndData(IngestionDataRequest payload, map<string|string[]> headers = {}) returns UploadSchemaAndDataResponseDto|error {
        string resourcePath = string `/spi/ingestions/v1/data`;
        http:Request request = new;
        mime:Entity[] bodyParts = check createBodyParts(check jsondata:toJson(payload).ensureType());
        request.setBodyParts(bodyParts);
        return self.gatewayClient->post(resourcePath, request, self.gatewayHeaders(headers));
    }

    # Get status of ingestion request
    #
    # + executionId - Ingestion request execution Id
    # + headers - Headers to be sent with the request 
    # + return - OK 
    remote isolated function getStatus(string executionId, map<string|string[]> headers = {}) returns ExecutionStatusDto|error {
        string resourcePath = string `/spi/ingestions/v1/${getEncodedUri(executionId)}/status`;
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(headers));
    }

    # List initiatives
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Success 
    remote isolated function listInitiatives(map<string|string[]> headers = {}, *ListInitiativesQueries queries) returns Initiative[]|error {
        string resourcePath = string `/transformationmanager/v1/initiatives`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(headers));
    }

    # Create initiative
    #
    # + payload - The request payload
    # + headers - Headers to be sent with the request 
    # + return - Successfully created initiative 
    remote isolated function createInitiative(IncomingInitiative payload, map<string|string[]> headers = {}) returns Initiative|error {
        string resourcePath = string `/transformationmanager/v1/initiatives`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.gatewayClient->post(resourcePath, request, self.gatewayHeaders(headers));
    }

    # Get initiative
    #
    # + initiativeId - The id of the initiative to retrieve
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function getInitiative(UUID initiativeId, map<string|string[]> headers = {}) returns Initiative|error {
        string resourcePath = string `/transformationmanager/v1/initiatives/${getEncodedUri(initiativeId)}`;
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(headers));
    }

    # Update initiative
    #
    # + initiativeId - The id of the initiative to update
    # + payload - The request payload
    # + headers - Headers to be sent with the request 
    # + return - Successfully updated initiative 
    remote isolated function updateInitiative(UUID initiativeId, IncomingInitiative payload, map<string|string[]> headers = {}) returns Initiative|error {
        string resourcePath = string `/transformationmanager/v1/initiatives/${getEncodedUri(initiativeId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.gatewayClient->put(resourcePath, request, self.gatewayHeaders(headers));
    }

    # Delete initiative
    #
    # + initiativeId - The id of the initiative to delete
    # + headers - Headers to be sent with the request 
    # + return - Successfully deleted initiative 
    remote isolated function deleteInitiative(UUID initiativeId, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/transformationmanager/v1/initiatives/${getEncodedUri(initiativeId)}`;
        return self.gatewayClient->delete(resourcePath, headers = self.gatewayHeaders(headers));
    }

    # List assets from initiative
    #
    # + initiativeId - The id of the initiative containing the assets
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function listAssetsInitiative(UUID initiativeId, map<string|string[]> headers = {}) returns Asset[]|error {
        string resourcePath = string `/transformationmanager/v1/initiatives/${getEncodedUri(initiativeId)}/assets`;
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(headers));
    }

    # Create asset in initiative
    #
    # + initiativeId - The id of the initiative to add the asset to
    # + payload - The request payload
    # + headers - Headers to be sent with the request 
    # + return - Successfully created asset 
    remote isolated function createAssetInitiative(UUID initiativeId, IncomingAsset payload, map<string|string[]> headers = {}) returns Asset|error {
        string resourcePath = string `/transformationmanager/v1/initiatives/${getEncodedUri(initiativeId)}/assets`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.gatewayClient->post(resourcePath, request, self.gatewayHeaders(headers));
    }

    # Get asset from initiative
    #
    # + assetId - The id of the asset to retrieve
    # + initiativeId - The id of the initiative containing the asset
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function getAssetInitiative(UUID assetId, UUID initiativeId, map<string|string[]> headers = {}) returns Asset|error {
        string resourcePath = string `/transformationmanager/v1/initiatives/${getEncodedUri(initiativeId)}/assets/${getEncodedUri(assetId)}`;
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(headers));
    }

    # Update asset in initiative
    #
    # + assetId - The id of the asset to update
    # + initiativeId - The id of the initiative containing the asset
    # + payload - The request payload
    # + headers - Headers to be sent with the request 
    # + return - Successfully updated asset 
    remote isolated function updateAssetInitiative(UUID assetId, UUID initiativeId, IncomingAsset payload, map<string|string[]> headers = {}) returns Asset|error {
        string resourcePath = string `/transformationmanager/v1/initiatives/${getEncodedUri(initiativeId)}/assets/${getEncodedUri(assetId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.gatewayClient->put(resourcePath, request, self.gatewayHeaders(headers));
    }

    # Delete asset from initiative
    #
    # + assetId - The id of the asset to delete
    # + initiativeId - The id of the initiative containing the asset
    # + headers - Headers to be sent with the request 
    # + return - Successfully deleted asset 
    remote isolated function deleteAssetInitiative(UUID assetId, UUID initiativeId, map<string|string[]> headers = {}) returns Asset|error {
        string resourcePath = string `/transformationmanager/v1/initiatives/${getEncodedUri(initiativeId)}/assets/${getEncodedUri(assetId)}`;
        return self.gatewayClient->delete(resourcePath, headers = self.gatewayHeaders(headers));
    }

    # Get all insights in an initiative
    #
    # + initiativeId - ID of the initiative whose insights should be listed
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Success 
    remote isolated function listInsightsInInitiative(string initiativeId, map<string|string[]> headers = {}, *ListInsightsInInitiativeQueries queries) returns Insight[]|error {
        string resourcePath = string `/transformationmanager/v1/initiatives/${getEncodedUri(initiativeId)}/insights`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(headers));
    }

    # Get insight in initiative
    #
    # + initiativeId - ID of the initiative to which the insight belongs
    # + insightId - ID of the insight to be retrieved
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function getInsightInInitiative(UUID initiativeId, UUID insightId, map<string|string[]> headers = {}) returns Insight|error {
        string resourcePath = string `/transformationmanager/v1/initiatives/${getEncodedUri(initiativeId)}/insights/${getEncodedUri(insightId)}`;
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(headers));
    }

    # Get all insights
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Success 
    remote isolated function listInsights(map<string|string[]> headers = {}, *ListInsightsQueries queries) returns Insight[]|error {
        string resourcePath = string `/transformationmanager/v1/insights`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(headers));
    }

    # Create an insight
    #
    # + payload - The request payload
    # + headers - Headers to be sent with the request 
    # + return - Successfully created insight 
    remote isolated function createInsight(IncomingInsight payload, map<string|string[]> headers = {}) returns Insight|error {
        string resourcePath = string `/transformationmanager/v1/insights`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.gatewayClient->post(resourcePath, request, self.gatewayHeaders(headers));
    }

    # Get insight
    #
    # + insightId - The id of the insight to retrieve
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function getInsight(UUID insightId, map<string|string[]> headers = {}) returns Insight|error {
        string resourcePath = string `/transformationmanager/v1/insights/${getEncodedUri(insightId)}`;
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(headers));
    }

    # Update insight
    #
    # + insightId - The id of the insight to update
    # + payload - The request payload
    # + headers - Headers to be sent with the request 
    # + return - Successfully updated insight 
    remote isolated function updateInsight(UUID insightId, IncomingInsight payload, map<string|string[]> headers = {}) returns Insight|error {
        string resourcePath = string `/transformationmanager/v1/insights/${getEncodedUri(insightId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.gatewayClient->put(resourcePath, request, self.gatewayHeaders(headers));
    }

    # Delete insight
    #
    # + insightId - The id of the insight to delete
    # + headers - Headers to be sent with the request 
    # + return - Successfully deleted insight 
    remote isolated function deleteInsight(UUID insightId, map<string|string[]> headers = {}) returns json|error {
        string resourcePath = string `/transformationmanager/v1/insights/${getEncodedUri(insightId)}`;
        return self.gatewayClient->delete(resourcePath, headers = self.gatewayHeaders(headers));
    }

    # Retrieve Model
    #
    # + id - The ID of the model to be retrieved
    # + headers - Headers to be sent with the request 
    # + return - Successful Operation 
    remote isolated function retrieveModel(string id, map<string|string[]> headers = {}) returns ModelResourceResponse[]|error {
        string resourcePath = string `/v1/model/${getEncodedUri(id)}`;
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(headers));
    }

    # Update Model
    #
    # + id - The ID of the model to be updated
    # + payload - The request payload
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Successful Operation 
    remote isolated function updateModel(string id, ModelRequest payload, map<string|string[]> headers = {}, *UpdateModelQueries queries) returns ModelResourceResponse[]|error {
        string resourcePath = string `/v1/model/${getEncodedUri(id)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        string encodedRequestBody = createFormURLEncodedRequestBody(check jsondata:toJson(payload).ensureType());
        request.setPayload(encodedRequestBody, "application/x-www-form-urlencoded");
        return self.gatewayClient->put(resourcePath, request, self.gatewayHeaders(headers));
    }

    # Delete Model
    #
    # + id - The ID of the model to be deleted
    # + headers - Headers to be sent with the request 
    # + return - Successful Operation 
    remote isolated function deleteModel(string id, map<string|string[]> headers = {}) returns SuccessResponse|error {
        string resourcePath = string `/v1/model/${getEncodedUri(id)}`;
        return self.gatewayClient->delete(resourcePath, headers = self.gatewayHeaders(headers));
    }

    # Create a new Model
    #
    # + payload - The request payload
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Successful Operation 
    remote isolated function createModel(ModelRequest payload, map<string|string[]> headers = {}, *CreateModelQueries queries) returns ModelResponse|error {
        string resourcePath = string `/v1/model`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        string encodedRequestBody = createFormURLEncodedRequestBody(check jsondata:toJson(payload).ensureType());
        request.setPayload(encodedRequestBody, "application/x-www-form-urlencoded");
        return self.gatewayClient->post(resourcePath, request, self.gatewayHeaders(headers));
    }

    # Retrieving all revision IDs of a model.
    #
    # + modelId - The model's ID
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Successful Operation 
    remote isolated function listModelRevisions(string modelId, map<string|string[]> headers = {}, *ListModelRevisionsQueries queries) returns ModelRevisionsResponse[]|error {
        string resourcePath = string `/v1/model/${getEncodedUri(modelId)}/revisions`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(headers));
    }

    # Update model info
    #
    # + modelId - The ID of the model
    # + payload - The request payload
    # + headers - Headers to be sent with the request 
    # + return - Successful operation 
    remote isolated function updateModelInfo(string modelId, ModelInfoRequest payload, map<string|string[]> headers = {}) returns ModelInfoResponse|error {
        string resourcePath = string `/v1/model/${getEncodedUri(modelId)}/info`;
        http:Request request = new;
        string encodedRequestBody = createFormURLEncodedRequestBody(check jsondata:toJson(payload).ensureType());
        request.setPayload(encodedRequestBody, "application/x-www-form-urlencoded");
        return self.gatewayClient->put(resourcePath, request, self.gatewayHeaders(headers));
    }

    # Performs a syntax check on a BPMN 2.0 process model.
    #
    # + payload - The request payload
    # + headers - Headers to be sent with the request 
    # + return - Syntax check successful 
    remote isolated function checkSyntax(SyntaxCheckRequest payload, map<string|string[]> headers = {}) returns SyntaxCheckResponse|error {
        string resourcePath = string `/v1/syntaxchecker`;
        http:Request request = new;
        string encodedRequestBody = createFormURLEncodedRequestBody(check jsondata:toJson(payload).ensureType());
        request.setPayload(encodedRequestBody, "application/x-www-form-urlencoded");
        return self.gatewayClient->post(resourcePath, request, self.gatewayHeaders(headers));
    }

    # Create a new model draft.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Model created successfully 
    remote isolated function createDiagramDraft(map<string|string[]> headers = {}, *CreateDiagramDraftQueries queries) returns DiagramDraftResponse|error {
        string resourcePath = string `/p/editorcreate`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.workspaceClient->get(resourcePath, withSessionHeaders(self.currentSessionHeaders(), headers));
    }

    # Get meta information
    #
    # + headers - Headers to be sent with the request
    # + return - Successfully retrieved meta information
    remote isolated function getMetaInfo(map<string|string[]> headers = {}) returns MetaResponseItem[]|error? {
        string resourcePath = string `/p/meta`;
        return self.workspaceClient->get(resourcePath, withSessionHeaders(self.currentSessionHeaders(), headers));
    }

    # Create meta information
    #
    # + payload - The request payload
    # + headers - Headers to be sent with the request
    # + return - Successfully created meta information
    remote isolated function createMetaInfo(MetaInfoRequest payload, map<string|string[]> headers = {}) returns MetaResponseItem|error {
        string resourcePath = string `/p/meta`;
        http:Request request = new;
        string encodedRequestBody = createFormURLEncodedRequestBody(check jsondata:toJson(payload).ensureType());
        request.setPayload(encodedRequestBody, "application/x-www-form-urlencoded");
        return self.workspaceClient->post(resourcePath, request, withSessionHeaders(self.currentSessionHeaders(), headers));
    }

    # Retrieve the current approval expiration date.
    #
    # + modelID - The ID of the model
    # + headers - Headers to be sent with the request 
    # + return - Successfully retrieved the approval expiration date 
    remote isolated function getExpirationDate(string modelID, map<string|string[]> headers = {}) returns ExpirationDate|error {
        string resourcePath = string `/v1/model/${getEncodedUri(modelID)}/approvalExpiration`;
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(headers));
    }

    # Update the approval expiration date.
    #
    # + modelID - The ID of the model
    # + payload - The request payload
    # + headers - Headers to be sent with the request 
    # + return - Successfully updated the approval expiration date 
    remote isolated function updateExpirationDate(string modelID, ExpirationDate payload, map<string|string[]> headers = {}) returns ExpirationDate|error {
        string resourcePath = string `/v1/model/${getEncodedUri(modelID)}/approvalExpiration`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.gatewayClient->put(resourcePath, request, self.gatewayHeaders(headers));
    }

    # Create a new approval expiration date.
    #
    # + modelID - The ID of the model
    # + payload - The request payload
    # + headers - Headers to be sent with the request 
    # + return - Successfully created the approval expiration date 
    remote isolated function createExpirationDate(string modelID, ExpirationDate payload, map<string|string[]> headers = {}) returns ExpirationDate|error {
        string resourcePath = string `/v1/model/${getEncodedUri(modelID)}/approvalExpiration`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.gatewayClient->post(resourcePath, request, self.gatewayHeaders(headers));
    }

    # Delete the current approval expiration date.
    #
    # + modelID - The ID of the model
    # + headers - Headers to be sent with the request 
    # + return - Successfully deleted the approval expiration date 
    remote isolated function deleteExpirationDate(string modelID, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/v1/model/${getEncodedUri(modelID)}/approvalExpiration`;
        return self.gatewayClient->delete(resourcePath, headers = self.gatewayHeaders(headers));
    }

    # Get all objectives
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Success returns objectives wrapped in value array 
    remote isolated function listObjectives(map<string|string[]> headers = {}, *ListObjectivesQueries queries) returns ObjectivesResponse|error {
        string resourcePath = string `/transformationmanager/v1/objectives`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(headers));
    }

    # Get objective by SID
    #
    # + objectiveSid - The Suite Objective ID (SID) (e.g. SuiteObjective_<32 hex chars>)
    # + headers - Headers to be sent with the request
    # + return - Success
    remote isolated function getObjective(string objectiveSid, map<string|string[]> headers = {}) returns Objective|error {
        string resourcePath = string `/transformationmanager/v1/objectives/by-sid/${getEncodedUri(objectiveSid)}`;
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(headers));
    }

    # Get linked initiatives
    #
    # + objectiveSid - The Suite Objective ID (SID) (e.g. SuiteObjective_<32 hex chars>)
    # + headers - Headers to be sent with the request
    # + return - Success
    remote isolated function getInitiativesByObjective(string objectiveSid, map<string|string[]> headers = {}) returns InitiativeSummaryForObjective[]|error {
        string resourcePath = string `/transformationmanager/v1/objectives/by-sid/${getEncodedUri(objectiveSid)}/initiatives`;
        return self.gatewayClient->get(resourcePath, self.gatewayHeaders(headers));
    }

    # Search the workspace
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - JSON array containing folder and model object representations. In the response object with `rel="search"`, the `totalNrOfResults` property gives the total number of results. When there are more than 250 results, the API limits the response array to the first 250 results. You can use the `offset=250` request parameter to fetch the second ‘page’ of results 
    remote isolated function search(map<string|string[]> headers = {}, *SearchQueries queries) returns http:Response|error {
        string resourcePath = string `/p/search`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.workspaceClient->get(resourcePath, withSessionHeaders(self.currentSessionHeaders(), headers));
    }

    # Returns all entity sets (Odata views) the user has access to. A JSON list is returned representing the entity set.
    #
    # + headers - Headers to be sent with the request 
    # + return - List all entity sets (OData views) the user has access to. The user has access if the underlying resources which the SIGNAL query in the view accesses (tables/views) are accessible. If this is not the case the entity (view) is not returned. A JSON list is given with all entities 
    remote isolated function getServiceDocument(map<string|string[]> headers = {}) returns ServiceDocument|error {
        http:Client odataClient = check self.getOdataClient();
        string resourcePath = string `/pi/signal/odata/v1/`;
        return odataClient->get(resourcePath, headers);
    }

    # Returns metadata for all entity sets (OData views) the user has access to. An XML schema is returned representing the metadata.
    #
    # + headers - Headers to be sent with the request
    # + return - Metadata information for all entity sets (OData views) the user has access to. The user has access if the underlying resources which the SIGNAL query in the view accesses (tables/views) are accessible. If this is not the case the entity (view) is not returned. A XML schema is given as metadata
    remote isolated function getMetadata(map<string|string[]> headers = {}) returns xml|error {
        http:Client odataClient = check self.getOdataClient();
        string resourcePath = string `/pi/signal/odata/v1/$metadata`;
        return odataClient->get(resourcePath, headers);
    }

    # This endpoint implements an OData service endpoint according to version 4.0 of
    # the OData Protocol specification.
    #
    # + entitySetName - The name for the entity set (in this case, the oData view). Can be returned by calling the /$metadata endpoint
    # + headers - Headers to be sent with the request
    # + queries - Queries to be sent with the request
    # + return - Data for the given entity, returned as a JSON schema
    remote isolated function queryEntitySet(string entitySetName, map<string|string[]> headers = {}, *QueryEntitySetQueries queries) returns OdataOutput|error {
        http:Client odataClient = check self.getOdataClient();
        string resourcePath = string `/pi/signal/odata/v1/${getEncodedUri(entitySetName)}`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return odataClient->get(resourcePath, headers);
    }

    # Returns the client authenticated for the SIGNAL Engine OData API, or an error if
    # `auth.odataAccessToken` was not supplied when the connector was initialized.
    #
    # + return - The OData-authenticated client, or an error
    private isolated function getOdataClient() returns http:Client|error {
        http:Client? odataClient = self.odataClient;
        if odataClient is () {
            return error("An 'odataAccessToken' must be provided in the connector configuration to call the SIGNAL Engine OData API");
        }
        return odataClient;
    }
}
