// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/constraint;
import ballerina/data.jsondata;
import ballerina/http;

# Non-standard meta-information that can not be represented as an attribute or relationship
public type Meta record {
};

# Represents the Queries record for the operation: getTaskCase
public type GetTaskCaseQueries record {
    # cases field to include
    string 'field = "id,creator";
};

# Represents the Queries record for the operation: createModel
public type CreateModelQueries record {
    # A timestamp or unique string used to prevent caching issues
    @http:Query {name: "_dc"}
    string dc?;
};

# The JSON:API resource ID
public type CasesIdResourceAttribute record {
    # The date
    string date?;
    # The timestamp (epoch seconds)
    int:Signed32 timestamp?;
};

# Represents the Headers record for the operation: updateDictionaryCategory
public type UpdateDictionaryCategoryHeaders record {
    # application/x-www-form-urlencoded
    @http:Header {name: "Content-Type"}
    string contentType = "application/x-www-form-urlencoded";
};

public type CasesCreatorResourceAttribute UsersResourceReference;

public type FilesResourceReferencesResponseSchema record {
    FilesResourceReference[] data?;
};

# A JSON:API document with a single resource
public type Success record {
    # The JSON:API version information
    JsonApi jsonapi?;
    # Non-standard meta-information that can not be represented as an attribute or relationship
    Meta meta?;
    # Link members related to the primary data
    Links links?;
    # Included resources
    SuccessIncluded[] included?;
};

public type UsersResourceReference record {
    # The JSON:API resource ID
    UsersIdResourceAttribute id;
    # The JSON:API resource type (Users)
    "Users" 'type;
};

public type GroupsUsersResourceAttribute UsersResourceReference[]?;

public type TokenRequest record {
    # Authenticating user's password
    string password;
    # Authenticating user's email address
    string name;
    # Must be set to retrieve the JWT
    boolean tokenonly;
    # Unique identifier of the target workspace. Only necessary if the authenticating user is a member of multiple workspaces
    string tenant?;
};

public type DictionaryEntryUpdateRequest record {
    Spmv1glossaryAttachments[] attachments?;
    record {} metaDataValues?;
    # A description of the entry
    string description?;
    # Force the update to occur. This parameter must be set to `true` if the item being updated has a non-unique name
    boolean force?;
    # The entry's title
    string title;
    # The desired dictionary category's ID
    string category;
};

# Represents the Headers record for the operation: listGroupUsers
public type ListGroupUsersHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

public type ValueDriver "IT_CAPACITY_PLANNING"|"IMPROVE_DEMAND_FORECAST_ACCURACY"|"IMPROVE_ON_TIME_DELIVERY"|"IMPROVE_FTE_PRODUCTIVITY"|"IMPROVE_USER_COMPLIANCE"|"INCREASE_CASH_FORECAST_ACCURACY"|"INCREASE_DAYS_PAYABLES"|"INCREASE_EFFECTIVENESS_MARKETING"|"OPERATIONAL_EXCELLENCE"|"REDUCE_HR_MANUAL_TRANSACTION"|"REDUCE_ASSET_COST"|"REDUCE_CUSTOMER_CHURN"|"REDUCE_DATA_MANAGEMENT_COST"|"REDUCE_DAYS_IN_INVENTORY"|"REDUCE_DAYS_SALES"|"REDUCE_DAYS_CLOSE_ANNUAL_BOOKS"|"REDUCE_FINANCE_COST"|"REDUCE_MANUFACTURING_CYCLE_TIME"|"REDUCE_READING_TO_INVOICE_TIME"|"REDUCE_NON_COMPLIANT_SERVICES"|"REDUCE_SUPPLY_CHAIN_PLANNING_COST"|"REDUCE_REVENUE_LOSS"|"REDUCE_SALES_COSTS"|"REDUCE_SERVICE_SUPPORT_COST"|"REDUCE_TIME_TO_FILL"|"REDUCE_TIME_TO_MARKET"|"REDUCE_LOGISTICS_COST"|"REDUCE_MANUFACTURING_COSTS"|"REDUCE_UNPLANNED_DOWNTIME"|"REDUCE_UNCOLLECTIBLE_ACCOUNTS"|"REDUCE_EMISSIONS_COST"|"REDUCE_WASTE_GENERATION_COST"|"REDUCE_COMPLIANCE_AND_RISK_MANAGEMENT_COST"|"INCREASE_BUSINESS_PROCESS_HARMONIZATION"|"INCREASE_ADHERENCE_TO_STANDARDIZED_SAP_BUSINESS_PROCESSES";

// >>> MANUALLY MAINTAINED - NOT REGENERATED. `Credentials` and `ConnectionConfig` are hand-written
// overrides (see docs/spec/sanitations.md item 2); `bal openapi` does not produce them. Reconcile
// this block against any regenerated output before committing a regeneration. <<<
# SAP Signavio account credentials. The connector uses these to transparently
# obtain both the API gateway access token (`POST /auth/v1/token`) and the
# Process Manager workspace session (`POST /p/login`) - no separate login
# step is required from the caller.
public type Credentials record {|
    # The account's user name (typically an email address)
    string username;
    # The account's password
    string password;
    # Unique identifier of the target workspace. Only necessary if the authenticating user is a member of multiple workspaces
    string tenant?;
    # A SAP Signavio OData API access token. Only required to call `getServiceDocument`, `getMetadata`, or `queryEntitySet` -
    # the SIGNAL Engine OData API authenticates with a dedicated access token rather than the account password, and that
    # token can only be generated from the SAP Signavio UI, so it cannot be derived from `username`/`password` automatically
    string odataAccessToken?;
|};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # SAP Signavio account credentials
    Credentials auth;
    # The SAP Signavio region that hosts the workspace. Determines both the API gateway hostname
    # (`api.<region>.signavio.cloud.sap`) and the Process Manager workspace hostname (`app-<region>.signavio.com`)
    string region = "eu";
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional,
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};
// <<< END MANUALLY MAINTAINED block (Credentials / ConnectionConfig) >>>

public type UsersNameResourceAttribute string?;

public type Status record {
    boolean deleted?;
    boolean approve?;
    boolean publish?;
    string id?;
};

# Represents the Headers record for the operation: listCaseTasks
public type ListCaseTasksHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

public type InitiativeType "STANDARD"|"PINT_MANAGED";

public type BpmnImportResult record {
    # The number of updated models
    int numUpdated?;
    # The IDs of the created models
    string[] createdIds?;
    Messages warnings?;
    # The ID of the main model
    string mainModelId?;
    # The number of created models
    int numCreated?;
    # The IDs of the updated models
    string[] updatedIds?;
    Messages errors?;
};

public type CaseVariablesResourceResponseSchema record {
    *Success;
    CaseVariablesResourceSchema data;
};

public type CesMeasurement record {
    *Measurement;
    int:Signed32 numDifficult;
    int:Signed32 numVeryDifficult?;
    int:Signed32 numBitEasy?;
    "ONE_TO_THREE"|"ONE_TO_FIVE"|"ONE_TO_SEVEN" scale;
    int:Signed32 numVeryEasy?;
    int:Signed32 numNeutral;
    int:Signed32 numEasy;
    int:Signed32 numBitDifficult?;
};

# Represents the Queries record for the operation: listCaseTasks
public type ListCaseTasksQueries record {
    # tasks field to include
    string fields = "id";
    # Filter by id (csv)
    @http:Query {name: "filter[id]"}
    string filterId?;
};

# Represents the Queries record for the operation: listModelRevisions
public type ListModelRevisionsQueries record {
    # The offset of the first revision to be returned
    int:Signed32 offset?;
    # A search query to filter the revisions
    string query?;
    # The maximum number of revisions to be returned
    int:Signed32 'limit?;
};

@constraint:String {pattern: re `^[0-9a-fA-F]{32}$`}
public type DirectoryId string;

@constraint:String {pattern: re `[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}`}
public type IncomingInsightAssigneesItemsString string;

public type CasesResourcesResponseSchema record {
    *Success;
    CasesResourceSchema[] data;
};

public type ModelResourceResponse record {
    string rel?;
    string href?;
    ModelRepresentation rep?;
};

public type TasksDueResourceAttribute int?;

# Represents the Queries record for the operation: getCase
public type GetCaseQueries record {
    # cases relationships to include (csv)
    string include = "creator,tasks,variables";
    # cases field to include
    string 'field = "id,creator";
};

public type AuthorizationType "USER"|"GROUP";

# Represents the Headers record for the operation: getDictionaryEntry
public type GetDictionaryEntryHeaders record {
};

public type UsersResourceResponseSchema record {
    *Success;
    UsersResourceSchema data;
};

public type InsightsValueDriver "IT_CAPACITY_PLANNING"|"IMPROVE_DEMAND_FORECAST_ACCURACY"|"IMPROVE_ON_TIME_DELIVERY"|"IMPROVE_FTE_PRODUCTIVITY"|"IMPROVE_USER_COMPLIANCE"|"INCREASE_CASH_FORECAST_ACCURACY"|"INCREASE_DAYS_PAYABLES"|"INCREASE_EFFECTIVENESS_MARKETING"|"OPERATIONAL_EXCELLENCE"|"REDUCE_HR_MANUAL_TRANSACTION"|"REDUCE_ASSET_COST"|"REDUCE_CUSTOMER_CHURN"|"REDUCE_DATA_MANAGEMENT_COST"|"REDUCE_DAYS_IN_INVENTORY"|"REDUCE_DAYS_SALES"|"REDUCE_DAYS_CLOSE_ANNUAL_BOOKS"|"REDUCE_FINANCE_COST"|"REDUCE_MANUFACTURING_CYCLE_TIME"|"REDUCE_READING_TO_INVOICE_TIME"|"REDUCE_NON_COMPLIANT_SERVICES"|"REDUCE_SUPPLY_CHAIN_PLANNING_COST"|"REDUCE_REVENUE_LOSS"|"REDUCE_SALES_COSTS"|"REDUCE_SERVICE_SUPPORT_COST"|"REDUCE_TIME_TO_FILL"|"REDUCE_TIME_TO_MARKET"|"REDUCE_LOGISTICS_COST"|"REDUCE_MANUFACTURING_COSTS"|"REDUCE_UNPLANNED_DOWNTIME"|"REDUCE_UNCOLLECTIBLE_ACCOUNTS";

public type CasesResourceAttributes record {
    CasesResourceAttributesAttributes attributes?;
};

public type ModelInfoRequest record {
    string parent?;
    record {} formats?;
    @jsondata:Name {value: "granted_revision_user"}
    string grantedRevisionUser?;
    string created?;
    string author?;
    boolean isLicensedStencilSet?;
    @jsondata:Name {value: "granted_revision_user_name"}
    string grantedRevisionUserName?;
    string description?;
    string 'type?;
    string authorCompany?;
    string revision?;
    string parentName?;
    string authorName?;
    boolean isDeployed?;
    string name?;
    string updated?;
    V1modelmodelIdinfoStatus status?;
};

# Represents the Headers record for the operation: getGroup
public type GetGroupHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

public type ModelResponse record {
    string rel?;
    string href?;
    Rep rep?;
};

public type DiagramJsonChildShape record {
    string resourceId?;
    record {} properties?;
};

public type NPSMeasurement record {
    *Measurement;
    int:Signed32 detractors;
    int:Signed32 promoters;
    int:Signed32 passives;
};

@constraint:String {pattern: re `^/[^/]+/[0-9a-fA-F]{32}$`}
public type ObjectReference string;

public type GroupsResourceReference record {
    # The JSON:API resource ID
    GroupsIdResourceAttribute id;
    # The JSON:API resource type (Groups)
    "Groups" 'type;
};

# The JSON:API resource ID
public type FilesIdResourceAttribute record {
    # The date
    string date?;
    # The timestamp (epoch seconds)
    int:Signed32 timestamp?;
};

# Represents the Queries record for the operation: listCases
public type ListCasesQueries record {
    # Max number of items
    @http:Query {name: "page[limit]"}
    int pageLimit = 100;
    # cases relationships to include (csv)
    string include = "creator,tasks,variables";
    # Page offset
    @http:Query {name: "page[offset]"}
    int pageOffset = 0;
    # Filter by processId
    @http:Query {name: "filter[processId]"}
    string filterProcessId?;
    # cases field to include
    string 'field = "id,creator";
};

# Represents the Headers record for the operation: getDictionaryCategory
public type GetDictionaryCategoryHeaders record {
};

public type CasesApplicationLinkResourceAttribute string?;

# Represents the Headers record for the operation: listTasks
public type ListTasksHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

public type DeleteDirectoryResponse record {
    boolean success?;
};

public type ObjectivesResponse record {
    int count?;
    Objective[] value?;
};

public type FilesResourcesResponseSchema record {
    *Success;
    FilesResourceSchema[] data;
};

public type TasksResourcesResponseSchema record {
    *Success;
    TasksResourceSchema[] data;
};

public type IngestionDataRequest record {
    # A Schema is represented in JSON following Apache Avro Specification of type record to define the table structure
    string schema;
    # Comma separated list of primary keys, for example primaryKeys=key1,key2,key3 (values must exist in the provided Schema)
    @constraint:Array {minLength: 1}
    string[] primaryKeys;
    # A character separating the data in the files. Default value is ","
    string delimiter = ",";
    # The data to be pushed. Supported formats are CSV and TSV
    @constraint:Array {minLength: 1}
    record {byte[] fileContent; string fileName;}[] files;
};

@constraint:String {pattern: re `[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}`}
public type IncomingInsightInitiativesItemsString string;

public type CsatMeasurement record {
    *Measurement;
    int:Signed32 numDissatisfied;
    int:Signed32 numHighlySatisfied;
    int:Signed32 numHighlyDissatisfied;
    int:Signed32 numSatisfied;
    int:Signed32 numNeutral;
};

# Represents the Queries record for the operation: listCaseVariableCases
public type ListCaseVariableCasesQueries record {
    # cases relationships to include (csv)
    string include = "creator,tasks,variables";
    # cases field to include
    string 'field = "id,creator";
};

public type GroupsResourceResponseSchema record {
    *Success;
    GroupsResourceSchema data;
};

public type Rep record {
    string parent?;
    record {} formats?;
    @jsondata:Name {value: "granted_revision_user"}
    string grantedRevisionUser?;
    boolean isLicensedStencilSet?;
    @jsondata:Name {value: "granted_revision_user_name"}
    string grantedRevisionUserName?;
    string description?;
    string 'type?;
    @jsondata:Name {value: "sri_revision"}
    string sriRevision?;
    @jsondata:Name {value: "sri_path"}
    string sriPath?;
    boolean isDeployed?;
    @jsondata:Name {value: "granted_revision"}
    string grantedRevision?;
    int rev?;
    string created?;
    string author?;
    @jsondata:Name {value: "granted_revision_date"}
    string grantedRevisionDate?;
    string sri?;
    string authorCompany?;
    string revision?;
    string parentName?;
    boolean deleted?;
    string authorName?;
    string name?;
    string namespace?;
    string comment?;
    string updated?;
    Status status?;
};

public type CasesTasksResourceAttribute TasksResourceReference[]?;

# Represents the Headers record for the operation: deleteDictionaryCategory
public type DeleteDictionaryCategoryHeaders record {
};

public type UsersResourceAttributes record {
    UsersResourceAttributesAttributes attributes?;
};

# Represents the Queries record for the operation: listDictionaryCategories
public type ListDictionaryCategoriesQueries record {
    # If set to `true`, hidden categories are included in the response
    boolean showHidden?;
    # If set to `true`, all categories' representations are returned  at once, without the need to send additional queries for  sub-categories
    boolean allCategories?;
    # To circumvent access restrictions as a member of the workspace's  administrators group, set this parameter to true
    boolean considerAllPrivilege?;
};

# Represents the Headers record for the operation: getCaseVariable
public type GetCaseVariableHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

# Represents the Queries record for the operation: listCaseVariables
public type ListCaseVariablesQueries record {
    # Max number of items
    @http:Query {name: "page[limit]"}
    int pageLimit = 100;
    # case-variables relationship to include
    string include = "case";
    # Page offset
    @http:Query {name: "page[offset]"}
    int pageOffset = 0;
    # Filter by id (csv)
    @http:Query {name: "filter[id]"}
    string filterId;
};

public type CaseVariablesValuesResourceAttribute record {}[]?;

public type GroupsResourceReferencesResponseSchema record {
    GroupsResourceReference[] data?;
};

# Represents the Headers record for the operation: deleteDictionaryEntry
public type DeleteDictionaryEntryHeaders record {
};

# Represents the Queries record for the operation: listTasks
public type ListTasksQueries record {
    # Max number of items
    @http:Query {name: "page[limit]"}
    int pageLimit = 100;
    # tasks relationships to include (csv)
    string include = "case";
    # Page offset
    @http:Query {name: "page[offset]"}
    int pageOffset = 0;
    # Filter by assignee
    @http:Query {name: "filter[assignee.email]"}
    string filterAssigneeEmail?;
    # Filter by case
    @http:Query {name: "filter[case.id]"}
    string filterCaseId?;
    # Filter by completed
    @http:Query {name: "filter[completed]"}
    string filterCompleted?;
    # tasks field to include
    string fields = "id";
    # Filter by id (csv)
    @http:Query {name: "filter[id]"}
    string filterId?;
};

public type SyntaxCheckRepresentation record {
    record {} should?;
    record {|string[]...;|} must?;
    string guidelineId?;
};

public type GroupsResourceSchema record {
    *GroupsResourceReference;
    *GroupsResourceAttributes;
    GroupsResourceAttributesAttributes attributes;
    record {} relationships?;
    record {} links?;
};

public type Insight record {
    UserInfo updatedBy;
    @constraint:Array {maxLength: 100}
    InsightsValueDriver[] valueDrivers;
    @constraint:Array {maxLength: 100}
    Authorization[] authorizations;
    string description?;
    @constraint:Array {maxLength: 100}
    UserInfo[] assignees;
    string sri;
    OffsetDateTime dateUpdated;
    Tag[] tags;
    OffsetDateTime dateCreated;
    UserInfo createdBy;
    DiscoveryReference[] discoveries;
    string name;
    float priorityScore;
    InsightInitiativesItemsString[] initiatives?;
    UUID id;
    float effortScore;
    float impactScore;
    InsightStatus status;
};

public type IncomingInitiative record {
    OffsetDateTime endDate?;
    string name;
    @constraint:Array {maxLength: 100}
    ValueDriver[] valueDrivers;
    @constraint:Array {maxLength: 100, minLength: 1}
    IncomingAuthorization[] authorizations;
    string description?;
    OffsetDateTime startDate?;
    InitiativeStatus status;
};

public type BpmnImportRequest record {
    # The filename and content of the BPMN 2.0 XML file
    @jsondata:Name {value: "bpmn2_0file"}
    record {byte[] fileContent; string fileName;} bpmn2File;
    # The ID of the model to create a new revision for
    string modelid?;
    # The directory where the content of the BPMN 2.0 XML file should be imported into
    string directory?;
};

public type CasesProcessIdResourceAttribute record {
    string date?;
    int:Signed32 timestamp?;
};

public type TasksResourceReference record {
    # The JSON:API resource ID
    TasksIdResourceAttribute id;
    # The JSON:API resource type (Tasks)
    "Tasks" 'type;
};

public type UsersResourceReferencesResponseSchema record {
    UsersResourceReference[] data?;
};

public type BenchmarkingAnalyticsContext record {
    @constraint:String {maxLength: 150}
    string metricBenchmarkContainerId?;
    @constraint:String {maxLength: 100}
    string e2eProcessId?;
};

public type FilesResourceSchema record {
    *FilesResourceReference;
    *FilesResourceAttributes;
    FilesResourceAttributesAttributes attributes;
    record {} relationships?;
    record {} links?;
};

@constraint:String {pattern: re `[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}`}
public type UserInfoUserGroupIdsItemsString string;

public type Representation record {
    record {} formats?;
    anydata[] attachments?;
    string color?;
    boolean hidden?;
    @jsondata:Name {value: "granted_revision_user"}
    string grantedRevisionUser?;
    boolean workflowSyncUpToDate?;
    # Array of prefixed IDs of categories that have this category  as parent category
    string publishingMode?;
    @jsondata:Name {value: "granted_revision_user_name"}
    string grantedRevisionUserName?;
    int linkedCount?;
    string description?;
    string language?;
    string[] childCategories?;
    int occurrence?;
    string[] replacedItemIds?;
    string title?;
    int childCategoryCount?;
    string 'type?;
    string categoryName?;
    int headRevisionNum?;
    int linkedByCount?;
    record {} metaDataValues?;
    boolean isEnabledForDimensions?;
    string id?;
    boolean hasAttachments?;
    # ID of the workspaces's Dictionary (not relevant for API access)
    string glossaryId?;
    int 'order?;
    string headRevision?;
    @jsondata:Name {value: "granted_revision"}
    string grantedRevision?;
    @jsondata:Name {value: "granted_revision_number"}
    int grantedRevisionNumber?;
    boolean decisionInput?;
    boolean isDimension?;
    string author?;
    @jsondata:Name {value: "granted_revision_date"}
    string grantedRevisionDate?;
    string authorCompany?;
    int itemCount?;
    boolean isStandard?;
    boolean workflowSyncEnabled?;
    string name?;
    # If the category corresponds to one of the six standard  categories, this field is set. For example, some reports  consider the content of these categories. The following  `oldCategories` exist:
    # 
    #   * `ORG_UNIT` - Organizational units
    #   * `DOCUMENT` - Documents
    #   * `ACTIVITY` - Activities
    #   * `STATE` - Events
    #   * `IT_SYSTEM` - IT systems
    #   * `NONE` - Everything else
    string oldCategory?;
    string parentCategory?;
    string comment?;
    string decisionDataObjectKey?;
    string category?;
    anydata[] items?;
    string updated?;
    string sendingInterval?;
    string linkingPublishedModelsUpdateMode?;
};

# The JSON:API resource ID
public type CaseVariablesIdResourceAttribute record {
    # The case identifier
    CaseVariablesIdResourceAttributeCazeId cazeId?;
    # The unique identifier
    string id?;
};

public type DiagramJson record {
    string resourceId?;
    record {} properties?;
    DiagramJsonChildShape[] childShapes?;
};

public type Role "OWNER"|"EDITOR"|"VIEWER";

public type DictionaryResponse record {
    string rel;
    string href;
    // Shape varies by `rel`: a `Representation`-like object for `gitem`/`cat`/`info`, an array
    // for relation-only entries like `priv`, and further nested hypermedia objects for
    // `parents` - `json` is used rather than a narrower union to accept all of these.
    json rep;
};

public type UsersResourcesResponseSchema record {
    *Success;
    UsersResourceSchema[] data;
};

public type OffsetDateTime string;

# Represents the Headers record for the operation: getCase
public type GetCaseHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

public type TasksResourceAttributesAttributes record {
    TasksDueResourceAttribute? due?;
    TasksCreatedResourceAttribute? created?;
    TasksNameResourceAttribute? name?;
    TasksAssigneeResourceAttribute? assignee?;
    TasksCompletedResourceAttribute? completed?;
    TasksUpdatedResourceAttribute? updated?;
    TasksCaseResourceAttribute case?;
    TasksApplicationLinkResourceAttribute? applicationLink?;
};

# Represents the Queries record for the operation: getTask
public type GetTaskQueries record {
    # tasks relationships to include (csv)
    string include = "case";
    # tasks field to include
    string fields = "id";
};

public type CasesClosedResourceAttribute int?;

public type IncomingAsset record {
    string name;
    string description?;
    AssetType 'type;
    string url;
};

public type Measurement record {
    int:Signed32 score;
    string time;
};

# Represents the Headers record for the operation: getTaskCase
public type GetTaskCaseHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

# Represents the Headers record for the operation: listGroups
public type ListGroupsHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

public type UsersResourceSchema record {
    *UsersResourceReference;
    *UsersResourceAttributes;
    UsersResourceAttributesAttributes attributes;
    record {} relationships?;
    record {} links?;
};

public type InitiativeSummaryForObjective record {
    UserInfo updatedBy?;
    OffsetDateTime endDate?;
    @constraint:Array {maxLength: 100}
    ValueDriver[] valueDrivers;
    @constraint:Array {maxLength: 100}
    Authorization[] authorizations;
    string description?;
    InitiativeType 'type;
    @constraint:String {pattern: re `^SuiteInitiative_[0-9a-fA-F]{32}$`}
    string sid;
    OffsetDateTime dateUpdated;
    OffsetDateTime dateCreated;
    UserInfo createdBy;
    string name;
    OffsetDateTime lastActivity;
    OffsetDateTime startDate?;
    InitiativeStatus status;
};

public type ProcessIntelligenceCanvasType "INVESTIGATION"|"DASHBOARD";

# Represents the Queries record for the operation: listObjectives
public type ListObjectivesQueries record {
    # Page size (max 1000)
    @constraint:Int {minValue: 1, maxValue: 1000}
    int:Signed32 size = 10;
    # Zero-based page index (0 = first page)
    @constraint:Int {minValue: 0}
    int:Signed32 page = 0;
    # Include approximate total count in response when true
    @http:Query {name: "$count"}
    boolean dollarCount = false;
};

public type UserInfo record {
    string firstName?;
    string lastName?;
    string displayName?;
    UUID id;
    UserInfoUserGroupIdsItemsString[] userGroupIds;
    string email?;
};

public type TasksAssigneeResourceAttribute record {
    string name?;
    string email?;
};

public type CaseVariablesResourceReference record {
    # The JSON:API resource ID
    CaseVariablesIdResourceAttribute id;
    # The JSON:API resource type (Case-variables)
    "Case-variables" 'type;
};

public type CaseVariablesResourcesResponseSchema record {
    *Success;
    CaseVariablesResourceSchema[] data;
};

# Represents the Headers record for the operation: listCaseVariables
public type ListCaseVariablesHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

# Represents the Headers record for the operation: listDictionaryCategories
public type ListDictionaryCategoriesHeaders record {
};

public type CasesResourceReferencesResponseSchema record {
    CasesResourceReference[] data?;
};

public type Spmv1glossaryAttachments record {
    string label?;
    string url?;
};

public type JsonApi record {|
    string version?;
|};

public type CreateDirectoryRequest record {
    ObjectReference parent?;
    string name?;
};

public type Initiative record {
    UserInfo updatedBy;
    OffsetDateTime endDate?;
    @constraint:Array {maxLength: 100}
    ValueDriver[] valueDrivers;
    Authorization[] authorizations;
    string description?;
    string sri;
    InitiativeType 'type;
    OffsetDateTime dateUpdated;
    OffsetDateTime dateCreated;
    UserInfo createdBy;
    string name;
    OffsetDateTime lastActivity;
    UUID id;
    OffsetDateTime startDate?;
    InitiativeStatus status;
};

public type CasesCaseNumberResourceAttribute int:Signed32?;

# Represents the Queries record for the operation: queryEntitySet
public type QueryEntitySetQueries record {
    # Not implemented
    @http:Query {name: "$deltatoken"}
    string dollarDeltatoken?;
    # A positive integer value that specifies the maximum number of entries to return, reduced by the value of skiptoken
    @http:Query {name: "$top"}
    int dollarTop?;
    # A filter expression that all entries in the result set must match
    @http:Query {name: "$filter"}
    string dollarFilter?;
    # An opaque value that enables consistent pagination of results. Included in the value of the `@odata.nextLink` parameter of a paginated OData result response
    @http:Query {name: "$skiptoken"}
    string dollarSkiptoken?;
    # Not implemented
    @http:Query {name: "$orderby"}
    string dollarOrderby?;
    # Not implemented
    @http:Query {name: "$search"}
    string dollarSearch?;
    # Not implemented
    @http:Query {name: "$expand"}
    string dollarExpand?;
    # A positive integer value that specifies the number of entries to skip before returning the remainder
    @constraint:Int {minValue: 0}
    int skip?;
    # Requested response format from the client.
    # If specified, `$format` overrides any value specified in the `Accept` header,
    # based on the OData specification 4.0.
    # 
    # Currently only `application/json` is supported
    @http:Query {name: "$format"}
    string dollarFormat?;
    # System query option `inlinecount`.
    # 
    # If specified, then the server will return the number of entries as an integer
    @http:Query {name: "$count"}
    boolean dollarCount?;
    # Not implemented
    @http:Query {name: "$id"}
    string dollarId?;
    # The list of properties that each returned entry will specify
    @http:Query {name: "$select"}
    string[] dollarSelect;
};

public type TasksCaseResourceAttribute CasesResourceReference;

# Represents the Headers record for the operation: getCaseCreator
public type GetCaseCreatorHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

# Represents the Headers record for the operation: listCaseVariableCases
public type ListCaseVariableCasesHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

public type FilesResourceReference record {
    # The JSON:API resource ID
    FilesIdResourceAttribute id;
    # The JSON:API resource type (Files)
    "Files" 'type;
};

public type MetaInfoRequest record {
    # JSON string representing stencilset bindings
    string stencilsetBindings;
    # Parent path of the meta information
    string parent;
    # German name of the meta information
    @jsondata:Name {value: "name_de_de"}
    string nameDeDe?;
    # English description of the meta information
    @jsondata:Name {value: "description_en_gb"}
    string descriptionEnGb?;
    # Spanish description of the meta information
    @jsondata:Name {value: "description_es_es"}
    string descriptionEsEs?;
    # Name of the meta information
    string name;
    # Spanish name of the meta information
    @jsondata:Name {value: "name_es_es"}
    string nameEsEs?;
    # German description of the meta information
    @jsondata:Name {value: "description_de_de"}
    string descriptionDeDe?;
    # Indicates if it is a glossary definition
    boolean isGlossaryDefinition;
    # English name of the meta information
    @jsondata:Name {value: "name_en_gb"}
    string nameEnGb?;
    # Type of the meta information
    string 'type;
};

# Represents the Queries record for the operation: listUsers
public type ListUsersQueries record {
    # Max number of items
    @http:Query {name: "page[limit]"}
    int pageLimit = 100;
    # Page offset
    @http:Query {name: "page[offset]"}
    int pageOffset = 0;
    # Filter by id (csv)
    @http:Query {name: "filter[id]"}
    string filterId?;
};

public type CaseVariablesCaseResourceAttribute CasesResourceReference;

# Represents the Headers record for the operation: listUsers
public type ListUsersHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

public type V1modelmodelIdrevisionsRep record {
    int rev?;
    int size?;
    string author?;
    string authorName?;
    string created?;
    boolean isDeployed?;
    string comment?;
    string authorCompany?;
    string status?;
};

public type ModelRevisionsResponse record {
    string rel?;
    string href?;
    V1modelmodelIdrevisionsRep rep?;
};

public type CasesPriorityResourceAttribute int:Signed32?;

# Represents the Headers record for the operation: listDictionaryEntries
public type ListDictionaryEntriesHeaders record {
    # application/x-www-form-urlencoded
    @http:Header {name: "Content-Type"}
    string contentType = "application/x-www-form-urlencoded";
};

@constraint:String {pattern: re `[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}`}
public type InsightInitiativesItemsString string;

public type ModelRepresentation record {
    string allowedMimeTypeRegex?;
    boolean deleted?;
    boolean visible?;
    string created?;
    string name?;
    string description?;
    string 'type?;
    string sendingInterval?;
    @jsondata:Name {value: "name_en"}
    string nameEn?;
};

public type CasesMilestoneResourceAttribute string?;

public type CaseVariablesResourceAttributes record {
    CaseVariablesResourceAttributesAttributes attributes?;
};

# Represents the Queries record for the operation: listGroups
public type ListGroupsQueries record {
    # Max number of items
    @http:Query {name: "page[limit]"}
    int pageLimit = 100;
    # groups relationships to include (csv)
    string include = "users";
    # Page offset
    @http:Query {name: "page[offset]"}
    int pageOffset = 0;
    # groups fields to include (csv)
    string fields = "id,name,users";
    # Filter by id (csv)
    @http:Query {name: "filter[id]"}
    string filterId?;
};

# The JSON:API resource ID
public type UsersIdResourceAttribute record {
    # The date
    string date?;
    # The timestamp (epoch seconds)
    int:Signed32 timestamp?;
};

public type Asset record {
    Initiative initiative;
    UserInfo updatedBy?;
    OffsetDateTime dateCreated;
    UserInfo createdBy;
    @constraint:String {pattern: re `\S`}
    string name;
    string description?;
    UUID id;
    AssetType 'type;
    string url;
    OffsetDateTime dateUpdated;
};

# Represents the Queries record for the operation: updateModel
public type UpdateModelQueries record {
    # A timestamp or unique string used to prevent caching issues
    @http:Query {name: "_dc"}
    string dc?;
};

public type CaseVariablesIdResourceAttributeCazeId record {
    string date?;
    int:Signed32 timestamp?;
};

public type DmnDownloadLinkResponse record {
    string rel?;
    string href?;
    DmnDownloadRepresentation rep?;
};

public type SuccessResponse record {
    boolean success?;
};

public type CasesResourceReferenceResponseSchema record {
    CasesResourceReference data?;
};

public type Messages MessagesInner[];

public type V1modelmodelIdinfoStatus record {
    boolean deleted?;
    boolean approve?;
    boolean publish?;
    string id?;
};

# Represents the Headers record for the operation: getTask
public type GetTaskHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

public type UsersEmailResourceAttribute string?;

public type MetaResponseItemRep record {
    record {}[] glossaryBindings?;
    boolean lineWrap?;
    string defaultValue?;
    int length?;
    string description?;
    boolean isGlossaryDefinition?;
    @jsondata:Name {value: "name_en_gb"}
    string nameEnGb?;
    string 'type?;
    boolean isList?;
    boolean multilanguage?;
    StencilsetBinding[] stencilsetBindings?;
    @jsondata:Name {value: "name_de_de"}
    string nameDeDe?;
    boolean 'readonly?;
    string name?;
    string id?;
};

public type FilesNameResourceAttribute string?;

# Represents the Queries record for the operation: getUser
public type GetUserQueries record {
    # users fields to include (csv)
    string fields = "id,name,email";
};

public type DmnDownloadRepresentation record {
    boolean success?;
    string downloadUrl?;
    string[] messages?;
};

public type CasesResourceReference record {
    # The JSON:API resource ID
    CasesIdResourceAttribute id;
    # The JSON:API resource type (Cases)
    "Cases" 'type;
};

# `OdataOutput` represents an OData document according to version 4.0 of the
# [JSON format specification](http://docs.oasis-open.org/odata/odata-json-format/v4.0/odata-json-format-v4.0.html).
# It can serialized into a JSON
public type OdataOutput record {
    # A link to the next page of results
    @jsondata:Name {value: "@odata.nextLink"}
    string? atOdataNextLink?;
    # The total number of entities matching the request
    @jsondata:Name {value: "@odata.count"}
    int? atOdataCount?;
    # The OData context URL for the response
    @jsondata:Name {value: "@odata.context"}
    string atOdataContext;
    # The value of the item
    anydata[] value;
};

public type GroupsResourceAttributesAttributes record {
    GroupsNameResourceAttribute? name?;
    GroupsUsersResourceAttribute? users?;
};

# Represents the Queries record for the operation: getRevisionBpmnXml
public type GetRevisionBpmnXmlQueries record {
    # Whether to include linked subprocesses
    boolean exportSubprocesses?;
    # Which tenant content language to use as the primary language of the exported XML
    string language?;
};

public type MessagesInner record {
    # Additional details for this message
    record {}[] details?;
    # The message itself
    string 'type?;
};

# Represents the Headers record for the operation: listCaseVariableCaseRefs
public type ListCaseVariableCaseRefsHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

public type TasksResourceResponseSchema record {
    *Success;
    TasksResourceSchema data;
};

public type GroupsNameResourceAttribute string?;

# Represents the Queries record for the operation: listDictionaryEntries
public type ListDictionaryEntriesQueries record {
    # Filters by a full-text search term (ignored when `letter` is specified)
    string q?;
    # If set to `all`, dictionary entries from a category and its subcategories are listed
    string include?;
    # The number of entries to skip before returning entries. Useful in combination with `limit` for pagination
    int offset?;
    # Filters by the initial letter of the dictionary entry's title
    string letter?;
    # The maximum number of entries to return
    int 'limit?;
    # If set to `title`, sorts entries by title; otherwise, the search sorts results by a dynamically determined relevance score
    string sort?;
    # Filters by entry type - `ORG_UNIT`, `DOCUMENT`, `ACTIVITY`, `STATE`, or `IT_SYSTEM`, representing the pre-defined dictionary categories "Organizational Units", "Documents", "Activities",  "Events", and "IT Systems", respectively, or a Dictionary  category's ID
    string category?;
};

# Represents the Queries record for the operation: deleteDictionaryCategory
public type DeleteDictionaryCategoryQueries record {
    # If set to `true`, before deleting the category with  all its sub-categories, the content is moved to the 'Others'  category. Otherwise, sub-categories and all contained dictionary  entries and the sub-categories' contained dictionary entries will  be deleted
    boolean moveContent;
};

public type Authorization record {
    Role role;
    AuthorizationType targetType;
    AuthorizationTargetInfo target;
};

# An entry in the OData service document.
# Details can be found in the
# [OData JSON specification](https://docs.oasis-open.org/odata/odata-json-format/v4.0/odata-json-format-v4.0.html#_Toc453766639)
public type ServiceDocumentEntity record {
    # The kind of the item
    string kind;
    # The name of the item
    string name;
    # The URL of the item
    string url;
};

public type TasksApplicationLinkResourceAttribute string?;

public type HyperMediaObject record {
    string rel?;
    string href?;
    // The real API returns an object shape for `dir`/`mod`/`glos` entries, but an
    // array (or empty array) for hypermedia-relation entries like `priv`/`parents`
    // - `json` is used rather than `record {}` to accept both.
    json rep?;
};

public type AuthorizationTargetInfo record {
    string displayName?;
    UUID id;
};

# Represents the Queries record for the operation: search
public type SearchQueries record {
    # The search term
    string q;
    # List of content types the search should include, from `MODEL`, `MODEL_REVISION`, `SHAPE`, `FILE`, `FILE_REVISION`, `DIR` and `COMMENT`
    string types?;
    # Index of first search result to return
    string offset?;
    # e.g. explorer
    string contentmode?;
    # Maximum number of search results, up to 250
    string 'limit?;
    # Example: [{"id":"search.searchableFields.all","textQueries":[{"matching":"contains","text":"foo-bar"}]}]
    @http:Query {name: "fields_json"}
    string fieldsJson?;
};

public type CasesNameResourceAttribute string?;

# Represents the Queries record for the operation: getFile
public type GetFileQueries record {
    # files fields to include (csv)
    string fields = "id,name,size";
};

public type TasksNameResourceAttribute string?;

# Represents the Queries record for the operation: listInsightsInInitiative
public type ListInsightsInInitiativeQueries record {
    # Page number (1-based, the first page has number 1)
    @constraint:Int {minValue: 1}
    int:Signed32 pageNumber = 1;
    # Only list insights that contain this substring. This parameter can be repeated
    string nameContains?;
    # Only list insights containing discoveries from process intelligence with this canvas type. This parameter can be repeated
    "INVESTIGATION"|"DASHBOARD" processIntelligenceCanvasType?;
    # Only list insights containing this value driver. This parameter can be repeated
    "IT_CAPACITY_PLANNING"|"IMPROVE_DEMAND_FORECAST_ACCURACY"|"IMPROVE_ON_TIME_DELIVERY"|"IMPROVE_FTE_PRODUCTIVITY"|"IMPROVE_USER_COMPLIANCE"|"INCREASE_CASH_FORECAST_ACCURACY"|"INCREASE_DAYS_PAYABLES"|"INCREASE_EFFECTIVENESS_MARKETING"|"OPERATIONAL_EXCELLENCE"|"REDUCE_HR_MANUAL_TRANSACTION"|"REDUCE_ASSET_COST"|"REDUCE_CUSTOMER_CHURN"|"REDUCE_DATA_MANAGEMENT_COST"|"REDUCE_DAYS_IN_INVENTORY"|"REDUCE_DAYS_SALES"|"REDUCE_DAYS_CLOSE_ANNUAL_BOOKS"|"REDUCE_FINANCE_COST"|"REDUCE_MANUFACTURING_CYCLE_TIME"|"REDUCE_READING_TO_INVOICE_TIME"|"REDUCE_NON_COMPLIANT_SERVICES"|"REDUCE_SUPPLY_CHAIN_PLANNING_COST"|"REDUCE_REVENUE_LOSS"|"REDUCE_SALES_COSTS"|"REDUCE_SERVICE_SUPPORT_COST"|"REDUCE_TIME_TO_FILL"|"REDUCE_TIME_TO_MARKET"|"REDUCE_LOGISTICS_COST"|"REDUCE_MANUFACTURING_COSTS"|"REDUCE_UNPLANNED_DOWNTIME"|"REDUCE_UNCOLLECTIBLE_ACCOUNTS" valueDriver?;
    # Only list insights containing discoveries with this domain application. This parameter can be repeated
    "PROCESS_MANAGER"|"PROCESS_INTELLIGENCE"|"PROCESS_INSIGHTS"|"BENCHMARKING_ANALYTICS"|"JOURNEY_MODELER"|"SUITE_CAPABILITIES"|"PROCESS_GOVERNANCE" discoveryReferenceApplication?;
    # Only list insights containing discoveries from process insights with this process flow id. This parameter can be repeated
    string processInsightsProcessFlowId?;
    # Number of entries per page
    @constraint:Int {minValue: 1}
    int:Signed32 pageSize = 10;
    # Only list insights containing discoveries from process intelligence with this widget id. This parameter can be repeated
    string processIntelligenceWidgetId?;
    # Only list insights containing discoveries from process intelligence with this process id. This parameter can be repeated
    string processIntelligenceProcessId?;
    # Only list insights which were created by this user. This parameter can be repeated
    @constraint:String {pattern: re `[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}`}
    string createdBy?;
    # Only list insights containing discoveries from process insights with this system id. This parameter can be repeated
    @constraint:String {pattern: re `[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}`}
    string processInsightsSystemId?;
    # Order to sort the initiatives by
    "Ascending"|"Descending" sortOrder = "Ascending";
    # Only list insights containing discoveries from process intelligence with this canvas id. This parameter can be repeated
    string processIntelligenceCanvasId?;
    # Initiative property to sort by
    "dateCreated"|"dateUpdated"|"name"|"impactScore"|"effortScore"|"priorityScore" sortBy = "dateCreated";
    # Only list insights which contain this tag. This parameter can be repeated
    @constraint:String {pattern: re `[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}`}
    string tag?;
    # Only list insights which are assigned to this user. This parameter can be repeated
    @constraint:String {pattern: re `[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}`}
    string assignee?;
    # Only list insights containing discoveries with this SRI. This parameter can be repeated
    @constraint:String {pattern: re `[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}`}
    string discoveryReferenceSRI?;
    # Only list insights with this status. This parameter can be repeated
    "OPEN"|"IN_PROGRESS"|"RESOLVED" status?;
};

public type CasesCreatedResourceAttribute int?;

public type DiagramDraftResponse record {
    string id?;
};

public type CasesResourceSchema record {
    *CasesResourceReference;
    *CasesResourceAttributes;
    CasesResourceAttributesAttributes attributes;
    record {} relationships?;
    record {} links?;
};

public type DictionaryCategoryRequest record {
    # A HEX color to display with the category, for example `#800000` (dark red)
    string color;
    # If set to `true`, the category will be invisible to all users
    boolean hidden?;
    # If set to `true`, the category may only be accessible to users who own a specific privilege
    boolean restricted?;
    # The category's name
    string name;
    # The category's parent category. Leave the parameter unset to create the category on the top-most level
    string parentCategory;
    # The order the category will take among categories within the same context
    int 'order;
};

public type ExpirationDate record {
    @constraint:String {pattern: re `[0-9]{4}/[0-9]{2}/[0-9]{2}`}
    string reApprovalDate?;
};

public type TasksCompletedResourceAttribute int?;

public type DictionaryEntryRequest record {
    # Add a single attachment as an object. For multiple attachments, add them as an array of objects:
    # ```
    #   [
    #     {"url":"http://www.example.com", "label":"Example"}
    #   ]
    # ```
    Spmv1glossaryAttachments[] attachments?;
    # A JSON object containing ID-to-value mappings of custom  attributes, for example:
    # ```
    #   {
    #     "meta-my-single-line-text": "one",
    #     "meta-my-multi-line-text": "two\nthree\nfour",
    #     "meta-my-dictionary-link": "/glossary/3aabd26a654c4123a71c597210810000",
    #     "meta-my-date": "2018-12-24T16:46:00.000Z",
    #     "meta-my-number": "42",
    #     "meta-my-drop-down": "ci1545668214217710650210",
    #     "meta-my-url": {
    #       "label": "Example",
    #       "url": "http://www.example.com/"
    #     },
    #     "meta-my-boolean": true
    #   }
    # ```
    record {} metaDataValues?;
    # A description of the entry
    string description?;
    # The entry's title
    string title;
    # The desired dictionary category's ID
    string category;
};

public type Tag record {
    OffsetDateTime dateCreated;
    UUID id;
    @constraint:String {pattern: re `\S`}
    string label;
    OffsetDateTime dateUpdated;
};

# Represents the Queries record for the operation: getCaseCreator
public type GetCaseCreatorQueries record {
    # users fields to include (csv)
    string fields = "id,name,email";
};

# Represents the Queries record for the operation: listCaseVariableCaseRefs
public type ListCaseVariableCaseRefsQueries record {
    # cases relationships to include (csv)
    string include = "creator,tasks,variables";
    # cases field to include
    string 'field = "id,creator";
};

# Represents the Queries record for the operation: getGroup
public type GetGroupQueries record {
    # groups relationships to include (csv)
    string include = "users";
    # groups fields to include (csv)
    string fields = "id,name,users";
};

# Represents the Queries record for the operation: listInitiatives
public type ListInitiativesQueries record {
    # Full-text search query for initiative name and description. Minimum 3 characters required; shorter queries are ignored
    string search?;
    # Page number (1-based, the first page has number 1)
    @constraint:Int {minValue: 1}
    int:Signed32 pageNumber = 1;
    # Only list initiatives that contain this substring. This parameter can be repeated
    string nameContains?;
    # Only list initiatives containing this value driver. This parameter can be repeated
    ValueDriver valueDriver?;
    # Only list initiatives which were created by this user. This parameter can be repeated
    UUID createdBy?;
    # Only list initiatives where the user has the specified access role. This parameter can be repeated
    Role authorizationRole?;
    # Order to sort the initiatives by
    "Ascending"|"Descending" sortOrder = "Ascending";
    # Only list initiatives which this user is a member. This parameter can be repeated
    UUID hasMember?;
    # Number of entries per page
    @constraint:Int {minValue: 1, maxValue: 100}
    int:Signed32 pageSize = 10;
    # Initiative property to sort by
    "dateCreated"|"dateUpdated"|"name"|"startDate"|"endDate"|"lastActivity"|"numberOfInsights" sortBy = "dateCreated";
    # Only list initiatives with this status. This parameter can be repeated
    InitiativeStatus status?;
};

public type IncomingInsight record {
    string name;
    @constraint:Array {maxLength: 100}
    InsightsValueDriver[] valueDrivers;
    float priorityScore;
    @constraint:Array {maxLength: 100, minLength: 1}
    IncomingAuthorization[] authorizations;
    string description?;
    @constraint:Array {maxLength: 100}
    IncomingInsightInitiativesItemsString[] initiatives?;
    @constraint:Array {maxLength: 1}
    IncomingInsightAssigneesItemsString[] assignees;
    float effortScore;
    float impactScore;
    InsightStatus status;
};

# Represents the Headers record for the operation: getDictionaryEntryInfo
public type GetDictionaryEntryInfoHeaders record {
};

public type SyntaxCheckResponse record {
    string rel?;
    string href?;
    SyntaxCheckRepresentation[] rep?;
};

public type FilesSizeResourceAttribute int:Signed32;

# The JSON:API resource ID
public type GroupsIdResourceAttribute record {
    # The date
    string date?;
    # The timestamp (epoch seconds)
    int:Signed32 timestamp?;
};

public type CaseVariablesResourceAttributesAttributes record {
    CaseVariablesValuesResourceAttribute? values?;
    CaseVariablesNameResourceAttribute? name?;
    CaseVariablesDefaultValuesResourceAttribute? defaultValues?;
    CaseVariablesDescriptionResourceAttribute? description?;
    CaseVariablesVariableIdResourceAttribute? variableId?;
    CaseVariablesCaseResourceAttribute case?;
};

# Represents the Headers record for the operation: createDictionaryEntry
public type CreateDictionaryEntryHeaders record {
};

# The data required to publish or unpublish an item; only models and files can be published
public type PublishData record {
    # The mode of the item
    "publish"|"unpublish" mode;
    # The associated models
    ObjectReference[] models;
};

public type StencilsetBinding record {
    string namespace?;
    string stencil?;
    int 'order?;
};

# This object can contain dynamic localized 'name' variants with the locale as a suffix of the attribute, e.g. name_fr_fr, name_en_us, name_de_de, etc
public type RenameDirectoryData record {
    # The name of the item
    string name;
    # A description of the item
    string description;
};

public type ModelRequest record {
    @jsondata:Name {value: "json_xml"}
    string jsonXml?;
};

# Represents the Headers record for the operation: listGroupUserRefs
public type ListGroupUserRefsHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

public type UploadSchemaAndDataResponseDto record {
    string executionId;
};

public type Pagination record {
    # The next page of data
    string? next?;
    # The last page of data
    string? last?;
    # The previous page of data
    string? prev?;
    # The first page of data
    string? first?;
};

# Represents the Headers record for the operation: listCases
public type ListCasesHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

# An OData service document.
# Details can be found in the
# [ OData JSON specification](https://docs.oasis-open.org/odata/odata-json-format/v4.0/odata-json-format-v4.0.html#_Toc453766639)
# Can be serialized into JSON
public type ServiceDocument record {
    # The OData context URL for the response
    @jsondata:Name {value: "@odata.context"}
    string atOdataContext;
    # The value of the item
    ServiceDocumentEntity[] value;
};

public type CaseVariablesVariableIdResourceAttribute string?;

@constraint:String {pattern: re `[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}`}
public type UUID string;

public type InsightStatus "OPEN"|"IN_PROGRESS"|"RESOLVED";

# Represents the Headers record for the operation: listFiles
public type ListFilesHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

public type FilesResourceResponseSchema record {
    *Success;
    FilesResourceSchema data;
};

public type MetaResponseItem record {
    string rel?;
    string href?;
    MetaResponseItemRep rep?;
};

# Represents the Headers record for the operation: getUser
public type GetUserHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

public type SyntaxCheckRequest record {
    string 'resource?;
    string ns?;
    boolean isJson?;
    string context?;
    # JSON representation of your model as a string
    @jsondata:Name {value: "data_json"}
    string dataJson?;
};

public type SuccessIncluded record {
    record {} attributes?;
    # The JSON:API resource ID
    string id?;
    # The JSON:API resource type
    string 'type?;
};

public type TasksResourceSchema record {
    *TasksResourceReference;
    *TasksResourceAttributes;
    TasksResourceAttributesAttributes attributes;
    record {} relationships?;
    record {} links?;
};

public type CaseVariablesDefaultValuesResourceAttribute record {}[]?;

public type CaseVariablesDescriptionResourceAttribute string?;

public type Objective record {
    # Date and time when the objective was created
    OffsetDateTime dateCreated;
    # Name of the objective
    string name;
    # Detailed description of the objective
    string description?;
    # Additional objective attributes as raw JSON
    anydata[] attributes;
    # Unique string identifier (sId) of the objective matching ^([A-Z][a-z]+)+_.+$
    @constraint:String {pattern: re `^([A-Z][a-z]+)+_.+$`}
    string sId;
    # Date and time when the objective was last updated
    OffsetDateTime dateUpdated;
};

public type CaseVariablesNameResourceAttribute string?;

# This object can contain dynamic localized 'name' variants with the locale as a suffix of the attribute, e.g. name_fr_fr, name_en_us, name_de_de, etc
public type DirectoryInfo record {
    # The identifier of the parent item
    ObjectReference parent?;
    # A regular expression describing the allowed MIME types
    string allowedMimeTypeRegex?;
    # The name of the parent item
    string parentName?;
    # Whether the item has been deleted
    boolean deleted?;
    # Whether the item is visible
    boolean visible?;
    # The time of creation. Dates are expressed according to ISO 8601,  with a space as separator and with timezone,  example: "2024-02-26 14:21:35 +0000"
    @constraint:String {pattern: re `^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} \+\d{4}$`}
    string created?;
    # The name of the item
    string name;
    # A description of the item
    string description?;
};

public type ProcessIntelligenceContext record {
    @constraint:String {maxLength: 40}
    string canvasId?;
    @constraint:String {maxLength: 40}
    string processId?;
    @constraint:String {maxLength: 40}
    string widgetId?;
    ProcessIntelligenceCanvasType canvasType?;
};

public type CasesResourceResponseSchema record {
    *Success;
    CasesResourceSchema data;
};

public type TasksResourceReferencesResponseSchema record {
    TasksResourceReference[] data?;
};

public type ExecutionStatusDto record {
    string displayStatus;
    string message;
    "REQUEST_VALIDATING"|"REQUEST_VALIDATED"|"REQUEST_VALIDATION_FAILED"|"FILE_CONVERTING"|"FILE_CONVERTED"|"FILE_CONVERSION_FAILED"|"FILE_UPLOADING"|"FILE_UPLOADED"|"FILE_UPLOAD_FAILED"|"INTERNAL_SYNCHRONISING"|"INTERNAL_SYNCHRONISING_FAILED"|"COMPLETED" status;
};

public type TasksCreatedResourceAttribute int?;

# Represents the Headers record for the operation: authenticate
public type AuthenticateHeaders record {
    # Required request body format
    @http:Header {name: "Content-Type"}
    string contentType?;
};

public type CaseVariablesResourceReferencesResponseSchema record {
    CaseVariablesResourceReference[] data?;
};

public type IncomingAuthorization record {
    Role role;
    UUID targetId;
    AuthorizationType targetType;
};

public type GroupsResourceAttributes record {
    GroupsResourceAttributesAttributes attributes?;
};

# Represents the Queries record for the operation: getCaseVariable
public type GetCaseVariableQueries record {
    # case-variables relationship to include
    string include = "case";
};

# Represents the Queries record for the operation: listGroupUsers
public type ListGroupUsersQueries record {
    # users fields to include (csv)
    string fields = "id,name,email";
};

public type DiscoveryReference record {
    BenchmarkingAnalyticsContext benchmarkingAnalyticsContext?;
    OffsetDateTime dateCreated;
    OffsetDateTime endDate?;
    ProcessIntelligenceContext processIntelligenceContext?;
    ProcessInsightsContext processInsightsContext?;
    UUID id;
    @constraint:String {pattern: re `\S`}
    string sri;
    record {|string...;|} additionalContext?;
    string url?;
    OffsetDateTime startDate?;
    OffsetDateTime dateUpdated;
};

# Represents the Queries record for the operation: getBpmnXml
public type GetBpmnXmlQueries record {
    # Whether to include linked subprocesses
    boolean exportSubprocesses?;
    # Which tenant content language to use as the primary language of the exported XML
    string language?;
};

public type InitiativeStatus "TODO"|"PLANNING"|"IN_PROGRESS"|"AT_RISK"|"COMPLETED"|"ARCHIVED";

# Represents the Queries record for the operation: listFiles
public type ListFilesQueries record {
    # Max number of items
    @http:Query {name: "page[limit]"}
    int pageLimit = 100;
    # Page offset
    @http:Query {name: "page[offset]"}
    int pageOffset = 0;
    # Filter by id (csv)
    @http:Query {name: "filter[id]"}
    string filterId?;
};

public type FilesResourceAttributes record {
    FilesResourceAttributesAttributes attributes?;
};

# Represents the Queries record for the operation: listInsights
public type ListInsightsQueries record {
    # Page number (1-based, the first page has number 1)
    @constraint:Int {minValue: 1}
    int:Signed32 pageNumber = 1;
    # Only list insights that contain this substring. This parameter can be repeated
    string nameContains?;
    # Only list insights containing discoveries from process intelligence with this canvas type. This parameter can be repeated
    "INVESTIGATION"|"DASHBOARD" processIntelligenceCanvasType?;
    # Only list insights containing this value driver. This parameter can be repeated
    "IT_CAPACITY_PLANNING"|"IMPROVE_DEMAND_FORECAST_ACCURACY"|"IMPROVE_ON_TIME_DELIVERY"|"IMPROVE_FTE_PRODUCTIVITY"|"IMPROVE_USER_COMPLIANCE"|"INCREASE_CASH_FORECAST_ACCURACY"|"INCREASE_DAYS_PAYABLES"|"INCREASE_EFFECTIVENESS_MARKETING"|"OPERATIONAL_EXCELLENCE"|"REDUCE_HR_MANUAL_TRANSACTION"|"REDUCE_ASSET_COST"|"REDUCE_CUSTOMER_CHURN"|"REDUCE_DATA_MANAGEMENT_COST"|"REDUCE_DAYS_IN_INVENTORY"|"REDUCE_DAYS_SALES"|"REDUCE_DAYS_CLOSE_ANNUAL_BOOKS"|"REDUCE_FINANCE_COST"|"REDUCE_MANUFACTURING_CYCLE_TIME"|"REDUCE_READING_TO_INVOICE_TIME"|"REDUCE_NON_COMPLIANT_SERVICES"|"REDUCE_SUPPLY_CHAIN_PLANNING_COST"|"REDUCE_REVENUE_LOSS"|"REDUCE_SALES_COSTS"|"REDUCE_SERVICE_SUPPORT_COST"|"REDUCE_TIME_TO_FILL"|"REDUCE_TIME_TO_MARKET"|"REDUCE_LOGISTICS_COST"|"REDUCE_MANUFACTURING_COSTS"|"REDUCE_UNPLANNED_DOWNTIME"|"REDUCE_UNCOLLECTIBLE_ACCOUNTS" valueDriver?;
    # Only list insights containing discoveries with this domain application. This parameter can be repeated
    "PROCESS_MANAGER"|"PROCESS_INTELLIGENCE"|"PROCESS_INSIGHTS"|"BENCHMARKING_ANALYTICS"|"JOURNEY_MODELER"|"SUITE_CAPABILITIES"|"PROCESS_GOVERNANCE" discoveryReferenceApplication?;
    # Only list insights containing discoveries from process insights with this process flow id. This parameter can be repeated
    string processInsightsProcessFlowId?;
    # Number of entries per page
    @constraint:Int {minValue: 1}
    int:Signed32 pageSize = 10;
    # Only list insights containing discoveries from process intelligence with this widget id. This parameter can be repeated
    string processIntelligenceWidgetId?;
    # Only list insights containing discoveries from process intelligence with this process id. This parameter can be repeated
    string processIntelligenceProcessId?;
    # Only list insights which were created by this user. This parameter can be repeated
    @constraint:String {pattern: re `[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}`}
    string createdBy?;
    # Only list insights containing discoveries from process insights with this system id. This parameter can be repeated
    @constraint:String {pattern: re `[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}`}
    string processInsightsSystemId?;
    # Order to sort the initiatives by
    "Ascending"|"Descending" sortOrder = "Ascending";
    # Only list insights containing discoveries from process intelligence with this canvas id. This parameter can be repeated
    string processIntelligenceCanvasId?;
    # Initiative property to sort by
    "dateCreated"|"dateUpdated"|"name"|"impactScore"|"effortScore"|"priorityScore" sortBy = "dateCreated";
    # Only list insights which contain this tag. This parameter can be repeated
    @constraint:String {pattern: re `[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}`}
    string tag?;
    # Only list insights which are assigned to this user. This parameter can be repeated
    @constraint:String {pattern: re `[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}`}
    string assignee?;
    # Only list insights containing discoveries with this SRI. This parameter can be repeated
    @constraint:String {pattern: re `[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}`}
    string discoveryReferenceSRI?;
    # Only list insights with this status. This parameter can be repeated
    "OPEN"|"IN_PROGRESS"|"RESOLVED" status?;
};

public type ProcessInsightsContext record {
    UUID systemId?;
    @constraint:String {maxLength: 32}
    string processFlowId?;
    @constraint:String {pattern: re `^[a-zA-Z0-9_\-]{0,10}$`}
    string contextInfo?;
    @constraint:String {pattern: re `^[a-zA-Z0-9_\-]{0,10}$`}
    string phaseId?;
};

# The JSON:API resource ID
public type TasksIdResourceAttribute record {
    # The date
    string date?;
    # The timestamp (epoch seconds)
    int:Signed32 timestamp?;
};

public type CasesResourceAttributesAttributes record {
    CasesCreatorResourceAttribute creator?;
    CasesVariablesResourceAttribute? variables?;
    CasesMilestoneResourceAttribute? milestone?;
    CasesProcessIdResourceAttribute? processId?;
    CasesCaseNumberResourceAttribute? caseNumber?;
    CasesCreatedResourceAttribute? created?;
    CasesNameResourceAttribute? name?;
    CasesClosedResourceAttribute? closed?;
    CasesPriorityResourceAttribute? priority?;
    CasesTasksResourceAttribute? tasks?;
    CasesApplicationLinkResourceAttribute? applicationLink?;
};

public type GroupsResourcesResponseSchema record {
    *Success;
    GroupsResourceSchema[] data;
};

# Represents the Headers record for the operation: updateDictionaryEntry
public type UpdateDictionaryEntryHeaders record {
};

public type TasksUpdatedResourceAttribute int?;

# Represents the Headers record for the operation: getFile
public type GetFileHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

# Represents the Queries record for the operation: createDiagramDraft
public type CreateDiagramDraftQueries record {
    # The notation URI value for the stencil set
    string stencilset;
};

public type MoveDirectoryRequest record {
    ObjectReference parent?;
};

public type TasksResourceAttributes record {
    TasksResourceAttributesAttributes attributes?;
};

public type AutomaticMeasurement record {
    "NPS"|"CSAT"|"CES" 'type;
    CesMeasurement|CsatMeasurement|NPSMeasurement value;
};

public type AssetType "METRICS"|"PROCESS_MODEL"|"JIRA"|"LEANIX"|"SAP_CLOUD_ALM"|"TASK"|"OBJECTIVE"|"KEY_RESULT"|"DASHBOARD"|"INVESTIGATION"|"DOCUMENT"|"FILE"|"IMPROVEMENT_OPPORTUNITY"|"CORRECTION_RECOMMENDATION"|"BLOCKER"|"PROCESS_FLOW"|"OTHER";

public type UsersResourceAttributesAttributes record {
    UsersNameResourceAttribute? name?;
    UsersEmailResourceAttribute? email?;
};

public type CasesVariablesResourceAttribute CaseVariablesResourceReference[]?;

# Represents the Headers record for the operation: getTaskCaseRef
public type GetTaskCaseRefHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

public type CaseVariablesResourceSchema record {
    *CaseVariablesResourceReference;
    *CaseVariablesResourceAttributes;
    CaseVariablesResourceAttributesAttributes attributes;
    record {} relationships?;
    record {} links?;
};

# Link members related to the primary data
public type Links record {
    *Pagination;
};

public type ModelInfoResponse record {
    string parent?;
    record {} formats?;
    @jsondata:Name {value: "granted_revision_user"}
    string grantedRevisionUser?;
    boolean isLicensedStencilSet?;
    @jsondata:Name {value: "granted_revision_user_name"}
    string grantedRevisionUserName?;
    string description?;
    string 'type?;
    @jsondata:Name {value: "sri_revision"}
    string sriRevision?;
    @jsondata:Name {value: "sri_path"}
    string sriPath?;
    int numberOfNewComments?;
    boolean isDeployed?;
    @jsondata:Name {value: "granted_revision"}
    string grantedRevision?;
    int rev?;
    string created?;
    string author?;
    @jsondata:Name {value: "granted_revision_date"}
    string grantedRevisionDate?;
    string sri?;
    string authorCompany?;
    string revision?;
    string parentName?;
    boolean deleted?;
    string authorName?;
    string name?;
    string namespace?;
    string comment?;
    string updated?;
    V1modelmodelIdinfoStatus status?;
};

public type FilesResourceAttributesAttributes record {
    FilesSizeResourceAttribute size?;
    FilesNameResourceAttribute? name?;
};

# Represents the Headers record for the operation: createDictionaryCategory
public type CreateDictionaryCategoryHeaders record {
    # application/x-www-form-urlencoded
    @http:Header {name: "Content-Type"}
    string contentType = "application/x-www-form-urlencoded";
};
