// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/constraint;
import ballerina/data.jsondata;
import ballerina/http;

# Non-standard meta-information that can not be represented as an attribute or relationship
public type Meta record {
};

# Represents the Queries record for the operation: getTaskCase
public type GetTaskCaseQueries record {
    # cases field to include
    string 'field = "id,creator";
};

# Represents the Queries record for the operation: createModel
public type CreateModelQueries record {
    # A timestamp or unique string used to prevent caching issues
    @http:Query {name: "_dc"}
    string dc?;
};

# The JSON:API resource ID
public type CasesIdResourceAttribute record {
    # The date
    string date?;
    # The timestamp (epoch seconds)
    int:Signed32 timestamp?;
};

# Represents the Headers record for the operation: updateDictionaryCategory
public type UpdateDictionaryCategoryHeaders record {
    # application/x-www-form-urlencoded
    @http:Header {name: "Content-Type"}
    string contentType = "application/x-www-form-urlencoded";
};

# Represents the cases creator resource attribute.
public type CasesCreatorResourceAttribute UsersResourceReference;

# Represents the files resource references response schema.
public type FilesResourceReferencesResponseSchema record {
    # The data
    FilesResourceReference[] data?;
};

# A JSON:API document with a single resource
public type Success record {
    # The JSON:API version information
    JsonApi jsonapi?;
    # Non-standard meta-information that can not be represented as an attribute or relationship
    Meta meta?;
    # Link members related to the primary data
    Links links?;
    # Included resources
    SuccessIncluded[] included?;
};

# Represents the users resource reference.
public type UsersResourceReference record {
    # The JSON:API resource ID
    UsersIdResourceAttribute id;
    # The JSON:API resource type (Users)
    "Users" 'type;
};

# Represents the groups users resource attribute.
public type GroupsUsersResourceAttribute UsersResourceReference[]?;

# Represents the token request.
public type TokenRequest record {
    # Authenticating user's password
    string password;
    # Authenticating user's email address
    string name;
    # Must be set to retrieve the JWT
    boolean tokenonly;
    # Unique identifier of the target workspace. Only necessary if the authenticating user is a member of multiple workspaces
    string tenant?;
};

# Represents the dictionary entry update request.
public type DictionaryEntryUpdateRequest record {
    # The attachments
    Spmv1glossaryAttachments[] attachments?;
    # The meta data values
    record {} metaDataValues?;
    # A description of the entry
    string description?;
    # Force the update to occur. This parameter must be set to `true` if the item being updated has a non-unique name
    boolean force?;
    # The entry's title
    string title;
    # The desired dictionary category's ID
    string category;
};

# Represents the Headers record for the operation: listGroupUsers
public type ListGroupUsersHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

# Represents the value driver.
public type ValueDriver "IT_CAPACITY_PLANNING"|"IMPROVE_DEMAND_FORECAST_ACCURACY"|"IMPROVE_ON_TIME_DELIVERY"|"IMPROVE_FTE_PRODUCTIVITY"|"IMPROVE_USER_COMPLIANCE"|"INCREASE_CASH_FORECAST_ACCURACY"|"INCREASE_DAYS_PAYABLES"|"INCREASE_EFFECTIVENESS_MARKETING"|"OPERATIONAL_EXCELLENCE"|"REDUCE_HR_MANUAL_TRANSACTION"|"REDUCE_ASSET_COST"|"REDUCE_CUSTOMER_CHURN"|"REDUCE_DATA_MANAGEMENT_COST"|"REDUCE_DAYS_IN_INVENTORY"|"REDUCE_DAYS_SALES"|"REDUCE_DAYS_CLOSE_ANNUAL_BOOKS"|"REDUCE_FINANCE_COST"|"REDUCE_MANUFACTURING_CYCLE_TIME"|"REDUCE_READING_TO_INVOICE_TIME"|"REDUCE_NON_COMPLIANT_SERVICES"|"REDUCE_SUPPLY_CHAIN_PLANNING_COST"|"REDUCE_REVENUE_LOSS"|"REDUCE_SALES_COSTS"|"REDUCE_SERVICE_SUPPORT_COST"|"REDUCE_TIME_TO_FILL"|"REDUCE_TIME_TO_MARKET"|"REDUCE_LOGISTICS_COST"|"REDUCE_MANUFACTURING_COSTS"|"REDUCE_UNPLANNED_DOWNTIME"|"REDUCE_UNCOLLECTIBLE_ACCOUNTS"|"REDUCE_EMISSIONS_COST"|"REDUCE_WASTE_GENERATION_COST"|"REDUCE_COMPLIANCE_AND_RISK_MANAGEMENT_COST"|"INCREASE_BUSINESS_PROCESS_HARMONIZATION"|"INCREASE_ADHERENCE_TO_STANDARDIZED_SAP_BUSINESS_PROCESSES";

// >>> MANUALLY MAINTAINED - NOT REGENERATED. `Credentials` and `ConnectionConfig` are hand-written
// overrides (see docs/spec/sanitations.md item 2); `bal openapi` does not produce them. Reconcile
// this block against any regenerated output before committing a regeneration. <<<
# SAP Signavio account credentials. The connector uses these to transparently
# obtain both the API gateway access token (`POST /auth/v1/token`) and the
# Process Manager workspace session (`POST /p/login`) - no separate login
# step is required from the caller.
public type Credentials record {|
    # The account's user name (typically an email address)
    string username;
    # The account's password
    string password;
    # Unique identifier of the target workspace. Only necessary if the authenticating user is a member of multiple workspaces
    string tenant?;
    # A SAP Signavio OData API access token. Only required to call `getServiceDocument`, `getMetadata`, or `queryEntitySet` -
    # the SIGNAL Engine OData API authenticates with a dedicated access token rather than the account password, and that
    # token can only be generated from the SAP Signavio UI, so it cannot be derived from `username`/`password` automatically
    string odataAccessToken?;
|};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # SAP Signavio account credentials
    Credentials auth;
    # The SAP Signavio region that hosts the workspace. Determines both the API gateway hostname
    # (`api.<region>.signavio.cloud.sap`) and the Process Manager workspace hostname (`app-<region>.signavio.com`)
    string region = "eu";
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional,
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};
// <<< END MANUALLY MAINTAINED block (Credentials / ConnectionConfig) >>>

# Represents the users name resource attribute.
public type UsersNameResourceAttribute string?;

# Represents the status.
public type Status record {
    # The deleted
    boolean deleted?;
    # The approve
    boolean approve?;
    # The publish
    boolean publish?;
    # The unique identifier
    string id?;
};

# Represents the Headers record for the operation: listCaseTasks
public type ListCaseTasksHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

# Represents the initiative type.
public type InitiativeType "STANDARD"|"PINT_MANAGED";

# Represents the bpmn import result.
public type BpmnImportResult record {
    # The number of updated models
    int numUpdated?;
    # The IDs of the created models
    string[] createdIds?;
    # The warnings
    Messages warnings?;
    # The ID of the main model
    string mainModelId?;
    # The number of created models
    int numCreated?;
    # The IDs of the updated models
    string[] updatedIds?;
    # The list of errors
    Messages errors?;
};

# Represents the case variables resource response schema.
public type CaseVariablesResourceResponseSchema record {
    *Success;
    # The data
    CaseVariablesResourceSchema data;
};

# Represents the ces measurement.
public type CesMeasurement record {
    *Measurement;
    # The num difficult
    int:Signed32 numDifficult;
    # The num very difficult
    int:Signed32 numVeryDifficult?;
    # The num bit easy
    int:Signed32 numBitEasy?;
    # The scale
    "ONE_TO_THREE"|"ONE_TO_FIVE"|"ONE_TO_SEVEN" scale;
    # The num very easy
    int:Signed32 numVeryEasy?;
    # The num neutral
    int:Signed32 numNeutral;
    # The num easy
    int:Signed32 numEasy;
    # The num bit difficult
    int:Signed32 numBitDifficult?;
};

# Represents the Queries record for the operation: listCaseTasks
public type ListCaseTasksQueries record {
    # tasks field to include
    string fields = "id";
    # Filter by id (csv)
    @http:Query {name: "filter[id]"}
    string filterId?;
};

# Represents the Queries record for the operation: listModelRevisions
public type ListModelRevisionsQueries record {
    # The offset of the first revision to be returned
    int:Signed32 offset?;
    # A search query to filter the revisions
    string query?;
    # The maximum number of revisions to be returned
    int:Signed32 'limit?;
};

# Represents the directory id.
@constraint:String {pattern: re `^[0-9a-fA-F]{32}$`}
public type DirectoryId string;

# Represents the incoming insight assignees items string.
@constraint:String {pattern: re `[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}`}
public type IncomingInsightAssigneesItemsString string;

# Represents the cases resources response schema.
public type CasesResourcesResponseSchema record {
    *Success;
    # The data
    CasesResourceSchema[] data;
};

# Represents the model resource response.
public type ModelResourceResponse record {
    # The relation type
    string rel?;
    # The hypermedia link
    string href?;
    # The representation payload
    ModelRepresentation rep?;
};

# Represents the tasks due resource attribute.
public type TasksDueResourceAttribute int?;

# Represents the Queries record for the operation: getCase
public type GetCaseQueries record {
    # cases relationships to include (csv)
    string include = "creator,tasks,variables";
    # cases field to include
    string 'field = "id,creator";
};

# Represents the authorization type.
public type AuthorizationType "USER"|"GROUP";

# Represents the Headers record for the operation: getDictionaryEntry
public type GetDictionaryEntryHeaders record {
};

# Represents the users resource response schema.
public type UsersResourceResponseSchema record {
    *Success;
    # The data
    UsersResourceSchema data;
};

# Represents the insights value driver.
public type InsightsValueDriver "IT_CAPACITY_PLANNING"|"IMPROVE_DEMAND_FORECAST_ACCURACY"|"IMPROVE_ON_TIME_DELIVERY"|"IMPROVE_FTE_PRODUCTIVITY"|"IMPROVE_USER_COMPLIANCE"|"INCREASE_CASH_FORECAST_ACCURACY"|"INCREASE_DAYS_PAYABLES"|"INCREASE_EFFECTIVENESS_MARKETING"|"OPERATIONAL_EXCELLENCE"|"REDUCE_HR_MANUAL_TRANSACTION"|"REDUCE_ASSET_COST"|"REDUCE_CUSTOMER_CHURN"|"REDUCE_DATA_MANAGEMENT_COST"|"REDUCE_DAYS_IN_INVENTORY"|"REDUCE_DAYS_SALES"|"REDUCE_DAYS_CLOSE_ANNUAL_BOOKS"|"REDUCE_FINANCE_COST"|"REDUCE_MANUFACTURING_CYCLE_TIME"|"REDUCE_READING_TO_INVOICE_TIME"|"REDUCE_NON_COMPLIANT_SERVICES"|"REDUCE_SUPPLY_CHAIN_PLANNING_COST"|"REDUCE_REVENUE_LOSS"|"REDUCE_SALES_COSTS"|"REDUCE_SERVICE_SUPPORT_COST"|"REDUCE_TIME_TO_FILL"|"REDUCE_TIME_TO_MARKET"|"REDUCE_LOGISTICS_COST"|"REDUCE_MANUFACTURING_COSTS"|"REDUCE_UNPLANNED_DOWNTIME"|"REDUCE_UNCOLLECTIBLE_ACCOUNTS";

# Represents the cases resource attributes.
public type CasesResourceAttributes record {
    # The attributes
    CasesResourceAttributesAttributes attributes?;
};

# Represents the model info request.
public type ModelInfoRequest record {
    # The parent
    string parent?;
    # The formats
    record {} formats?;
    # The granted revision user
    @jsondata:Name {value: "granted_revision_user"}
    string grantedRevisionUser?;
    # The created
    string created?;
    # The author
    string author?;
    # The is licensed stencil set
    boolean isLicensedStencilSet?;
    # The granted revision user name
    @jsondata:Name {value: "granted_revision_user_name"}
    string grantedRevisionUserName?;
    # The description
    string description?;
    # The type
    string 'type?;
    # The author company
    string authorCompany?;
    # The revision
    string revision?;
    # The parent name
    string parentName?;
    # The author name
    string authorName?;
    # The is deployed
    boolean isDeployed?;
    # The name
    string name?;
    # The updated
    string updated?;
    # The status
    V1modelmodelIdinfoStatus status?;
};

# Represents the Headers record for the operation: getGroup
public type GetGroupHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

# Represents the model response.
public type ModelResponse record {
    # The relation type
    string rel?;
    # The hypermedia link
    string href?;
    # The representation payload
    Rep rep?;
};

# Represents the diagram json child shape.
public type DiagramJsonChildShape record {
    # The resource id
    string resourceId?;
    # The properties
    record {} properties?;
};

# Represents the NPS measurement.
public type NPSMeasurement record {
    *Measurement;
    # The detractors
    int:Signed32 detractors;
    # The promoters
    int:Signed32 promoters;
    # The passives
    int:Signed32 passives;
};

# Represents the object reference.
@constraint:String {pattern: re `^/[^/]+/[0-9a-fA-F]{32}$`}
public type ObjectReference string;

# Represents the groups resource reference.
public type GroupsResourceReference record {
    # The JSON:API resource ID
    GroupsIdResourceAttribute id;
    # The JSON:API resource type (Groups)
    "Groups" 'type;
};

# The JSON:API resource ID
public type FilesIdResourceAttribute record {
    # The date
    string date?;
    # The timestamp (epoch seconds)
    int:Signed32 timestamp?;
};

# Represents the Queries record for the operation: listCases
public type ListCasesQueries record {
    # Max number of items
    @http:Query {name: "page[limit]"}
    int pageLimit = 100;
    # cases relationships to include (csv)
    string include = "creator,tasks,variables";
    # Page offset
    @http:Query {name: "page[offset]"}
    int pageOffset = 0;
    # Filter by processId
    @http:Query {name: "filter[processId]"}
    string filterProcessId?;
    # cases field to include
    string 'field = "id,creator";
};

# Represents the Headers record for the operation: getDictionaryCategory
public type GetDictionaryCategoryHeaders record {
};

# Represents the cases application link resource attribute.
public type CasesApplicationLinkResourceAttribute string?;

# Represents the Headers record for the operation: listTasks
public type ListTasksHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

# Represents the delete directory response.
public type DeleteDirectoryResponse record {
    # The success
    boolean success?;
};

# Represents the objectives response.
public type ObjectivesResponse record {
    # The count
    int count?;
    # The value
    Objective[] value?;
};

# Represents the files resources response schema.
public type FilesResourcesResponseSchema record {
    *Success;
    # The data
    FilesResourceSchema[] data;
};

# Represents the tasks resources response schema.
public type TasksResourcesResponseSchema record {
    *Success;
    # The data
    TasksResourceSchema[] data;
};

# Represents the ingestion data request.
public type IngestionDataRequest record {
    # A Schema is represented in JSON following Apache Avro Specification of type record to define the table structure
    string schema;
    # Comma separated list of primary keys, for example primaryKeys=key1,key2,key3 (values must exist in the provided Schema)
    @constraint:Array {minLength: 1}
    string[] primaryKeys;
    # A character separating the data in the files. Default value is ","
    string delimiter = ",";
    # The data to be pushed. Supported formats are CSV and TSV
    @constraint:Array {minLength: 1}
    record {byte[] fileContent; string fileName;}[] files;
};

# Represents the incoming insight initiatives items string.
@constraint:String {pattern: re `[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}`}
public type IncomingInsightInitiativesItemsString string;

# Represents the csat measurement.
public type CsatMeasurement record {
    *Measurement;
    # The num dissatisfied
    int:Signed32 numDissatisfied;
    # The num highly satisfied
    int:Signed32 numHighlySatisfied;
    # The num highly dissatisfied
    int:Signed32 numHighlyDissatisfied;
    # The num satisfied
    int:Signed32 numSatisfied;
    # The num neutral
    int:Signed32 numNeutral;
};

# Represents the Queries record for the operation: listCaseVariableCases
public type ListCaseVariableCasesQueries record {
    # cases relationships to include (csv)
    string include = "creator,tasks,variables";
    # cases field to include
    string 'field = "id,creator";
};

# Represents the groups resource response schema.
public type GroupsResourceResponseSchema record {
    *Success;
    # The data
    GroupsResourceSchema data;
};

# Represents the rep.
public type Rep record {
    # The parent
    string parent?;
    # The formats
    record {} formats?;
    # The granted revision user
    @jsondata:Name {value: "granted_revision_user"}
    string grantedRevisionUser?;
    # The is licensed stencil set
    boolean isLicensedStencilSet?;
    # The granted revision user name
    @jsondata:Name {value: "granted_revision_user_name"}
    string grantedRevisionUserName?;
    # The description
    string description?;
    # The type
    string 'type?;
    # The sri revision
    @jsondata:Name {value: "sri_revision"}
    string sriRevision?;
    # The sri path
    @jsondata:Name {value: "sri_path"}
    string sriPath?;
    # The is deployed
    boolean isDeployed?;
    # The granted revision
    @jsondata:Name {value: "granted_revision"}
    string grantedRevision?;
    # The rev
    int rev?;
    # The created
    string created?;
    # The author
    string author?;
    # The granted revision date
    @jsondata:Name {value: "granted_revision_date"}
    string grantedRevisionDate?;
    # The sri
    string sri?;
    # The author company
    string authorCompany?;
    # The revision
    string revision?;
    # The parent name
    string parentName?;
    # The deleted
    boolean deleted?;
    # The author name
    string authorName?;
    # The name
    string name?;
    # The namespace
    string namespace?;
    # The comment
    string comment?;
    # The updated
    string updated?;
    # The status
    Status status?;
};

# Represents the cases tasks resource attribute.
public type CasesTasksResourceAttribute TasksResourceReference[]?;

# Represents the Headers record for the operation: deleteDictionaryCategory
public type DeleteDictionaryCategoryHeaders record {
};

# Represents the users resource attributes.
public type UsersResourceAttributes record {
    # The attributes
    UsersResourceAttributesAttributes attributes?;
};

# Represents the Queries record for the operation: listDictionaryCategories
public type ListDictionaryCategoriesQueries record {
    # If set to `true`, hidden categories are included in the response
    boolean showHidden?;
    # If set to `true`, all categories' representations are returned  at once, without the need to send additional queries for  sub-categories
    boolean allCategories?;
    # To circumvent access restrictions as a member of the workspace's  administrators group, set this parameter to true
    boolean considerAllPrivilege?;
};

# Represents the Headers record for the operation: getCaseVariable
public type GetCaseVariableHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

# Represents the Queries record for the operation: listCaseVariables
public type ListCaseVariablesQueries record {
    # Max number of items
    @http:Query {name: "page[limit]"}
    int pageLimit = 100;
    # case-variables relationship to include
    string include = "case";
    # Page offset
    @http:Query {name: "page[offset]"}
    int pageOffset = 0;
    # Filter by id (csv)
    @http:Query {name: "filter[id]"}
    string filterId;
};

# Represents the case variables values resource attribute.
public type CaseVariablesValuesResourceAttribute record {}[]?;

# Represents the groups resource references response schema.
public type GroupsResourceReferencesResponseSchema record {
    # The data
    GroupsResourceReference[] data?;
};

# Represents the Headers record for the operation: deleteDictionaryEntry
public type DeleteDictionaryEntryHeaders record {
};

# Represents the Queries record for the operation: listTasks
public type ListTasksQueries record {
    # Max number of items
    @http:Query {name: "page[limit]"}
    int pageLimit = 100;
    # tasks relationships to include (csv)
    string include = "case";
    # Page offset
    @http:Query {name: "page[offset]"}
    int pageOffset = 0;
    # Filter by assignee
    @http:Query {name: "filter[assignee.email]"}
    string filterAssigneeEmail?;
    # Filter by case
    @http:Query {name: "filter[case.id]"}
    string filterCaseId?;
    # Filter by completed
    @http:Query {name: "filter[completed]"}
    string filterCompleted?;
    # tasks field to include
    string fields = "id";
    # Filter by id (csv)
    @http:Query {name: "filter[id]"}
    string filterId?;
};

# Represents the syntax check representation.
public type SyntaxCheckRepresentation record {
    # The should
    record {} should?;
    # The must
    record {|string[]...;|} must?;
    # The guideline id
    string guidelineId?;
};

# Represents the groups resource schema.
public type GroupsResourceSchema record {
    *GroupsResourceReference;
    *GroupsResourceAttributes;
    # The attributes
    GroupsResourceAttributesAttributes attributes;
    # The relationships
    record {} relationships?;
    # The links
    record {} links?;
};

# Represents the insight.
public type Insight record {
    # The updated by
    UserInfo updatedBy;
    # The value drivers
    @constraint:Array {maxLength: 100}
    InsightsValueDriver[] valueDrivers;
    # The authorizations
    @constraint:Array {maxLength: 100}
    Authorization[] authorizations;
    # The description
    string description?;
    # The assignees
    @constraint:Array {maxLength: 100}
    UserInfo[] assignees;
    # The sri
    string sri;
    # The date updated
    OffsetDateTime dateUpdated;
    # The tags
    Tag[] tags;
    # The date created
    OffsetDateTime dateCreated;
    # The created by
    UserInfo createdBy;
    # The discoveries
    DiscoveryReference[] discoveries;
    # The name
    string name;
    # The priority score
    float priorityScore;
    # The initiatives
    InsightInitiativesItemsString[] initiatives?;
    # The unique identifier
    UUID id;
    # The effort score
    float effortScore;
    # The impact score
    float impactScore;
    # The status
    InsightStatus status;
};

# Represents the incoming initiative.
public type IncomingInitiative record {
    # The end date
    OffsetDateTime endDate?;
    # The name
    string name;
    # The value drivers
    @constraint:Array {maxLength: 100}
    ValueDriver[] valueDrivers;
    # The authorizations
    @constraint:Array {maxLength: 100, minLength: 1}
    IncomingAuthorization[] authorizations;
    # The description
    string description?;
    # The start date
    OffsetDateTime startDate?;
    # The status
    InitiativeStatus status;
};

# Represents the bpmn import request.
public type BpmnImportRequest record {
    # The filename and content of the BPMN 2.0 XML file
    @jsondata:Name {value: "bpmn2_0file"}
    record {byte[] fileContent; string fileName;} bpmn2File;
    # The ID of the model to create a new revision for
    string modelid?;
    # The directory where the content of the BPMN 2.0 XML file should be imported into
    string directory?;
};

# Represents the cases process id resource attribute.
public type CasesProcessIdResourceAttribute record {
    # The date
    string date?;
    # The timestamp (epoch seconds)
    int:Signed32 timestamp?;
};

# Represents the tasks resource reference.
public type TasksResourceReference record {
    # The JSON:API resource ID
    TasksIdResourceAttribute id;
    # The JSON:API resource type (Tasks)
    "Tasks" 'type;
};

# Represents the users resource references response schema.
public type UsersResourceReferencesResponseSchema record {
    # The data
    UsersResourceReference[] data?;
};

# Represents the benchmarking analytics context.
public type BenchmarkingAnalyticsContext record {
    # The metric benchmark container id
    @constraint:String {maxLength: 150}
    string metricBenchmarkContainerId?;
    # The e2e process id
    @constraint:String {maxLength: 100}
    string e2eProcessId?;
};

# Represents the files resource schema.
public type FilesResourceSchema record {
    *FilesResourceReference;
    *FilesResourceAttributes;
    # The attributes
    FilesResourceAttributesAttributes attributes;
    # The relationships
    record {} relationships?;
    # The links
    record {} links?;
};

# Represents the user info user group ids items string.
@constraint:String {pattern: re `[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}`}
public type UserInfoUserGroupIdsItemsString string;

# Represents the representation.
public type Representation record {
    # The formats
    record {} formats?;
    # The attachments
    anydata[] attachments?;
    # The color
    string color?;
    # The hidden
    boolean hidden?;
    # The granted revision user
    @jsondata:Name {value: "granted_revision_user"}
    string grantedRevisionUser?;
    # The workflow sync up to date
    boolean workflowSyncUpToDate?;
    # Array of prefixed IDs of categories that have this category  as parent category
    string publishingMode?;
    # The granted revision user name
    @jsondata:Name {value: "granted_revision_user_name"}
    string grantedRevisionUserName?;
    # The linked count
    int linkedCount?;
    # The description
    string description?;
    # The language
    string language?;
    # The child categories
    string[] childCategories?;
    # The occurrence
    int occurrence?;
    # The replaced item ids
    string[] replacedItemIds?;
    # The title
    string title?;
    # The child category count
    int childCategoryCount?;
    # The type
    string 'type?;
    # The category name
    string categoryName?;
    # The head revision num
    int headRevisionNum?;
    # The linked by count
    int linkedByCount?;
    # The meta data values
    record {} metaDataValues?;
    # The is enabled for dimensions
    boolean isEnabledForDimensions?;
    # The unique identifier
    string id?;
    # The has attachments
    boolean hasAttachments?;
    # ID of the workspaces's Dictionary (not relevant for API access)
    string glossaryId?;
    # The order
    int 'order?;
    # The head revision
    string headRevision?;
    # The granted revision
    @jsondata:Name {value: "granted_revision"}
    string grantedRevision?;
    # The granted revision number
    @jsondata:Name {value: "granted_revision_number"}
    int grantedRevisionNumber?;
    # The decision input
    boolean decisionInput?;
    # The is dimension
    boolean isDimension?;
    # The author
    string author?;
    # The granted revision date
    @jsondata:Name {value: "granted_revision_date"}
    string grantedRevisionDate?;
    # The author company
    string authorCompany?;
    # The item count
    int itemCount?;
    # The is standard
    boolean isStandard?;
    # The workflow sync enabled
    boolean workflowSyncEnabled?;
    # The name
    string name?;
    # If the category corresponds to one of the six standard  categories, this field is set. For example, some reports  consider the content of these categories. The following  `oldCategories` exist:
    # 
    #   * `ORG_UNIT` - Organizational units
    #   * `DOCUMENT` - Documents
    #   * `ACTIVITY` - Activities
    #   * `STATE` - Events
    #   * `IT_SYSTEM` - IT systems
    #   * `NONE` - Everything else
    string oldCategory?;
    # The parent category
    string parentCategory?;
    # The comment
    string comment?;
    # The decision data object key
    string decisionDataObjectKey?;
    # The category
    string category?;
    # The items
    anydata[] items?;
    # The updated
    string updated?;
    # The sending interval
    string sendingInterval?;
    # The linking published models update mode
    string linkingPublishedModelsUpdateMode?;
};

# The JSON:API resource ID
public type CaseVariablesIdResourceAttribute record {
    # The case identifier
    CaseVariablesIdResourceAttributeCazeId cazeId?;
    # The unique identifier
    string id?;
};

# Represents the diagram json.
public type DiagramJson record {
    # The resource id
    string resourceId?;
    # The properties
    record {} properties?;
    # The child shapes
    DiagramJsonChildShape[] childShapes?;
};

# Represents the role.
public type Role "OWNER"|"EDITOR"|"VIEWER";

# Represents the dictionary response.
public type DictionaryResponse record {
    # The relation type
    string rel;
    # The hypermedia link
    string href;
    // Shape varies by `rel`: a `Representation`-like object for `gitem`/`cat`/`info`, an array
    // for relation-only entries like `priv`, and further nested hypermedia objects for
    // `parents` - `json` is used rather than a narrower union to accept all of these.
    # The representation payload
    json rep;
};

# Represents the users resources response schema.
public type UsersResourcesResponseSchema record {
    *Success;
    # The data
    UsersResourceSchema[] data;
};

# Represents the offset date time.
public type OffsetDateTime string;

# Represents the Headers record for the operation: getCase
public type GetCaseHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

# Represents the tasks resource attributes attributes.
public type TasksResourceAttributesAttributes record {
    # The due
    TasksDueResourceAttribute? due?;
    # The created
    TasksCreatedResourceAttribute? created?;
    # The name
    TasksNameResourceAttribute? name?;
    # The assignee
    TasksAssigneeResourceAttribute? assignee?;
    # The completed
    TasksCompletedResourceAttribute? completed?;
    # The updated
    TasksUpdatedResourceAttribute? updated?;
    # The case
    TasksCaseResourceAttribute case?;
    # The application link
    TasksApplicationLinkResourceAttribute? applicationLink?;
};

# Represents the Queries record for the operation: getTask
public type GetTaskQueries record {
    # tasks relationships to include (csv)
    string include = "case";
    # tasks field to include
    string fields = "id";
};

# Represents the cases closed resource attribute.
public type CasesClosedResourceAttribute int?;

# Represents the incoming asset.
public type IncomingAsset record {
    # The name
    string name;
    # The description
    string description?;
    # The type
    AssetType 'type;
    # The url
    string url;
};

# Represents the measurement.
public type Measurement record {
    # The score
    int:Signed32 score;
    # The time
    string time;
};

# Represents the Headers record for the operation: getTaskCase
public type GetTaskCaseHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

# Represents the Headers record for the operation: listGroups
public type ListGroupsHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

# Represents the users resource schema.
public type UsersResourceSchema record {
    *UsersResourceReference;
    *UsersResourceAttributes;
    # The attributes
    UsersResourceAttributesAttributes attributes;
    # The relationships
    record {} relationships?;
    # The links
    record {} links?;
};

# Represents the initiative summary for objective.
public type InitiativeSummaryForObjective record {
    # The updated by
    UserInfo updatedBy?;
    # The end date
    OffsetDateTime endDate?;
    # The value drivers
    @constraint:Array {maxLength: 100}
    ValueDriver[] valueDrivers;
    # The authorizations
    @constraint:Array {maxLength: 100}
    Authorization[] authorizations;
    # The description
    string description?;
    # The type
    InitiativeType 'type;
    # The sid
    @constraint:String {pattern: re `^SuiteInitiative_[0-9a-fA-F]{32}$`}
    string sid;
    # The date updated
    OffsetDateTime dateUpdated;
    # The date created
    OffsetDateTime dateCreated;
    # The created by
    UserInfo createdBy;
    # The name
    string name;
    # The last activity
    OffsetDateTime lastActivity;
    # The start date
    OffsetDateTime startDate?;
    # The status
    InitiativeStatus status;
};

# Represents the process intelligence canvas type.
public type ProcessIntelligenceCanvasType "INVESTIGATION"|"DASHBOARD";

# Represents the Queries record for the operation: listObjectives
public type ListObjectivesQueries record {
    # Page size (max 1000)
    @constraint:Int {minValue: 1, maxValue: 1000}
    int:Signed32 size = 10;
    # Zero-based page index (0 = first page)
    @constraint:Int {minValue: 0}
    int:Signed32 page = 0;
    # Include approximate total count in response when true
    @http:Query {name: "$count"}
    boolean dollarCount = false;
};

# Represents the user info.
public type UserInfo record {
    # The first name
    string firstName?;
    # The last name
    string lastName?;
    # The display name
    string displayName?;
    # The unique identifier
    UUID id;
    # The user group ids
    UserInfoUserGroupIdsItemsString[] userGroupIds;
    # The email
    string email?;
};

# Represents the tasks assignee resource attribute.
public type TasksAssigneeResourceAttribute record {
    # The name
    string name?;
    # The email
    string email?;
};

# Represents the case variables resource reference.
public type CaseVariablesResourceReference record {
    # The JSON:API resource ID
    CaseVariablesIdResourceAttribute id;
    # The JSON:API resource type (Case-variables)
    "Case-variables" 'type;
};

# Represents the case variables resources response schema.
public type CaseVariablesResourcesResponseSchema record {
    *Success;
    # The data
    CaseVariablesResourceSchema[] data;
};

# Represents the Headers record for the operation: listCaseVariables
public type ListCaseVariablesHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

# Represents the Headers record for the operation: listDictionaryCategories
public type ListDictionaryCategoriesHeaders record {
};

# Represents the cases resource references response schema.
public type CasesResourceReferencesResponseSchema record {
    # The data
    CasesResourceReference[] data?;
};

# Represents the spmv1glossary attachments.
public type Spmv1glossaryAttachments record {
    # The label
    string label?;
    # The url
    string url?;
};

# Represents the json api.
public type JsonApi record {|
    # The version
    string version?;
|};

# Represents the create directory request.
public type CreateDirectoryRequest record {
    # The parent
    ObjectReference parent?;
    # The name
    string name?;
};

# Represents the initiative.
public type Initiative record {
    # The updated by
    UserInfo updatedBy;
    # The end date
    OffsetDateTime endDate?;
    # The value drivers
    @constraint:Array {maxLength: 100}
    ValueDriver[] valueDrivers;
    # The authorizations
    Authorization[] authorizations;
    # The description
    string description?;
    # The sri
    string sri;
    # The type
    InitiativeType 'type;
    # The date updated
    OffsetDateTime dateUpdated;
    # The date created
    OffsetDateTime dateCreated;
    # The created by
    UserInfo createdBy;
    # The name
    string name;
    # The last activity
    OffsetDateTime lastActivity;
    # The unique identifier
    UUID id;
    # The start date
    OffsetDateTime startDate?;
    # The status
    InitiativeStatus status;
};

# Represents the cases case number resource attribute.
public type CasesCaseNumberResourceAttribute int:Signed32?;

# Represents the Queries record for the operation: queryEntitySet
public type QueryEntitySetQueries record {
    # Not implemented
    @http:Query {name: "$deltatoken"}
    string dollarDeltatoken?;
    # A positive integer value that specifies the maximum number of entries to return, reduced by the value of skiptoken
    @http:Query {name: "$top"}
    int dollarTop?;
    # A filter expression that all entries in the result set must match
    @http:Query {name: "$filter"}
    string dollarFilter?;
    # An opaque value that enables consistent pagination of results. Included in the value of the `@odata.nextLink` parameter of a paginated OData result response
    @http:Query {name: "$skiptoken"}
    string dollarSkiptoken?;
    # Not implemented
    @http:Query {name: "$orderby"}
    string dollarOrderby?;
    # Not implemented
    @http:Query {name: "$search"}
    string dollarSearch?;
    # Not implemented
    @http:Query {name: "$expand"}
    string dollarExpand?;
    # A positive integer value that specifies the number of entries to skip before returning the remainder
    @constraint:Int {minValue: 0}
    int skip?;
    # Requested response format from the client.
    # If specified, `$format` overrides any value specified in the `Accept` header,
    # based on the OData specification 4.0.
    # 
    # Currently only `application/json` is supported
    @http:Query {name: "$format"}
    string dollarFormat?;
    # System query option `inlinecount`.
    # 
    # If specified, then the server will return the number of entries as an integer
    @http:Query {name: "$count"}
    boolean dollarCount?;
    # Not implemented
    @http:Query {name: "$id"}
    string dollarId?;
    # The list of properties that each returned entry will specify
    @http:Query {name: "$select"}
    string[] dollarSelect;
};

# Represents the tasks case resource attribute.
public type TasksCaseResourceAttribute CasesResourceReference;

# Represents the Headers record for the operation: getCaseCreator
public type GetCaseCreatorHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

# Represents the Headers record for the operation: listCaseVariableCases
public type ListCaseVariableCasesHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

# Represents the files resource reference.
public type FilesResourceReference record {
    # The JSON:API resource ID
    FilesIdResourceAttribute id;
    # The JSON:API resource type (Files)
    "Files" 'type;
};

# Represents the meta info request.
public type MetaInfoRequest record {
    # JSON string representing stencilset bindings
    string stencilsetBindings;
    # Parent path of the meta information
    string parent;
    # German name of the meta information
    @jsondata:Name {value: "name_de_de"}
    string nameDeDe?;
    # English description of the meta information
    @jsondata:Name {value: "description_en_gb"}
    string descriptionEnGb?;
    # Spanish description of the meta information
    @jsondata:Name {value: "description_es_es"}
    string descriptionEsEs?;
    # Name of the meta information
    string name;
    # Spanish name of the meta information
    @jsondata:Name {value: "name_es_es"}
    string nameEsEs?;
    # German description of the meta information
    @jsondata:Name {value: "description_de_de"}
    string descriptionDeDe?;
    # Indicates if it is a glossary definition
    boolean isGlossaryDefinition;
    # English name of the meta information
    @jsondata:Name {value: "name_en_gb"}
    string nameEnGb?;
    # Type of the meta information
    string 'type;
};

# Represents the Queries record for the operation: listUsers
public type ListUsersQueries record {
    # Max number of items
    @http:Query {name: "page[limit]"}
    int pageLimit = 100;
    # Page offset
    @http:Query {name: "page[offset]"}
    int pageOffset = 0;
    # Filter by id (csv)
    @http:Query {name: "filter[id]"}
    string filterId?;
};

# Represents the case variables case resource attribute.
public type CaseVariablesCaseResourceAttribute CasesResourceReference;

# Represents the Headers record for the operation: listUsers
public type ListUsersHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

# Represents the v1modelmodel idrevisions rep.
public type V1modelmodelIdrevisionsRep record {
    # The rev
    int rev?;
    # The size
    int size?;
    # The author
    string author?;
    # The author name
    string authorName?;
    # The created
    string created?;
    # The is deployed
    boolean isDeployed?;
    # The comment
    string comment?;
    # The author company
    string authorCompany?;
    # The status
    string status?;
};

# Represents the model revisions response.
public type ModelRevisionsResponse record {
    # The relation type
    string rel?;
    # The hypermedia link
    string href?;
    # The representation payload
    V1modelmodelIdrevisionsRep rep?;
};

# Represents the cases priority resource attribute.
public type CasesPriorityResourceAttribute int:Signed32?;

# Represents the Headers record for the operation: listDictionaryEntries
public type ListDictionaryEntriesHeaders record {
    # application/x-www-form-urlencoded
    @http:Header {name: "Content-Type"}
    string contentType = "application/x-www-form-urlencoded";
};

# Represents the insight initiatives items string.
@constraint:String {pattern: re `[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}`}
public type InsightInitiativesItemsString string;

# Represents the model representation.
public type ModelRepresentation record {
    # The allowed mime type regex
    string allowedMimeTypeRegex?;
    # The deleted
    boolean deleted?;
    # The visible
    boolean visible?;
    # The created
    string created?;
    # The name
    string name?;
    # The description
    string description?;
    # The type
    string 'type?;
    # The sending interval
    string sendingInterval?;
    # The name en
    @jsondata:Name {value: "name_en"}
    string nameEn?;
};

# Represents the cases milestone resource attribute.
public type CasesMilestoneResourceAttribute string?;

# Represents the case variables resource attributes.
public type CaseVariablesResourceAttributes record {
    # The attributes
    CaseVariablesResourceAttributesAttributes attributes?;
};

# Represents the Queries record for the operation: listGroups
public type ListGroupsQueries record {
    # Max number of items
    @http:Query {name: "page[limit]"}
    int pageLimit = 100;
    # groups relationships to include (csv)
    string include = "users";
    # Page offset
    @http:Query {name: "page[offset]"}
    int pageOffset = 0;
    # groups fields to include (csv)
    string fields = "id,name,users";
    # Filter by id (csv)
    @http:Query {name: "filter[id]"}
    string filterId?;
};

# The JSON:API resource ID
public type UsersIdResourceAttribute record {
    # The date
    string date?;
    # The timestamp (epoch seconds)
    int:Signed32 timestamp?;
};

# Represents the asset.
public type Asset record {
    # The initiative
    Initiative initiative;
    # The updated by
    UserInfo updatedBy?;
    # The date created
    OffsetDateTime dateCreated;
    # The created by
    UserInfo createdBy;
    # The name
    @constraint:String {pattern: re `\S`}
    string name;
    # The description
    string description?;
    # The unique identifier
    UUID id;
    # The type
    AssetType 'type;
    # The url
    string url;
    # The date updated
    OffsetDateTime dateUpdated;
};

# Represents the Queries record for the operation: updateModel
public type UpdateModelQueries record {
    # A timestamp or unique string used to prevent caching issues
    @http:Query {name: "_dc"}
    string dc?;
};

# Represents the case variables id resource attribute caze id.
public type CaseVariablesIdResourceAttributeCazeId record {
    # The date
    string date?;
    # The timestamp (epoch seconds)
    int:Signed32 timestamp?;
};

# Represents the dmn download link response.
public type DmnDownloadLinkResponse record {
    # The relation type
    string rel?;
    # The hypermedia link
    string href?;
    # The representation payload
    DmnDownloadRepresentation rep?;
};

# Represents the success response.
public type SuccessResponse record {
    # The success
    boolean success?;
};

# Represents the cases resource reference response schema.
public type CasesResourceReferenceResponseSchema record {
    # The data
    CasesResourceReference data?;
};

# Represents the messages.
public type Messages MessagesInner[];

# Represents the v1modelmodel idinfo status.
public type V1modelmodelIdinfoStatus record {
    # The deleted
    boolean deleted?;
    # The approve
    boolean approve?;
    # The publish
    boolean publish?;
    # The unique identifier
    string id?;
};

# Represents the Headers record for the operation: getTask
public type GetTaskHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

# Represents the users email resource attribute.
public type UsersEmailResourceAttribute string?;

# Represents the meta response item rep.
public type MetaResponseItemRep record {
    # The glossary bindings
    record {}[] glossaryBindings?;
    # The line wrap
    boolean lineWrap?;
    # The default value
    string defaultValue?;
    # The length
    int length?;
    # The description
    string description?;
    # The is glossary definition
    boolean isGlossaryDefinition?;
    # The name en gb
    @jsondata:Name {value: "name_en_gb"}
    string nameEnGb?;
    # The type
    string 'type?;
    # The is list
    boolean isList?;
    # The multilanguage
    boolean multilanguage?;
    # The stencilset bindings
    StencilsetBinding[] stencilsetBindings?;
    # The name de de
    @jsondata:Name {value: "name_de_de"}
    string nameDeDe?;
    # The readonly
    boolean 'readonly?;
    # The name
    string name?;
    # The unique identifier
    string id?;
};

# Represents the files name resource attribute.
public type FilesNameResourceAttribute string?;

# Represents the Queries record for the operation: getUser
public type GetUserQueries record {
    # users fields to include (csv)
    string fields = "id,name,email";
};

# Represents the dmn download representation.
public type DmnDownloadRepresentation record {
    # The success
    boolean success?;
    # The download url
    string downloadUrl?;
    # The messages
    string[] messages?;
};

# Represents the cases resource reference.
public type CasesResourceReference record {
    # The JSON:API resource ID
    CasesIdResourceAttribute id;
    # The JSON:API resource type (Cases)
    "Cases" 'type;
};

# `OdataOutput` represents an OData document according to version 4.0 of the
# [JSON format specification](http://docs.oasis-open.org/odata/odata-json-format/v4.0/odata-json-format-v4.0.html).
# It can serialized into a JSON
public type OdataOutput record {
    # A link to the next page of results
    @jsondata:Name {value: "@odata.nextLink"}
    string? atOdataNextLink?;
    # The total number of entities matching the request
    @jsondata:Name {value: "@odata.count"}
    int? atOdataCount?;
    # The OData context URL for the response
    @jsondata:Name {value: "@odata.context"}
    string atOdataContext;
    # The value of the item
    anydata[] value;
};

# Represents the groups resource attributes attributes.
public type GroupsResourceAttributesAttributes record {
    # The name
    GroupsNameResourceAttribute? name?;
    # The users
    GroupsUsersResourceAttribute? users?;
};

# Represents the Queries record for the operation: getRevisionBpmnXml
public type GetRevisionBpmnXmlQueries record {
    # Whether to include linked subprocesses
    boolean exportSubprocesses?;
    # Which tenant content language to use as the primary language of the exported XML
    string language?;
};

# Represents the messages inner.
public type MessagesInner record {
    # Additional details for this message
    record {}[] details?;
    # The message itself
    string 'type?;
};

# Represents the Headers record for the operation: listCaseVariableCaseRefs
public type ListCaseVariableCaseRefsHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

# Represents the tasks resource response schema.
public type TasksResourceResponseSchema record {
    *Success;
    # The data
    TasksResourceSchema data;
};

# Represents the groups name resource attribute.
public type GroupsNameResourceAttribute string?;

# Represents the Queries record for the operation: listDictionaryEntries
public type ListDictionaryEntriesQueries record {
    # Filters by a full-text search term (ignored when `letter` is specified)
    string q?;
    # If set to `all`, dictionary entries from a category and its subcategories are listed
    string include?;
    # The number of entries to skip before returning entries. Useful in combination with `limit` for pagination
    int offset?;
    # Filters by the initial letter of the dictionary entry's title
    string letter?;
    # The maximum number of entries to return
    int 'limit?;
    # If set to `title`, sorts entries by title; otherwise, the search sorts results by a dynamically determined relevance score
    string sort?;
    # Filters by entry type - `ORG_UNIT`, `DOCUMENT`, `ACTIVITY`, `STATE`, or `IT_SYSTEM`, representing the pre-defined dictionary categories "Organizational Units", "Documents", "Activities",  "Events", and "IT Systems", respectively, or a Dictionary  category's ID
    string category?;
};

# Represents the Queries record for the operation: deleteDictionaryCategory
public type DeleteDictionaryCategoryQueries record {
    # If set to `true`, before deleting the category with  all its sub-categories, the content is moved to the 'Others'  category. Otherwise, sub-categories and all contained dictionary  entries and the sub-categories' contained dictionary entries will  be deleted
    boolean moveContent;
};

# Represents the authorization.
public type Authorization record {
    # The role
    Role role;
    # The target type
    AuthorizationType targetType;
    # The target
    AuthorizationTargetInfo target;
};

# An entry in the OData service document.
# Details can be found in the
# [OData JSON specification](https://docs.oasis-open.org/odata/odata-json-format/v4.0/odata-json-format-v4.0.html#_Toc453766639)
public type ServiceDocumentEntity record {
    # The kind of the item
    string kind;
    # The name of the item
    string name;
    # The URL of the item
    string url;
};

# Represents the tasks application link resource attribute.
public type TasksApplicationLinkResourceAttribute string?;

# Represents the hyper media object.
public type HyperMediaObject record {
    # The relation type
    string rel?;
    # The hypermedia link
    string href?;
    // The real API returns an object shape for `dir`/`mod`/`glos` entries, but an
    // array (or empty array) for hypermedia-relation entries like `priv`/`parents`
    // - `json` is used rather than `record {}` to accept both.
    # The representation payload
    json rep?;
};

# Represents the authorization target info.
public type AuthorizationTargetInfo record {
    # The display name
    string displayName?;
    # The unique identifier
    UUID id;
};

# Represents the Queries record for the operation: search
public type SearchQueries record {
    # The search term
    string q;
    # List of content types the search should include, from `MODEL`, `MODEL_REVISION`, `SHAPE`, `FILE`, `FILE_REVISION`, `DIR` and `COMMENT`
    string types?;
    # Index of first search result to return
    string offset?;
    # e.g. explorer
    string contentmode?;
    # Maximum number of search results, up to 250
    string 'limit?;
    # Example: [{"id":"search.searchableFields.all","textQueries":[{"matching":"contains","text":"foo-bar"}]}]
    @http:Query {name: "fields_json"}
    string fieldsJson?;
};

# Represents the cases name resource attribute.
public type CasesNameResourceAttribute string?;

# Represents the Queries record for the operation: getFile
public type GetFileQueries record {
    # files fields to include (csv)
    string fields = "id,name,size";
};

# Represents the tasks name resource attribute.
public type TasksNameResourceAttribute string?;

# Represents the Queries record for the operation: listInsightsInInitiative
public type ListInsightsInInitiativeQueries record {
    # Page number (1-based, the first page has number 1)
    @constraint:Int {minValue: 1}
    int:Signed32 pageNumber = 1;
    # Only list insights that contain this substring. This parameter can be repeated
    string nameContains?;
    # Only list insights containing discoveries from process intelligence with this canvas type. This parameter can be repeated
    "INVESTIGATION"|"DASHBOARD" processIntelligenceCanvasType?;
    # Only list insights containing this value driver. This parameter can be repeated
    "IT_CAPACITY_PLANNING"|"IMPROVE_DEMAND_FORECAST_ACCURACY"|"IMPROVE_ON_TIME_DELIVERY"|"IMPROVE_FTE_PRODUCTIVITY"|"IMPROVE_USER_COMPLIANCE"|"INCREASE_CASH_FORECAST_ACCURACY"|"INCREASE_DAYS_PAYABLES"|"INCREASE_EFFECTIVENESS_MARKETING"|"OPERATIONAL_EXCELLENCE"|"REDUCE_HR_MANUAL_TRANSACTION"|"REDUCE_ASSET_COST"|"REDUCE_CUSTOMER_CHURN"|"REDUCE_DATA_MANAGEMENT_COST"|"REDUCE_DAYS_IN_INVENTORY"|"REDUCE_DAYS_SALES"|"REDUCE_DAYS_CLOSE_ANNUAL_BOOKS"|"REDUCE_FINANCE_COST"|"REDUCE_MANUFACTURING_CYCLE_TIME"|"REDUCE_READING_TO_INVOICE_TIME"|"REDUCE_NON_COMPLIANT_SERVICES"|"REDUCE_SUPPLY_CHAIN_PLANNING_COST"|"REDUCE_REVENUE_LOSS"|"REDUCE_SALES_COSTS"|"REDUCE_SERVICE_SUPPORT_COST"|"REDUCE_TIME_TO_FILL"|"REDUCE_TIME_TO_MARKET"|"REDUCE_LOGISTICS_COST"|"REDUCE_MANUFACTURING_COSTS"|"REDUCE_UNPLANNED_DOWNTIME"|"REDUCE_UNCOLLECTIBLE_ACCOUNTS" valueDriver?;
    # Only list insights containing discoveries with this domain application. This parameter can be repeated
    "PROCESS_MANAGER"|"PROCESS_INTELLIGENCE"|"PROCESS_INSIGHTS"|"BENCHMARKING_ANALYTICS"|"JOURNEY_MODELER"|"SUITE_CAPABILITIES"|"PROCESS_GOVERNANCE" discoveryReferenceApplication?;
    # Only list insights containing discoveries from process insights with this process flow id. This parameter can be repeated
    string processInsightsProcessFlowId?;
    # Number of entries per page
    @constraint:Int {minValue: 1}
    int:Signed32 pageSize = 10;
    # Only list insights containing discoveries from process intelligence with this widget id. This parameter can be repeated
    string processIntelligenceWidgetId?;
    # Only list insights containing discoveries from process intelligence with this process id. This parameter can be repeated
    string processIntelligenceProcessId?;
    # Only list insights which were created by this user. This parameter can be repeated
    @constraint:String {pattern: re `[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}`}
    string createdBy?;
    # Only list insights containing discoveries from process insights with this system id. This parameter can be repeated
    @constraint:String {pattern: re `[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}`}
    string processInsightsSystemId?;
    # Order to sort the initiatives by
    "Ascending"|"Descending" sortOrder = "Ascending";
    # Only list insights containing discoveries from process intelligence with this canvas id. This parameter can be repeated
    string processIntelligenceCanvasId?;
    # Initiative property to sort by
    "dateCreated"|"dateUpdated"|"name"|"impactScore"|"effortScore"|"priorityScore" sortBy = "dateCreated";
    # Only list insights which contain this tag. This parameter can be repeated
    @constraint:String {pattern: re `[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}`}
    string tag?;
    # Only list insights which are assigned to this user. This parameter can be repeated
    @constraint:String {pattern: re `[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}`}
    string assignee?;
    # Only list insights containing discoveries with this SRI. This parameter can be repeated
    @constraint:String {pattern: re `[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}`}
    string discoveryReferenceSRI?;
    # Only list insights with this status. This parameter can be repeated
    "OPEN"|"IN_PROGRESS"|"RESOLVED" status?;
};

# Represents the cases created resource attribute.
public type CasesCreatedResourceAttribute int?;

# Represents the diagram draft response.
public type DiagramDraftResponse record {
    # The unique identifier
    string id?;
};

# Represents the cases resource schema.
public type CasesResourceSchema record {
    *CasesResourceReference;
    *CasesResourceAttributes;
    # The attributes
    CasesResourceAttributesAttributes attributes;
    # The relationships
    record {} relationships?;
    # The links
    record {} links?;
};

# Represents the dictionary category request.
public type DictionaryCategoryRequest record {
    # A HEX color to display with the category, for example `#800000` (dark red)
    string color;
    # If set to `true`, the category will be invisible to all users
    boolean hidden?;
    # If set to `true`, the category may only be accessible to users who own a specific privilege
    boolean restricted?;
    # The category's name
    string name;
    # The category's parent category. Leave the parameter unset to create the category on the top-most level
    string parentCategory;
    # The order the category will take among categories within the same context
    int 'order;
};

# Represents the expiration date.
public type ExpirationDate record {
    # The re approval date
    @constraint:String {pattern: re `[0-9]{4}/[0-9]{2}/[0-9]{2}`}
    string reApprovalDate?;
};

# Represents the tasks completed resource attribute.
public type TasksCompletedResourceAttribute int?;

# Represents the dictionary entry request.
public type DictionaryEntryRequest record {
    # Add a single attachment as an object. For multiple attachments, add them as an array of objects:
    # ```
    #   [
    #     {"url":"http://www.example.com", "label":"Example"}
    #   ]
    # ```
    Spmv1glossaryAttachments[] attachments?;
    # A JSON object containing ID-to-value mappings of custom  attributes, for example:
    # ```
    #   {
    #     "meta-my-single-line-text": "one",
    #     "meta-my-multi-line-text": "two\nthree\nfour",
    #     "meta-my-dictionary-link": "/glossary/3aabd26a654c4123a71c597210810000",
    #     "meta-my-date": "2018-12-24T16:46:00.000Z",
    #     "meta-my-number": "42",
    #     "meta-my-drop-down": "ci1545668214217710650210",
    #     "meta-my-url": {
    #       "label": "Example",
    #       "url": "http://www.example.com/"
    #     },
    #     "meta-my-boolean": true
    #   }
    # ```
    record {} metaDataValues?;
    # A description of the entry
    string description?;
    # The entry's title
    string title;
    # The desired dictionary category's ID
    string category;
};

# Represents the tag.
public type Tag record {
    # The date created
    OffsetDateTime dateCreated;
    # The unique identifier
    UUID id;
    # The label
    @constraint:String {pattern: re `\S`}
    string label;
    # The date updated
    OffsetDateTime dateUpdated;
};

# Represents the Queries record for the operation: getCaseCreator
public type GetCaseCreatorQueries record {
    # users fields to include (csv)
    string fields = "id,name,email";
};

# Represents the Queries record for the operation: listCaseVariableCaseRefs
public type ListCaseVariableCaseRefsQueries record {
    # cases relationships to include (csv)
    string include = "creator,tasks,variables";
    # cases field to include
    string 'field = "id,creator";
};

# Represents the Queries record for the operation: getGroup
public type GetGroupQueries record {
    # groups relationships to include (csv)
    string include = "users";
    # groups fields to include (csv)
    string fields = "id,name,users";
};

# Represents the Queries record for the operation: listInitiatives
public type ListInitiativesQueries record {
    # Full-text search query for initiative name and description. Minimum 3 characters required; shorter queries are ignored
    string search?;
    # Page number (1-based, the first page has number 1)
    @constraint:Int {minValue: 1}
    int:Signed32 pageNumber = 1;
    # Only list initiatives that contain this substring. This parameter can be repeated
    string nameContains?;
    # Only list initiatives containing this value driver. This parameter can be repeated
    ValueDriver valueDriver?;
    # Only list initiatives which were created by this user. This parameter can be repeated
    UUID createdBy?;
    # Only list initiatives where the user has the specified access role. This parameter can be repeated
    Role authorizationRole?;
    # Order to sort the initiatives by
    "Ascending"|"Descending" sortOrder = "Ascending";
    # Only list initiatives which this user is a member. This parameter can be repeated
    UUID hasMember?;
    # Number of entries per page
    @constraint:Int {minValue: 1, maxValue: 100}
    int:Signed32 pageSize = 10;
    # Initiative property to sort by
    "dateCreated"|"dateUpdated"|"name"|"startDate"|"endDate"|"lastActivity"|"numberOfInsights" sortBy = "dateCreated";
    # Only list initiatives with this status. This parameter can be repeated
    InitiativeStatus status?;
};

# Represents the incoming insight.
public type IncomingInsight record {
    # The name
    string name;
    # The value drivers
    @constraint:Array {maxLength: 100}
    InsightsValueDriver[] valueDrivers;
    # The priority score
    float priorityScore;
    # The authorizations
    @constraint:Array {maxLength: 100, minLength: 1}
    IncomingAuthorization[] authorizations;
    # The description
    string description?;
    # The initiatives
    @constraint:Array {maxLength: 100}
    IncomingInsightInitiativesItemsString[] initiatives?;
    # The assignees
    @constraint:Array {maxLength: 1}
    IncomingInsightAssigneesItemsString[] assignees;
    # The effort score
    float effortScore;
    # The impact score
    float impactScore;
    # The status
    InsightStatus status;
};

# Represents the Headers record for the operation: getDictionaryEntryInfo
public type GetDictionaryEntryInfoHeaders record {
};

# Represents the syntax check response.
public type SyntaxCheckResponse record {
    # The relation type
    string rel?;
    # The hypermedia link
    string href?;
    # The representation payload
    SyntaxCheckRepresentation[] rep?;
};

# Represents the files size resource attribute.
public type FilesSizeResourceAttribute int:Signed32;

# The JSON:API resource ID
public type GroupsIdResourceAttribute record {
    # The date
    string date?;
    # The timestamp (epoch seconds)
    int:Signed32 timestamp?;
};

# Represents the case variables resource attributes attributes.
public type CaseVariablesResourceAttributesAttributes record {
    # The values
    CaseVariablesValuesResourceAttribute? values?;
    # The name
    CaseVariablesNameResourceAttribute? name?;
    # The default values
    CaseVariablesDefaultValuesResourceAttribute? defaultValues?;
    # The description
    CaseVariablesDescriptionResourceAttribute? description?;
    # The variable id
    CaseVariablesVariableIdResourceAttribute? variableId?;
    # The case
    CaseVariablesCaseResourceAttribute case?;
};

# Represents the Headers record for the operation: createDictionaryEntry
public type CreateDictionaryEntryHeaders record {
};

# The data required to publish or unpublish an item; only models and files can be published
public type PublishData record {
    # The mode of the item
    "publish"|"unpublish" mode;
    # The associated models
    ObjectReference[] models;
};

# Represents the stencilset binding.
public type StencilsetBinding record {
    # The namespace
    string namespace?;
    # The stencil
    string stencil?;
    # The order
    int 'order?;
};

# This object can contain dynamic localized 'name' variants with the locale as a suffix of the attribute, e.g. name_fr_fr, name_en_us, name_de_de, etc
public type RenameDirectoryData record {
    # The name of the item
    string name;
    # A description of the item
    string description;
};

# Represents the model request.
public type ModelRequest record {
    # The json xml
    @jsondata:Name {value: "json_xml"}
    string jsonXml?;
};

# Represents the Headers record for the operation: listGroupUserRefs
public type ListGroupUserRefsHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

# Represents the upload schema and data response dto.
public type UploadSchemaAndDataResponseDto record {
    # The execution id
    string executionId;
};

# Represents the pagination.
public type Pagination record {
    # The next page of data
    string? next?;
    # The last page of data
    string? last?;
    # The previous page of data
    string? prev?;
    # The first page of data
    string? first?;
};

# Represents the Headers record for the operation: listCases
public type ListCasesHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

# An OData service document.
# Details can be found in the
# [ OData JSON specification](https://docs.oasis-open.org/odata/odata-json-format/v4.0/odata-json-format-v4.0.html#_Toc453766639)
# Can be serialized into JSON
public type ServiceDocument record {
    # The OData context URL for the response
    @jsondata:Name {value: "@odata.context"}
    string atOdataContext;
    # The value of the item
    ServiceDocumentEntity[] value;
};

# Represents the case variables variable id resource attribute.
public type CaseVariablesVariableIdResourceAttribute string?;

# Represents the UUID.
@constraint:String {pattern: re `[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}`}
public type UUID string;

# Represents the insight status.
public type InsightStatus "OPEN"|"IN_PROGRESS"|"RESOLVED";

# Represents the Headers record for the operation: listFiles
public type ListFilesHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

# Represents the files resource response schema.
public type FilesResourceResponseSchema record {
    *Success;
    # The data
    FilesResourceSchema data;
};

# Represents the meta response item.
public type MetaResponseItem record {
    # The relation type
    string rel?;
    # The hypermedia link
    string href?;
    # The representation payload
    MetaResponseItemRep rep?;
};

# Represents the Headers record for the operation: getUser
public type GetUserHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

# Represents the syntax check request.
public type SyntaxCheckRequest record {
    # The resource
    string 'resource?;
    # The ns
    string ns?;
    # The is json
    boolean isJson?;
    # The context
    string context?;
    # JSON representation of your model as a string
    @jsondata:Name {value: "data_json"}
    string dataJson?;
};

# Represents the success included.
public type SuccessIncluded record {
    # The attributes
    record {} attributes?;
    # The JSON:API resource ID
    string id?;
    # The JSON:API resource type
    string 'type?;
};

# Represents the tasks resource schema.
public type TasksResourceSchema record {
    *TasksResourceReference;
    *TasksResourceAttributes;
    # The attributes
    TasksResourceAttributesAttributes attributes;
    # The relationships
    record {} relationships?;
    # The links
    record {} links?;
};

# Represents the case variables default values resource attribute.
public type CaseVariablesDefaultValuesResourceAttribute record {}[]?;

# Represents the case variables description resource attribute.
public type CaseVariablesDescriptionResourceAttribute string?;

# Represents the objective.
public type Objective record {
    # Date and time when the objective was created
    OffsetDateTime dateCreated;
    # Name of the objective
    string name;
    # Detailed description of the objective
    string description?;
    # Additional objective attributes as raw JSON
    anydata[] attributes;
    # Unique string identifier (sId) of the objective matching ^([A-Z][a-z]+)+_.+$
    @constraint:String {pattern: re `^([A-Z][a-z]+)+_.+$`}
    string sId;
    # Date and time when the objective was last updated
    OffsetDateTime dateUpdated;
};

# Represents the case variables name resource attribute.
public type CaseVariablesNameResourceAttribute string?;

# This object can contain dynamic localized 'name' variants with the locale as a suffix of the attribute, e.g. name_fr_fr, name_en_us, name_de_de, etc
public type DirectoryInfo record {
    # The identifier of the parent item
    ObjectReference parent?;
    # A regular expression describing the allowed MIME types
    string allowedMimeTypeRegex?;
    # The name of the parent item
    string parentName?;
    # Whether the item has been deleted
    boolean deleted?;
    # Whether the item is visible
    boolean visible?;
    # The time of creation. Dates are expressed according to ISO 8601,  with a space as separator and with timezone,  example: "2024-02-26 14:21:35 +0000"
    @constraint:String {pattern: re `^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} \+\d{4}$`}
    string created?;
    # The name of the item
    string name;
    # A description of the item
    string description?;
};

# Represents the process intelligence context.
public type ProcessIntelligenceContext record {
    # The canvas id
    @constraint:String {maxLength: 40}
    string canvasId?;
    # The process id
    @constraint:String {maxLength: 40}
    string processId?;
    # The widget id
    @constraint:String {maxLength: 40}
    string widgetId?;
    # The canvas type
    ProcessIntelligenceCanvasType canvasType?;
};

# Represents the cases resource response schema.
public type CasesResourceResponseSchema record {
    *Success;
    # The data
    CasesResourceSchema data;
};

# Represents the tasks resource references response schema.
public type TasksResourceReferencesResponseSchema record {
    # The data
    TasksResourceReference[] data?;
};

# Represents the execution status dto.
public type ExecutionStatusDto record {
    # The display status
    string displayStatus;
    # The message
    string message;
    # The status
    "REQUEST_VALIDATING"|"REQUEST_VALIDATED"|"REQUEST_VALIDATION_FAILED"|"FILE_CONVERTING"|"FILE_CONVERTED"|"FILE_CONVERSION_FAILED"|"FILE_UPLOADING"|"FILE_UPLOADED"|"FILE_UPLOAD_FAILED"|"INTERNAL_SYNCHRONISING"|"INTERNAL_SYNCHRONISING_FAILED"|"COMPLETED" status;
};

# Represents the tasks created resource attribute.
public type TasksCreatedResourceAttribute int?;

# Represents the Headers record for the operation: authenticate
public type AuthenticateHeaders record {
    # Required request body format
    @http:Header {name: "Content-Type"}
    string contentType?;
};

# Represents the case variables resource references response schema.
public type CaseVariablesResourceReferencesResponseSchema record {
    # The data
    CaseVariablesResourceReference[] data?;
};

# Represents the incoming authorization.
public type IncomingAuthorization record {
    # The role
    Role role;
    # The target id
    UUID targetId;
    # The target type
    AuthorizationType targetType;
};

# Represents the groups resource attributes.
public type GroupsResourceAttributes record {
    # The attributes
    GroupsResourceAttributesAttributes attributes?;
};

# Represents the Queries record for the operation: getCaseVariable
public type GetCaseVariableQueries record {
    # case-variables relationship to include
    string include = "case";
};

# Represents the Queries record for the operation: listGroupUsers
public type ListGroupUsersQueries record {
    # users fields to include (csv)
    string fields = "id,name,email";
};

# Represents the discovery reference.
public type DiscoveryReference record {
    # The benchmarking analytics context
    BenchmarkingAnalyticsContext benchmarkingAnalyticsContext?;
    # The date created
    OffsetDateTime dateCreated;
    # The end date
    OffsetDateTime endDate?;
    # The process intelligence context
    ProcessIntelligenceContext processIntelligenceContext?;
    # The process insights context
    ProcessInsightsContext processInsightsContext?;
    # The unique identifier
    UUID id;
    # The sri
    @constraint:String {pattern: re `\S`}
    string sri;
    # The additional context
    record {|string...;|} additionalContext?;
    # The url
    string url?;
    # The start date
    OffsetDateTime startDate?;
    # The date updated
    OffsetDateTime dateUpdated;
};

# Represents the Queries record for the operation: getBpmnXml
public type GetBpmnXmlQueries record {
    # Whether to include linked subprocesses
    boolean exportSubprocesses?;
    # Which tenant content language to use as the primary language of the exported XML
    string language?;
};

# Represents the initiative status.
public type InitiativeStatus "TODO"|"PLANNING"|"IN_PROGRESS"|"AT_RISK"|"COMPLETED"|"ARCHIVED";

# Represents the Queries record for the operation: listFiles
public type ListFilesQueries record {
    # Max number of items
    @http:Query {name: "page[limit]"}
    int pageLimit = 100;
    # Page offset
    @http:Query {name: "page[offset]"}
    int pageOffset = 0;
    # Filter by id (csv)
    @http:Query {name: "filter[id]"}
    string filterId?;
};

# Represents the files resource attributes.
public type FilesResourceAttributes record {
    # The attributes
    FilesResourceAttributesAttributes attributes?;
};

# Represents the Queries record for the operation: listInsights
public type ListInsightsQueries record {
    # Page number (1-based, the first page has number 1)
    @constraint:Int {minValue: 1}
    int:Signed32 pageNumber = 1;
    # Only list insights that contain this substring. This parameter can be repeated
    string nameContains?;
    # Only list insights containing discoveries from process intelligence with this canvas type. This parameter can be repeated
    "INVESTIGATION"|"DASHBOARD" processIntelligenceCanvasType?;
    # Only list insights containing this value driver. This parameter can be repeated
    "IT_CAPACITY_PLANNING"|"IMPROVE_DEMAND_FORECAST_ACCURACY"|"IMPROVE_ON_TIME_DELIVERY"|"IMPROVE_FTE_PRODUCTIVITY"|"IMPROVE_USER_COMPLIANCE"|"INCREASE_CASH_FORECAST_ACCURACY"|"INCREASE_DAYS_PAYABLES"|"INCREASE_EFFECTIVENESS_MARKETING"|"OPERATIONAL_EXCELLENCE"|"REDUCE_HR_MANUAL_TRANSACTION"|"REDUCE_ASSET_COST"|"REDUCE_CUSTOMER_CHURN"|"REDUCE_DATA_MANAGEMENT_COST"|"REDUCE_DAYS_IN_INVENTORY"|"REDUCE_DAYS_SALES"|"REDUCE_DAYS_CLOSE_ANNUAL_BOOKS"|"REDUCE_FINANCE_COST"|"REDUCE_MANUFACTURING_CYCLE_TIME"|"REDUCE_READING_TO_INVOICE_TIME"|"REDUCE_NON_COMPLIANT_SERVICES"|"REDUCE_SUPPLY_CHAIN_PLANNING_COST"|"REDUCE_REVENUE_LOSS"|"REDUCE_SALES_COSTS"|"REDUCE_SERVICE_SUPPORT_COST"|"REDUCE_TIME_TO_FILL"|"REDUCE_TIME_TO_MARKET"|"REDUCE_LOGISTICS_COST"|"REDUCE_MANUFACTURING_COSTS"|"REDUCE_UNPLANNED_DOWNTIME"|"REDUCE_UNCOLLECTIBLE_ACCOUNTS" valueDriver?;
    # Only list insights containing discoveries with this domain application. This parameter can be repeated
    "PROCESS_MANAGER"|"PROCESS_INTELLIGENCE"|"PROCESS_INSIGHTS"|"BENCHMARKING_ANALYTICS"|"JOURNEY_MODELER"|"SUITE_CAPABILITIES"|"PROCESS_GOVERNANCE" discoveryReferenceApplication?;
    # Only list insights containing discoveries from process insights with this process flow id. This parameter can be repeated
    string processInsightsProcessFlowId?;
    # Number of entries per page
    @constraint:Int {minValue: 1}
    int:Signed32 pageSize = 10;
    # Only list insights containing discoveries from process intelligence with this widget id. This parameter can be repeated
    string processIntelligenceWidgetId?;
    # Only list insights containing discoveries from process intelligence with this process id. This parameter can be repeated
    string processIntelligenceProcessId?;
    # Only list insights which were created by this user. This parameter can be repeated
    @constraint:String {pattern: re `[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}`}
    string createdBy?;
    # Only list insights containing discoveries from process insights with this system id. This parameter can be repeated
    @constraint:String {pattern: re `[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}`}
    string processInsightsSystemId?;
    # Order to sort the initiatives by
    "Ascending"|"Descending" sortOrder = "Ascending";
    # Only list insights containing discoveries from process intelligence with this canvas id. This parameter can be repeated
    string processIntelligenceCanvasId?;
    # Initiative property to sort by
    "dateCreated"|"dateUpdated"|"name"|"impactScore"|"effortScore"|"priorityScore" sortBy = "dateCreated";
    # Only list insights which contain this tag. This parameter can be repeated
    @constraint:String {pattern: re `[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}`}
    string tag?;
    # Only list insights which are assigned to this user. This parameter can be repeated
    @constraint:String {pattern: re `[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}`}
    string assignee?;
    # Only list insights containing discoveries with this SRI. This parameter can be repeated
    @constraint:String {pattern: re `[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}`}
    string discoveryReferenceSRI?;
    # Only list insights with this status. This parameter can be repeated
    "OPEN"|"IN_PROGRESS"|"RESOLVED" status?;
};

# Represents the process insights context.
public type ProcessInsightsContext record {
    # The system id
    UUID systemId?;
    # The process flow id
    @constraint:String {maxLength: 32}
    string processFlowId?;
    # The context info
    @constraint:String {pattern: re `^[a-zA-Z0-9_\-]{0,10}$`}
    string contextInfo?;
    # The phase id
    @constraint:String {pattern: re `^[a-zA-Z0-9_\-]{0,10}$`}
    string phaseId?;
};

# The JSON:API resource ID
public type TasksIdResourceAttribute record {
    # The date
    string date?;
    # The timestamp (epoch seconds)
    int:Signed32 timestamp?;
};

# Represents the cases resource attributes attributes.
public type CasesResourceAttributesAttributes record {
    # The creator
    CasesCreatorResourceAttribute creator?;
    # The variables
    CasesVariablesResourceAttribute? variables?;
    # The milestone
    CasesMilestoneResourceAttribute? milestone?;
    # The process id
    CasesProcessIdResourceAttribute? processId?;
    # The case number
    CasesCaseNumberResourceAttribute? caseNumber?;
    # The created
    CasesCreatedResourceAttribute? created?;
    # The name
    CasesNameResourceAttribute? name?;
    # The closed
    CasesClosedResourceAttribute? closed?;
    # The priority
    CasesPriorityResourceAttribute? priority?;
    # The tasks
    CasesTasksResourceAttribute? tasks?;
    # The application link
    CasesApplicationLinkResourceAttribute? applicationLink?;
};

# Represents the groups resources response schema.
public type GroupsResourcesResponseSchema record {
    *Success;
    # The data
    GroupsResourceSchema[] data;
};

# Represents the Headers record for the operation: updateDictionaryEntry
public type UpdateDictionaryEntryHeaders record {
};

# Represents the tasks updated resource attribute.
public type TasksUpdatedResourceAttribute int?;

# Represents the Headers record for the operation: getFile
public type GetFileHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

# Represents the Queries record for the operation: createDiagramDraft
public type CreateDiagramDraftQueries record {
    # The notation URI value for the stencil set
    string stencilset;
};

# Represents the move directory request.
public type MoveDirectoryRequest record {
    # The parent
    ObjectReference parent?;
};

# Represents the tasks resource attributes.
public type TasksResourceAttributes record {
    # The attributes
    TasksResourceAttributesAttributes attributes?;
};

# Represents the automatic measurement.
public type AutomaticMeasurement record {
    # The type
    "NPS"|"CSAT"|"CES" 'type;
    # The value
    CesMeasurement|CsatMeasurement|NPSMeasurement value;
};

# Represents the asset type.
public type AssetType "METRICS"|"PROCESS_MODEL"|"JIRA"|"LEANIX"|"SAP_CLOUD_ALM"|"TASK"|"OBJECTIVE"|"KEY_RESULT"|"DASHBOARD"|"INVESTIGATION"|"DOCUMENT"|"FILE"|"IMPROVEMENT_OPPORTUNITY"|"CORRECTION_RECOMMENDATION"|"BLOCKER"|"PROCESS_FLOW"|"OTHER";

# Represents the users resource attributes attributes.
public type UsersResourceAttributesAttributes record {
    # The name
    UsersNameResourceAttribute? name?;
    # The email
    UsersEmailResourceAttribute? email?;
};

# Represents the cases variables resource attribute.
public type CasesVariablesResourceAttribute CaseVariablesResourceReference[]?;

# Represents the Headers record for the operation: getTaskCaseRef
public type GetTaskCaseRefHeaders record {
    # The content type of the request. Use `application/vnd.api+json`.
    @http:Header {name: "Content-Type"}
    "application/vnd.api+json"|"application/json" contentType = "application/vnd.api+json";
};

# Represents the case variables resource schema.
public type CaseVariablesResourceSchema record {
    *CaseVariablesResourceReference;
    *CaseVariablesResourceAttributes;
    # The attributes
    CaseVariablesResourceAttributesAttributes attributes;
    # The relationships
    record {} relationships?;
    # The links
    record {} links?;
};

# Link members related to the primary data
public type Links record {
    *Pagination;
};

# Represents the model info response.
public type ModelInfoResponse record {
    # The parent
    string parent?;
    # The formats
    record {} formats?;
    # The granted revision user
    @jsondata:Name {value: "granted_revision_user"}
    string grantedRevisionUser?;
    # The is licensed stencil set
    boolean isLicensedStencilSet?;
    # The granted revision user name
    @jsondata:Name {value: "granted_revision_user_name"}
    string grantedRevisionUserName?;
    # The description
    string description?;
    # The type
    string 'type?;
    # The sri revision
    @jsondata:Name {value: "sri_revision"}
    string sriRevision?;
    # The sri path
    @jsondata:Name {value: "sri_path"}
    string sriPath?;
    # The number of new comments
    int numberOfNewComments?;
    # The is deployed
    boolean isDeployed?;
    # The granted revision
    @jsondata:Name {value: "granted_revision"}
    string grantedRevision?;
    # The rev
    int rev?;
    # The created
    string created?;
    # The author
    string author?;
    # The granted revision date
    @jsondata:Name {value: "granted_revision_date"}
    string grantedRevisionDate?;
    # The sri
    string sri?;
    # The author company
    string authorCompany?;
    # The revision
    string revision?;
    # The parent name
    string parentName?;
    # The deleted
    boolean deleted?;
    # The author name
    string authorName?;
    # The name
    string name?;
    # The namespace
    string namespace?;
    # The comment
    string comment?;
    # The updated
    string updated?;
    # The status
    V1modelmodelIdinfoStatus status?;
};

# Represents the files resource attributes attributes.
public type FilesResourceAttributesAttributes record {
    # The size
    FilesSizeResourceAttribute size?;
    # The name
    FilesNameResourceAttribute? name?;
};

# Represents the Headers record for the operation: createDictionaryCategory
public type CreateDictionaryCategoryHeaders record {
    # application/x-www-form-urlencoded
    @http:Header {name: "Content-Type"}
    string contentType = "application/x-www-form-urlencoded";
};
